/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
          "error": "#ffb4ab",
          "secondary-container": "#ffdb3c",
          "primary": "#a4c9ff",
          "on-tertiary-fixed-variant": "#910030",
          "on-primary-container": "#fefcff",
          "tertiary-fixed-dim": "#ffb2ba",
          "on-error": "#690005",
          "surface-container-highest": "#353439",
          "inverse-primary": "#005fac",
          "error-container": "#93000a",
          "on-error-container": "#ffdad6",
          "on-background": "#e4e1e7",
          "surface": "var(--surface)",
          "on-tertiary-fixed": "#400011",
          "tertiary-container": "#e31754",
          "on-tertiary-container": "#fffcff",
          "on-tertiary": "#670020",
          "on-primary": "#00315d",
          "inverse-surface": "#e4e1e7",
          "primary-fixed-dim": "#a4c9ff",
          "outline-variant": "#414752",
          "surface-dim": "#131317",
          "surface-container-low": "var(--surface-container-low)",
          "primary-fixed": "#d4e3ff",
          "surface-container-lowest": "#0e0e12",
          "primary-container": "#0176d3",
          "on-surface-variant": "var(--on-surface-variant)",
          "inverse-on-surface": "#303034",
          "secondary-fixed": "#ffe16d",
          "surface-variant": "#353439",
          "surface-container": "var(--surface-container)",
          "background": "var(--background)",
          "tertiary": "#ffb2ba",
          "outline": "#8b919e",
          "on-surface": "var(--on-surface)",
          "secondary-fixed-dim": "#e9c400",
          "on-secondary-fixed-variant": "#544600",
          "surface-tint": "#a4c9ff",
          "on-primary-fixed-variant": "#004884",
          "surface-container-high": "#2a292e",
          "on-secondary": "#3a3000",
          "on-secondary-fixed": "#221b00",
          "on-secondary-container": "#725f00",
          "secondary": "#fff9ef",
          "on-primary-fixed": "#001c39",
          "tertiary-fixed": "#ffd9dc",
          "surface-bright": "#39393d"
      },
      fontFamily: {
          "headline": ["Plus Jakarta Sans"],
          "body": ["Plus Jakarta Sans"],
          "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
