export const AGENTFORCE_TILES = [
  {
    id: 'agentforce-grid',
    symbol: 'Ag',
    name: 'Agentforce Grid',
    label: 'Agentforce Grid',
    icon: 'grid_on',
    accent: '#7B5EA7',
    type: 'standalone',
    tagline: 'Enterprise agent orchestration and deployment.',
    description: 'Central hub for managing and deploying Agentforce agents across your organization.',
    storyline: [
      'Configure agent deployment settings',
      'Monitor active agents across channels',
      'Manage agent lifecycle and updates',
    ],
    specs: {
      availability: 'GA',
      focus: 'Agent orchestration',
    },
    releases: [],
    useCases: ['Multi-agent deployment', 'Enterprise governance', 'Agent lifecycle management'],
  },
  {
    id: 'agentforce-development',
    symbol: 'Ad',
    name: 'Agentforce Development',
    label: 'Agentforce Development',
    icon: 'code',
    accent: '#7B5EA7',
    type: 'parent',
    tagline: 'Build agents with deterministic flows or classic patterns.',
    description: 'Choose between Agent Script for hybrid reasoning or Legacy Builder for traditional flows.',
    storyline: [
      'Select your development approach',
      'Build with deterministic or LLM-driven logic',
      'Deploy to multiple channels',
    ],
    specs: {
      builders: '2 approaches',
      focus: 'Agent authoring',
    },
    releases: [],
    useCases: ['Agent development', 'Multi-channel deployment', 'Hybrid reasoning'],
    children: [
      {
        id: 'agent-script',
        symbol: 'As',
        name: 'Agent Script',
        label: 'Agent Script',
        icon: 'architecture',
        accent: '#7B5EA7',
        type: 'child',
        tagline: 'Deterministic flows plus LLM reasoning inside the Builder.',
        description: 'Design structured agent journeys that combine determinism with reasoning in Agentforce Builder.',
        storyline: [
          'Open Agentforce Studio and create a new agent',
          'Compose deterministic steps with Agent Script reasoning nodes',
          'Preview and validate before publishing to production',
        ],
        specs: {
          availability: 'Beta from December 4, 2025',
          builder: 'New Agentforce Builder',
          model: 'GPT-4.1',
          focus: 'Determinism + LLM reasoning',
        },
        capabilities: {
          channelSupport: [
            { name: 'Email', icon: 'email', accent: '#06A59A', available: true },
            { name: 'Slack', icon: 'chat', accent: '#E01E5A', available: true },
            { name: 'Service Agent', icon: 'support_agent', accent: '#0176D3', available: true },
            { name: 'Employee Agent', icon: 'badge', accent: '#9C27B0', available: true },
            { name: 'Enhanced Chat v2', icon: 'chat_bubble', accent: '#00BFA5', available: true },
            { name: 'Voice', icon: 'phone', accent: '#06A59A', available: false },
          ],
          features: [
            { name: 'Supports RAG', icon: 'library_books', accent: '#FFDB3C', available: true },
            { name: 'Support task resolution', icon: 'task_alt', accent: '#45C65A', available: true },
          ],
        },
        releases: [
      {
        id: 'agent-script-dreamforce-2025',
        title: 'Reveal Agent Script at Dreamforce 2025',
        date: '2025-10-13',
        dateLabel: 'Dreamforce 2025',
        summary:
          'Agent Script debuts inside Agentforce 360 as a new prompting tool that lets builders script "if/then" logic so AI agents stay flexible yet predictable.',
        url: 'https://techcrunch.com/2025/10/13/salesforce-announces-agentforce-360-as-enterprise-ai-competition-heats-up/',
        accent: '#7B5EA7',
        icon: 'flash_on',
      },
      {
        id: 'agent-script-beta-intro',
        title: 'Agent Script beta rolls into Agentforce 360 for hybrid reasoning',
        date: '2025-11-05',
        dateLabel: 'Nov 5, 2025',
        summary:
          'The beta release highlights hybrid reasoning with Agent Script guardrails plus Atlas-powered instructions that transform high-level prompts into deterministic branches.',
        url: 'https://www.salesforce.com/ap/news/press-releases/2025/10/14/welcome-to-the-agentic-enterprise-with-agentforce-360-salesforce-elevates-human-potential-in-the-age-of-ai-2/',
        accent: '#7B5EA7',
        icon: 'rocket_launch',
      },
      {
        id: 'agent-script-builder-beta',
        title: 'Build enterprise-ready agents with the new Agent Script view (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Agentforce Builder\'s Script view documents deterministic steps, quick actions, and topics in one place so reasoning stays predictable.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'developer_mode',
      },
      {
        id: 'agent-script-reasoning-instructions',
        title: 'Reasoning instructions keep Agent Script predictable',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Guardrails let you decide where the LLM can flex and where the agent executes deterministic logic, eliminating surprises in topic transitions.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#reasoning',
        accent: '#7B5EA7',
        icon: 'gavel',
      },
      {
        id: 'agent-script-variables-conditions',
        title: 'Variables and conditions power repeatable decisions',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Store agent state, compare values, and branch to next actions or topics without relying solely on LLM memory.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#expressions',
        accent: '#7B5EA7',
        icon: 'tune',
      },
      {
        id: 'agent-script-combine-determinism',
        title: 'Combine Determinism and LLM Reasoning with Agent Script (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Agent Script introduces deterministic flows blended with LLM reasoning.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_script.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'architecture',
      },
      {
        id: 'agent-script-previews',
        title: 'Confidently Build Agents with In-Depth Agent Previews (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Previews help you understand how Agent Script flows behave.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_test.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'visibility',
      },
      {
        id: 'agent-script-editor-expansion',
        title: 'Canvas, quick actions, and DX editing for Agent Script',
        date: '2026-01-15',
        dateLabel: 'Jan 15, 2026',
        summary:
          'Canvas view summarizes script blocks, slash shortcuts add common expressions, and Agentforce DX/VS Code extensions keep syntax, autocomplete, and validation close at hand.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html',
        accent: '#7B5EA7',
        icon: 'code',
      },
      {
        id: 'agent-script-flow-control',
        title: 'Flow-of-control patterns show how to hand off topics',
        date: '2026-02-05',
        dateLabel: 'Feb 5, 2026',
        summary:
          'New patterns illustrate how to combine deterministic transitions and topic handoffs so the agent always knows the next step.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#flow-of-control',
        accent: '#7B5EA7',
        icon: 'swap_horiz',
      },
      {
        id: 'agent-script-patterns-library',
        title: 'Agent Script patterns and reference guide expand',
        date: '2026-03-01',
        dateLabel: 'Mar 1, 2026',
        summary:
          'The Agent Script documentation now highlights reusable patterns, code examples, and reference tables so builders can copy proven logic quickly.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#patterns',
        accent: '#7B5EA7',
        icon: 'library_books',
      },
    ],
        useCases: ['Deterministic flows', 'Hybrid reasoning', 'Multi-channel support'],
      },
      {
        id: 'legacy-builder',
        symbol: 'Lb',
        name: 'Legacy Builder',
        label: 'Legacy Builder',
        icon: 'handyman',
        accent: '#0176D3',
        type: 'child',
        tagline: 'Classic agent builder for traditional flows.',
        description: 'Track the transition from the Legacy Builder to the modern Agentforce Builder experience.',
        storyline: [
          'Understand where Builder capabilities migrated',
          'Map legacy flows to the new Agent Script structure',
          'Enable the new Builder for your organization',
        ],
        specs: {
          transition: 'Beta + GA',
          model: 'GPT-4o',
          focus: 'Builder migration',
        },
        capabilities: {
          channelSupport: [
            { name: 'Email', icon: 'email', accent: '#06A59A', available: true },
            { name: 'Slack', icon: 'chat', accent: '#E01E5A', available: true },
            { name: 'Service Agent', icon: 'support_agent', accent: '#0176D3', available: true },
            { name: 'Employee Agent', icon: 'badge', accent: '#9C27B0', available: true },
            { name: 'Voice', icon: 'phone', accent: '#06A59A', available: true },
          ],
          features: [
            { name: 'Supports RAG', icon: 'library_books', accent: '#FFDB3C', available: true },
          ],
        },
        releases: [
          {
            id: 'legacy-escalate-reps',
            title: 'Escalate complex employee agent conversations to reps',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'When an employee agent needs human help, escalation routes conversations to the right rep without losing context.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_escalate_conversations_to_reps.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'support_agent',
          },
          {
            id: 'legacy-welcome-recommendations',
            title: 'Customize welcome recommendations in Agentforce Builder',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'Fine-tune the welcome experience so intelligent recommendations greet customers with the right next steps.',
            url: 'https://help.salesforce.com/s/articleView?language=en_US&id=release-notes.rn_einstein_customize_welcome_reco_in_agentforce_builder.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'recommend',
          },
          {
            id: 'legacy-migrate-employee-agent',
            title: 'Easily migrate from Agentforce to an Employee Agent',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'A guided setup flow walks admins through converting a default Agentforce bot into an employee-facing agent.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_easily_migrate_af_to_aea.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'swap_horiz',
          },
          {
            id: 'legacy-enhanced-connections',
            title: 'Easily add agents to multiple channels with enhanced connections setup',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'The new connections panel streamlines attaching Agents to voice, chat, and digital channels from a single place.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_enhanced_connections_panel.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'settings_input_component',
          },
          {
            id: 'legacy-service-email-connection',
            title: 'Deliver emails with the Service Email connection',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary: 'Agentforce Builder now wires email delivery channels into classic service email pipelines.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_email_connection.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'email',
          },
          {
            title: 'New Agentforce Builder Availability in Agentforce Studio',
            date: '2026-02-20',
            dateLabel: 'Feb 20, 2026',
            summary: 'The new Builder lands in Agentforce Studio with usability improvements.',
            url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
            accent: '#0176D3',
            icon: 'new_releases',
          },
          {
            title: 'Build Complex Agents Faster with Canvas View Enhancements',
            date: '2026-01-05',
            dateLabel: 'Week of Jan 5, 2026',
            summary: 'Canvas View upgrades accelerate complex branching.',
            url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
            accent: '#0176D3',
            icon: 'grid_view',
          },
          {
            title: 'Connect Agents to Your Knowledge Sources in the New Builder',
            date: '2026-01-05',
            dateLabel: 'Release 260',
            summary: 'Knowledge connections now live inside the modern Builder.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_data_library_new_builder.htm&release=260&type=5',
            accent: '#0176D3',
            icon: 'book',
          },
        ],
        useCases: ['Legacy agent migration', 'Traditional flows', 'Multi-channel support'],
      },
    ],
  },
  {
    id: 'testing-center',
    symbol: 'Tc',
    name: 'Testing Center',
    label: 'Testing Center',
    icon: 'bug_report',
    accent: '#FFDB3C',
    type: 'standalone',
    tagline: 'Preview and validation are now part of Builder testing.',
    description: 'Capture confidence with testing features such as previews and validation tools.',
    storyline: [
      'Kick off testing cycles inside the Builder',
      'Inspect agent previews before deployment',
      'Validate flows with the new guardrails',
    ],
    specs: {
      focus: 'Previews + Validation',
      status: 'Beta',
    },
    releases: [
      {
        title: 'Build High-Quality Agents with Validation Enhancements (Beta)',
        date: '2026-01-05',
        dateLabel: 'Week of Jan 5, 2026',
        summary: 'Validation tooling ships to harden agent quality.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_builder_validation.htm&release=260&type=5',
        accent: '#FFDB3C',
        icon: 'check_circle',
      },
      {
        title: 'Confidently Build Agents with In-Depth Agent Previews (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Agent previews help test interactions before release.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_test.htm&release=258&type=5',
        accent: '#FFDB3C',
        icon: 'visibility',
      },
    ],
    useCases: ['Agent validation', 'Preview testing', 'Quality assurance'],
  },
  {
    id: 'agentforce-voice',
    symbol: 'Av',
    name: 'Agentforce Voice',
    label: 'Agentforce Voice',
    icon: 'headset_mic',
    accent: '#06A59A',
    type: 'parent',
    tagline: 'AI-powered voice conversations that replace traditional IVR systems.',
    description: 'Enable natural voice interactions powered by Deepgram speech recognition, OpenAI GPT reasoning, and ElevenLabs text-to-speech. Connect to PSTN and SIP telephony networks through Service Cloud Voice integration with partners like Amazon Connect and Genesys Cloud.',
    storyline: [
      'Customer calls your support line via PSTN or SIP',
      'Deepgram transcribes speech to text in real-time',
      'OpenAI GPT via Flash Planner reasons through agent instructions',
      'ElevenLabs converts responses to natural voice',
      'Context-preserving escalation to human agents via Omni-Channel',
    ],
    specs: {
      speechToText: 'Deepgram Nova-2',
      llm: 'OpenAI GPT (Flash Planner)',
      textToSpeech: 'ElevenLabs Turbo v2.5',
      telephony: 'PSTN, SIP',
      language: 'English only',
      concurrentCalls: '500 per org',
      billing: 'Voice Minutes (rounded up per minute)',
      dataRetention: 'Zero retention by all LLM providers',
      release: 'October 2025 (GA)',
    },
    useCases: [
      'Appointment booking and cancellation over the phone',
      'Order status inquiries with real-time data lookup',
      'Account balance and payment questions',
      'Technical support triage before human escalation',
      'Multi-turn conversations with context retention',
      'Context-preserving handoff to live agents',
    ],
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=ai.agentforce_voice.htm&type=5',
      setup: 'https://help.salesforce.com/s/articleView?id=ai.agent_connect_telephony_parent.htm&type=5',
      releaseNotes: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_voice.htm&release=258&type=5',
      devGuide: 'https://developer.salesforce.com/docs/platform/agentforce-partners/guide/agentforce-voice-overview',
      video: 'https://www.youtube.com/results?search_query=salesforce+agentforce+voice',
      partners: 'https://help.salesforce.com/s/articleView?id=ai.agent_connect_telephony_parent.htm&type=5',
      pricing: 'https://www.salesforce.com/products/service-cloud/pricing/',
      trustDocs: 'https://help.salesforce.com/s/articleView?id=ai.trust_agentforce.htm&type=5',
    },
    releases: [
      {
        id: 'agentforce-voice-english-launch',
        title: 'Agentforce Voice launches with English-only support',
        date: '2025-10-13',
        dateLabel: 'Oct 13, 2025',
        summary: 'Agentforce Voice debuts in English so your teams can prototype telephony interactions with Builder agents.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_voice.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'language',
      },
      {
        id: 'agentforce-voice-billing-usage-types',
        title: 'New billable usage types for Agentforce Voice',
        date: '2025-10-24',
        dateLabel: 'Oct 24, 2025',
        summary: 'Define new billing buckets for telephony and track voice usage as part of Agentforce analytics.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_billing_flex_voice_usage_type.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'monetization_on',
      },
      {
        id: 'agentforce-voice-enable-service-agents',
        title: 'Enable voice conversations for Agentforce Service Agents',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary: 'Agentforce Voice now powers service agents that can answer calls, escalate to humans, and keep sessions secure.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_voice.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'support_agent',
      },
      {
        id: 'agentforce-voice-keyterm-prompting',
        title: 'Help your voice-enabled agent recognize key terms',
        date: '2025-12-15',
        dateLabel: 'Week of Dec 15, 2025',
        summary: 'Key-term prompting lets you highlight important phrases so Agentforce Voice senses critical triggers during calls.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_agent_voice_keyterm_prompting.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'settings_voice',
      },
      {
        id: 'agentforce-voice-minutes-usage',
        title: 'Introduce the Agentforce Voice minutes usage type',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Track Agentforce Voice minutes separately to understand telephony spend and optimize workloads.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_billing_voice_minutes.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'timer',
      },
      {
        id: 'agentforce-voice-sip-routing',
        title: 'Route Agentforce Voice calls using SIP',
        date: '2026-03-30',
        dateLabel: 'Mar 30, 2026',
        summary: 'SIP routing gives you flexibility to connect Agentforce Voice into existing telephony carriers.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_voice_with_sip.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'network_cell',
      },
    ],
    children: [
      {
        id: 'voice-engine',
        symbol: 'Ve',
        name: 'Voice Engine',
        label: 'Voice Engine',
        icon: 'record_voice_over',
        accent: '#06A59A',
        type: 'child',
        tagline: 'Speech recognition and synthesis powered by best-in-class AI models.',
        description: 'Agentforce Voice uses Deepgram Nova-2 for speech-to-text transcription, OpenAI GPT via Flash Planner for reasoning, and ElevenLabs Turbo v2.5 for natural text-to-speech. All providers enforce zero data retention policies to protect customer privacy.',
        storyline: [
          'Deepgram Nova-2 transcribes customer speech with 95%+ accuracy',
          'Flash Planner (Atlas reasoning engine) processes intent with OpenAI GPT',
          'Agent Builder instructions guide conversation flow and actions',
          'ElevenLabs Turbo v2.5 synthesizes natural-sounding voice responses',
          'All processing happens in real-time with <500ms latency',
        ],
        specs: {
          stt: 'Deepgram Nova-2',
          llm: 'OpenAI GPT (Flash Planner)',
          tts: 'ElevenLabs Turbo v2.5',
          latency: '<500ms end-to-end',
          accuracy: '95%+ transcription accuracy',
          dataRetention: 'Zero retention (all providers)',
          failover: 'Automatic provider failover',
        },
        useCases: [
          'Real-time speech transcription for multi-turn conversations',
          'Intent recognition and slot filling from natural language',
          'Dynamic response generation based on CRM data',
          'Natural voice synthesis with emotional tone control',
          'Fallback handling when transcription confidence is low',
        ],
        links: {
          docs: 'https://help.salesforce.com/s/articleView?id=ai.agentforce_voice.htm&type=5',
          deepgram: 'https://deepgram.com/product/nova-2',
          openai: 'https://platform.openai.com/docs',
          elevenlabs: 'https://elevenlabs.io/docs',
          privacy: 'https://help.salesforce.com/s/articleView?id=ai.trust_agentforce.htm&type=5',
        },
        capabilities: {
          channelSupport: [
            {
              name: 'PSTN',
              icon: 'phone',
              accent: '#06A59A',
              available: true,
              description: 'Public Switched Telephone Network for traditional phone calls',
              specs: { protocol: 'PSTN', codecs: 'G.711, G.729', quality: 'HD Voice' },
            },
            {
              name: 'SIP',
              icon: 'settings_phone',
              accent: '#06A59A',
              available: true,
              description: 'Session Initiation Protocol for VoIP routing',
              specs: { protocol: 'SIP/2.0', codecs: 'Opus, G.722', quality: 'Wideband' },
            },
            {
              name: 'Amazon Connect',
              icon: 'cloud_circle',
              accent: '#FF9900',
              available: true,
              description: 'AWS-based contact center integration',
              specs: { integration: 'Service Cloud Voice', region: 'Multi-region' },
            },
            {
              name: 'Genesys Cloud',
              icon: 'hub',
              accent: '#FF4F1F',
              available: true,
              description: 'Genesys CCaaS platform integration',
              specs: { integration: 'Service Cloud Voice', deployment: 'Cloud-native' },
            },
          ],
          features: [
            {
              name: 'Speech-to-Text',
              icon: 'mic',
              accent: '#06A59A',
              available: true,
              description: 'Real-time transcription powered by Deepgram Nova-2 with 95%+ accuracy',
              specs: { provider: 'Deepgram Nova-2', latency: '<200ms', accuracy: '95%+' },
            },
            {
              name: 'Large Language Model',
              icon: 'psychology',
              accent: '#06A59A',
              available: true,
              description: 'OpenAI GPT reasoning via Flash Planner (Atlas-like engine)',
              specs: { provider: 'OpenAI GPT', engine: 'Flash Planner', reasoning: 'Atlas-like' },
            },
            {
              name: 'Text-to-Speech',
              icon: 'campaign',
              accent: '#06A59A',
              available: true,
              description: 'Natural voice synthesis with ElevenLabs Turbo v2.5',
              specs: { provider: 'ElevenLabs Turbo v2.5', latency: '<300ms', quality: 'HD' },
            },
            {
              name: 'Failover Strategy',
              icon: 'backup',
              accent: '#06A59A',
              available: true,
              description: 'Automatic provider failover if primary STT/TTS service is unavailable',
              specs: { strategy: 'Multi-provider', detection: 'Health checks', fallback: 'Automatic' },
            },
            {
              name: 'Zero Data Retention',
              icon: 'lock',
              accent: '#06A59A',
              available: true,
              description: 'All external LLM providers enforce zero data retention policies',
              specs: { deepgram: 'No retention', openai: 'No retention', elevenlabs: 'Zero retention mode' },
            },
            {
              name: 'Low Latency Processing',
              icon: 'speed',
              accent: '#06A59A',
              available: true,
              description: 'End-to-end processing under 500ms for natural conversation flow',
              specs: { stt: '<200ms', reasoning: '<100ms', tts: '<300ms', total: '<500ms' },
            },
          ],
        },
        releases: [
          {
            id: 'voice-engine-deepgram-nova2',
            title: 'Deepgram Nova-2 powers speech recognition',
            date: '2025-10-13',
            dateLabel: 'Oct 13, 2025',
            summary: 'Agentforce Voice uses Deepgram Nova-2 for real-time transcription with 95%+ accuracy and failover support.',
            accent: '#06A59A',
            icon: 'mic',
          },
          {
            id: 'voice-engine-openai-gpt',
            title: 'OpenAI GPT via Flash Planner for reasoning',
            date: '2025-10-13',
            dateLabel: 'Oct 13, 2025',
            summary: 'Flash Planner (Atlas-like reasoning engine) processes customer intent using OpenAI GPT with zero data retention.',
            accent: '#06A59A',
            icon: 'psychology',
          },
          {
            id: 'voice-engine-elevenlabs',
            title: 'ElevenLabs Turbo v2.5 for natural voice synthesis',
            date: '2025-10-13',
            dateLabel: 'Oct 13, 2025',
            summary: 'ElevenLabs Turbo v2.5 generates natural-sounding voice responses with emotional tone control and zero retention mode.',
            accent: '#06A59A',
            icon: 'campaign',
          },
        ],
      },
      {
        id: 'voice-configuration',
        symbol: 'Vc',
        name: 'Voice Configuration',
        label: 'Voice Configuration',
        icon: 'tune',
        accent: '#06A59A',
        type: 'child',
        tagline: 'Fine-tune transcription accuracy, pronunciation, and voice quality.',
        description: 'Customize voice interactions with key-term prompting (highlight important phrases), pronunciation dictionaries (IPA and CMU phonetic spelling), and voice tuning (speed, stability, similarity). Supports up to 100 key terms per agent.',
        storyline: [
          'Add key terms to improve transcription of product names and jargon',
          'Define pronunciation rules using IPA or CMU phonetic spelling',
          'Tune voice speed (0.5x-2.0x), stability (0-100), and similarity (0-100)',
          'Test voice settings in Agent Builder preview mode',
          'Deploy tuned voice profile to production agents',
        ],
        specs: {
          keyTerms: 'Up to 100 terms per agent',
          pronunciationFormats: 'IPA, CMU',
          voiceSpeed: '0.5x - 2.0x',
          voiceStability: '0 - 100',
          voiceSimilarity: '0 - 100',
          preview: 'Real-time testing in Builder',
        },
        useCases: [
          'Improve transcription of product names, acronyms, and industry jargon',
          'Correct pronunciation of brand names and technical terms',
          'Adjust voice speed for accessibility (slower for complex info)',
          'Increase stability for consistent professional tone',
          'Fine-tune similarity for brand voice alignment',
        ],
        links: {
          docs: 'https://help.salesforce.com/s/articleView?id=ai.agent_configure_voice_settings.htm&type=5',
          ipa: 'https://en.wikipedia.org/wiki/International_Phonetic_Alphabet',
          cmu: 'https://en.wikipedia.org/wiki/CMU_Pronouncing_Dictionary',
        },
        capabilities: {
          channelSupport: [
            {
              name: 'Agent Builder',
              icon: 'build',
              accent: '#7B5EA7',
              available: true,
              description: 'Configure voice settings directly in Agentforce Builder',
              specs: { interface: 'Setup UI', preview: 'Real-time', deployment: 'One-click' },
            },
            {
              name: 'Voice Settings API',
              icon: 'code',
              accent: '#06A59A',
              available: true,
              description: 'Programmatic configuration via REST API',
              specs: { endpoints: 'REST API', auth: 'OAuth 2.0', versioning: 'v60+' },
            },
          ],
          features: [
            {
              name: 'Key-term Prompting',
              icon: 'settings_voice',
              accent: '#06A59A',
              available: true,
              description: 'Highlight up to 100 important phrases for improved transcription accuracy',
              specs: { limit: '100 terms per agent', format: 'String list', caseSensitive: false },
            },
            {
              name: 'Pronunciation Dictionary',
              icon: 'spellcheck',
              accent: '#06A59A',
              available: true,
              description: 'Define custom pronunciation using IPA or CMU phonetic spelling',
              specs: { formats: 'IPA, CMU', entries: 'Unlimited', priority: 'Override default' },
            },
            {
              name: 'Voice Speed Control',
              icon: 'speed',
              accent: '#06A59A',
              available: true,
              description: 'Adjust speaking speed from 0.5x (slow) to 2.0x (fast)',
              specs: { range: '0.5x - 2.0x', default: '1.0x', granularity: '0.1x increments' },
            },
            {
              name: 'Voice Stability',
              icon: 'equalizer',
              accent: '#06A59A',
              available: true,
              description: 'Control consistency of voice output (0=expressive, 100=monotone)',
              specs: { range: '0 - 100', default: '50', useCase: 'Professional consistency' },
            },
            {
              name: 'Voice Similarity',
              icon: 'record_voice_over',
              accent: '#06A59A',
              available: true,
              description: 'Fine-tune how closely output matches target voice (0=loose, 100=exact)',
              specs: { range: '0 - 100', default: '75', useCase: 'Brand voice matching' },
            },
            {
              name: 'Real-time Preview',
              icon: 'play_circle',
              accent: '#06A59A',
              available: true,
              description: 'Test voice settings in Agent Builder before deployment',
              specs: { mode: 'Interactive preview', latency: 'Real-time', feedback: 'Instant' },
            },
          ],
        },
        releases: [
          {
            id: 'voice-config-keyterm-prompting',
            title: 'Key-term prompting for better transcription',
            date: '2025-12-15',
            dateLabel: 'Week of Dec 15, 2025',
            summary: 'Highlight up to 100 important phrases so Agentforce Voice accurately transcribes product names, acronyms, and jargon.',
            accent: '#06A59A',
            icon: 'settings_voice',
          },
          {
            id: 'voice-config-pronunciation-dictionary',
            title: 'Pronunciation dictionary with IPA and CMU support',
            date: '2026-01-05',
            dateLabel: 'Release 260',
            summary: 'Define custom pronunciations using International Phonetic Alphabet (IPA) or CMU phonetic spelling to correct brand names.',
            accent: '#06A59A',
            icon: 'spellcheck',
          },
          {
            id: 'voice-config-voice-tuning',
            title: 'Voice tuning controls for speed, stability, and similarity',
            date: '2026-01-05',
            dateLabel: 'Release 260',
            summary: 'Fine-tune voice output with speed (0.5x-2.0x), stability (0-100), and similarity (0-100) controls for professional tone.',
            accent: '#06A59A',
            icon: 'tune',
          },
        ],
      },
      {
        id: 'telephony-integration',
        symbol: 'Ti',
        name: 'Telephony Integration',
        label: 'Telephony Integration',
        icon: 'settings_phone',
        accent: '#06A59A',
        type: 'child',
        tagline: 'Connect to PSTN and SIP networks via Service Cloud Voice partners.',
        description: 'Agentforce Voice requires Service Cloud Voice to connect to telephony networks. Supported partners include Amazon Connect, Genesys Cloud, and other CCaaS vendors. Route calls using PSTN (traditional phone lines) or SIP (VoIP) with support for Omni-Channel flow integration.',
        storyline: [
          'Enable Service Cloud Voice with Amazon Connect or Genesys Cloud',
          'Configure SIP routing or PSTN phone numbers',
          'Create Omni-Channel flows for call routing',
          'Connect Agentforce Builder agents to voice channels',
          'Test end-to-end call flow with real phone numbers',
        ],
        specs: {
          prerequisite: 'Service Cloud Voice (required)',
          partners: 'Amazon Connect, Genesys Cloud, CCaaS vendors',
          protocols: 'PSTN, SIP/2.0',
          routing: 'Omni-Channel flow builder',
          concurrentCalls: '500 per org',
          codecs: 'G.711, G.729, Opus, G.722',
        },
        useCases: [
          'Route incoming calls to Agentforce Voice agents',
          'Escalate complex calls to human agents with full context',
          'Load balance across multiple voice agents',
          'Connect traditional phone systems via PSTN',
          'Integrate VoIP systems using SIP routing',
          'Multi-region deployment with local phone numbers',
        ],
        links: {
          docs: 'https://help.salesforce.com/s/articleView?id=ai.agent_connect_telephony_parent.htm&type=5',
          serviceCloudVoice: 'https://help.salesforce.com/s/articleView?id=service.voice_customize.htm&type=5',
          amazonConnect: 'https://help.salesforce.com/s/articleView?id=service.voice_omni_unified_routing_configure.htm&type=5',
          omniChannel: 'https://help.salesforce.com/s/articleView?id=service.voice_routing_flows.htm&type=5',
        },
        capabilities: {
          channelSupport: [
            {
              name: 'Amazon Connect',
              icon: 'cloud_circle',
              accent: '#FF9900',
              available: true,
              description: 'AWS-based contact center integration via Service Cloud Voice',
              specs: { provider: 'AWS', deployment: 'Multi-region', failover: 'Built-in' },
            },
            {
              name: 'Genesys Cloud',
              icon: 'hub',
              accent: '#FF4F1F',
              available: true,
              description: 'Genesys CCaaS platform integration via Service Cloud Voice',
              specs: { provider: 'Genesys', deployment: 'Cloud-native', failover: 'Automatic' },
            },
            {
              name: 'Other CCaaS Vendors',
              icon: 'diversity_3',
              accent: '#06A59A',
              available: true,
              description: 'Service Cloud Voice supports additional CCaaS vendors',
              specs: { standard: 'SIP/2.0', certification: 'Partner program' },
            },
          ],
          features: [
            {
              name: 'PSTN Routing',
              icon: 'phone',
              accent: '#06A59A',
              available: true,
              description: 'Traditional phone network connectivity with local and toll-free numbers',
              specs: { protocol: 'PSTN', codecs: 'G.711, G.729', quality: 'HD Voice' },
            },
            {
              name: 'SIP Routing',
              icon: 'settings_phone',
              accent: '#06A59A',
              available: true,
              description: 'Session Initiation Protocol for VoIP and carrier integration',
              specs: { protocol: 'SIP/2.0', codecs: 'Opus, G.722', quality: 'Wideband' },
            },
            {
              name: 'Omni-Channel Routing',
              icon: 'alt_route',
              accent: '#06A59A',
              available: true,
              description: 'Flow-based call routing with skills-based assignment',
              specs: { flowBuilder: 'Visual', routing: 'Skills-based', priority: 'Configurable' },
            },
            {
              name: 'Context-Preserving Escalation',
              icon: 'transfer_within_a_station',
              accent: '#06A59A',
              available: true,
              description: 'Hand off to human agents with full conversation history',
              specs: { context: 'Full transcript', crm: 'Auto-logged', hold: 'Seamless' },
            },
            {
              name: 'Call Recording',
              icon: 'fiber_manual_record',
              accent: '#06A59A',
              available: true,
              description: 'Record voice interactions for compliance and quality assurance',
              specs: { storage: 'Salesforce Files', retention: 'Configurable', encryption: 'At rest' },
            },
            {
              name: 'Concurrent Call Limits',
              icon: 'hourglass_top',
              accent: '#06A59A',
              available: true,
              description: 'Support up to 500 concurrent calls per Salesforce org',
              specs: { limit: '500 per org', queueing: 'Automatic', overflow: 'Configurable' },
            },
          ],
        },
        releases: [
          {
            id: 'telephony-integration-sip-routing',
            title: 'SIP routing for flexible carrier integration',
            date: '2026-03-30',
            dateLabel: 'Mar 30, 2026',
            summary: 'Route Agentforce Voice calls using SIP protocol to connect with existing VoIP carriers and PBX systems.',
            accent: '#06A59A',
            icon: 'settings_phone',
          },
          {
            id: 'telephony-integration-amazon-connect',
            title: 'Amazon Connect support via Service Cloud Voice',
            date: '2025-10-13',
            dateLabel: 'Oct 13, 2025',
            summary: 'Integrate Agentforce Voice with Amazon Connect for AWS-based contact center deployments.',
            accent: '#FF9900',
            icon: 'cloud_circle',
          },
          {
            id: 'telephony-integration-genesys',
            title: 'Genesys Cloud support via Service Cloud Voice',
            date: '2025-10-13',
            dateLabel: 'Oct 13, 2025',
            summary: 'Connect Agentforce Voice to Genesys Cloud CCaaS platform for enterprise telephony integration.',
            accent: '#FF4F1F',
            icon: 'hub',
          },
        ],
      },
      {
        id: 'operations-monitoring',
        symbol: 'Om',
        name: 'Operations & Monitoring',
        label: 'Operations & Monitoring',
        icon: 'monitoring',
        accent: '#06A59A',
        type: 'child',
        tagline: 'Track usage, performance, and costs with real-time analytics.',
        description: 'Monitor Agentforce Voice with conversation logs, usage analytics, billing reports (Voice Minutes), and performance metrics. Track transcription accuracy, call duration, escalation rates, and customer satisfaction scores.',
        storyline: [
          'View real-time conversation logs with transcripts',
          'Track Voice Minutes usage and billing per agent',
          'Analyze call duration, escalation rate, and resolution metrics',
          'Monitor transcription accuracy and low-confidence alerts',
          'Export reports for compliance and quality assurance',
        ],
        specs: {
          billing: 'Voice Minutes (rounded up per minute)',
          logging: 'Real-time conversation logs',
          analytics: 'Usage, performance, cost reports',
          retention: 'Configurable (30-90 days)',
          exports: 'CSV, JSON, API',
        },
        useCases: [
          'Track monthly Voice Minutes usage and forecast costs',
          'Monitor call volume trends by hour, day, and week',
          'Identify conversation failures and low transcription confidence',
          'Analyze escalation patterns to improve agent instructions',
          'Generate compliance reports for recorded calls',
          'Measure customer satisfaction and resolution rates',
        ],
        links: {
          docs: 'https://help.salesforce.com/s/articleView?id=ai.agentforce_voice.htm&type=5',
          api: 'https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/',
        },
        capabilities: {
          channelSupport: [
            {
              name: 'Agentforce Studio',
              icon: 'dashboard',
              accent: '#7B5EA7',
              available: true,
              description: 'Real-time monitoring dashboard for conversation health',
              specs: { view: 'Live metrics', filters: 'Agent, channel, date', export: 'CSV' },
            },
            {
              name: 'Einstein Analytics',
              icon: 'analytics',
              accent: '#0176D3',
              available: true,
              description: 'Deep-dive analytics with custom dashboards and AI insights',
              specs: { dashboards: 'Custom', forecasting: 'AI-powered', sharing: 'Role-based' },
            },
            {
              name: 'Salesforce APIs',
              icon: 'api',
              accent: '#06A59A',
              available: true,
              description: 'Programmatic access to logs, metrics, and billing data',
              specs: { endpoints: 'REST, GraphQL', auth: 'OAuth 2.0', rate: '100k calls/day' },
              docs: 'https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/',
            },
          ],
          features: [
            {
              name: 'Voice Minutes Billing',
              icon: 'monetization_on',
              accent: '#06A59A',
              available: true,
              description: 'Track usage rounded up per minute with detailed cost breakdowns',
              specs: { granularity: 'Per minute', rounding: 'Up', reporting: 'Real-time' },
            },
            {
              name: 'Conversation Logs',
              icon: 'description',
              accent: '#06A59A',
              available: true,
              description: 'Full transcripts with timestamps, confidence scores, and metadata',
              specs: { format: 'JSON, plain text', retention: '30-90 days', search: 'Full-text' },
            },
            {
              name: 'Usage Analytics',
              icon: 'bar_chart',
              accent: '#06A59A',
              available: true,
              description: 'Call volume, duration, and escalation rate metrics by agent and channel',
              specs: { metrics: '20+', granularity: 'Hourly', history: '12 months' },
            },
            {
              name: 'Performance Metrics',
              icon: 'speed',
              accent: '#06A59A',
              available: true,
              description: 'Latency, transcription accuracy, and customer satisfaction scores',
              specs: { stt: 'Confidence score', latency: 'P50/P95/P99', csat: '1-5 scale' },
            },
            {
              name: 'Compliance Exports',
              icon: 'inventory',
              accent: '#06A59A',
              available: true,
              description: 'Export conversation logs and call recordings for regulatory compliance',
              specs: { formats: 'CSV, JSON, audio files', schedule: 'Automated', encryption: 'PGP' },
            },
            {
              name: 'Real-time Alerts',
              icon: 'notifications_active',
              accent: '#06A59A',
              available: true,
              description: 'Get notified when transcription confidence drops or calls fail',
              specs: { channels: 'Email, Slack, SMS', thresholds: 'Configurable', severity: '3 levels' },
            },
          ],
        },
        releases: [
          {
            id: 'operations-voice-minutes-billing',
            title: 'Voice Minutes usage type for accurate billing',
            date: '2026-01-05',
            dateLabel: 'Release 260',
            summary: 'Track Agentforce Voice usage with dedicated Voice Minutes metric, rounded up per minute for transparent billing.',
            accent: '#06A59A',
            icon: 'monetization_on',
          },
          {
            id: 'operations-conversation-logs',
            title: 'Full conversation logs with transcripts and metadata',
            date: '2025-10-13',
            dateLabel: 'Oct 13, 2025',
            summary: 'View complete conversation history with timestamps, confidence scores, and context for quality assurance.',
            accent: '#06A59A',
            icon: 'description',
          },
          {
            id: 'operations-usage-analytics',
            title: 'Usage analytics dashboard in Agentforce Studio',
            date: '2025-12-04',
            dateLabel: 'Winter \'26',
            summary: 'Monitor call volume, escalation rates, and performance metrics with built-in analytics dashboards.',
            accent: '#06A59A',
            icon: 'analytics',
          },
        ],
      },
    ],
  },
  {
    id: 'observability',
    symbol: 'Ob',
    name: 'Observability',
    label: 'Observability',
    icon: 'visibility',
    accent: '#00BFA5',
    type: 'standalone',
    tagline: 'Understand runtime health and resolution confidence.',
    description: 'Surface telemetry such as Task Resolution success and runtime guardrails.',
    storyline: [
      'Monitor agents in production',
      'Understand task coverage via logs',
      'Resolve issues with visibility into executions',
    ],
    specs: {
      focus: 'Runtime observability',
      release: 'GA January 2026',
    },
    releases: [
      {
        id: 'observability-agentforce-studio',
        title: 'Monitor your agents more easily with Agentforce Studio',
        date: '2025-09-01',
        dateLabel: 'Sep 2025',
        summary:
          'Agentforce Studio surfaces Observability dashboards so admins can review session health and move quickly from insights to action.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_studio.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'dashboard',
      },
      {
        id: 'observability-agent-optimization-beta',
        title: 'Explore Agentforce Optimization (Beta)',
        date: '2025-09-01',
        dateLabel: 'Sep 2025',
        summary:
          'Agentforce Optimization Beta surfaces early insights, traces, and moments to help you experiment with agent improvements.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_optimization.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'insights',
      },
      {
        id: 'observability-agent-optimization-ga',
        title: 'Agentforce Optimization GA unlocks better traces and intents',
        date: '2025-11-05',
        dateLabel: 'Nov 5, 2025',
        summary:
          'Session trace enhancements, voice agent support, and the renaming of Moments to Intents make optimization ready for production use.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_optimization_ga.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'trending_up',
      },
      {
        id: 'observability-agent-analytics-ga',
        title: 'Track agent performance and quality metrics with Agent Analytics',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'New dashboards show error rate, unique user count, action counts, and a Quality tab for service agents and employee agents.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_analytics_performance_quality_ga.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'bar_chart',
      },
      {
        id: 'observability-task-resolution-beta',
        title: 'Measure agent outcomes with Task Resolution (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Capture structured outcomes for each task so you can analyze success rates and drop-off points before going GA.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_task_resolution.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'assignment_turned_in',
      },
      {
        id: 'observability-agent-analytics-tableau',
        title: 'Gain dynamic insights with Agentforce Analytics powered by Tableau Next (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Tableau Next adds deeper dashboards and guided analytics so you can explore agent behavior across datasets.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_analytics.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'table_chart',
      },
      {
        id: 'observability-session-tracing',
        title: 'Gain visibility into agent behavior with Agentforce Session Tracing',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Session traces record the entire conversation so you can replay, debug, and audit every decision path.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_session_tracing.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'timeline',
      },
      {
        id: 'observability-knowledge-retrieval',
        title: 'Gain visibility into knowledge retrieval quality',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Track which knowledge results were surfaced so you can refine retrieval pipelines for accuracy and relevance.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_retrieval_quality.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'search',
      },
      {
        id: 'observability-task-resolution-ga',
        title: 'Task Resolution Support for New Agentforce Builder Agents',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Agents created with the new Builder gain Task Resolution.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_task_resolution_ga.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'task_alt',
      },
      {
        id: 'observability-enhancements-spring26',
        title: 'Observability enhancements: breadcrumb navigation, UI tweaks, and analytics metrics',
        date: '2026-03-30',
        dateLabel: 'Spring \'26',
        summary:
          'Optimization breadcrumb navigation, refreshed UI, and extra analytics metrics make it easier to spot trends.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_observability_enhancements.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'layers',
      },
      {
        id: 'observability-rag-metrics',
        title: 'Evaluate AI performance with new RAG metrics and enriched analytics',
        date: '2026-03-30',
        dateLabel: 'Spring \'26',
        summary:
          'New RAG metrics and enriched analytics help you understand how grounding sources influence answers.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_analytics_metrics.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'analytics',
      },
      {
        id: 'observability-voice-optimization',
        title: 'Voice optimization: session playback and dashboard enhancements',
        date: '2026-03-30',
        dateLabel: 'Spring \'26',
        summary:
          'Voice session playback and dashboard upgrades make it easier to audit conversation quality and agent decisions.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_optimization_voice.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'mic',
      },
    ],
  },
  {
    id: 'prompt-builder',
    symbol: 'Pb',
    name: 'Prompt Builder',
    label: 'Prompt Builder',
    icon: 'edit_note',
    accent: '#9C27B0',
    type: 'parent',
    tagline: 'Design and ground prompts with data and knowledge.',
    description: 'Author prompts with knowledge grounding, web data, and CRM context before wiring them into Agent Script flows.',
    storyline: [
      'Author prompt content with semantic context',
      'Ground prompts in knowledge, CRM data, and web sources',
      'Configure limits and guardrails',
      'Reuse prompt blocks across agents',
    ],
    specs: {
      focus: 'Prompt experimentation + Grounding',
      availability: 'Preview 2026',
    },
    releases: [],
    useCases: ['Prompt authoring', 'Knowledge grounding', 'Web data retrieval'],
    children: [
      {
        id: 'prompt-builder-web',
        symbol: 'Pw',
        name: 'Web Grounding',
        label: 'Web Grounding',
        icon: 'language',
        accent: '#9C27B0',
        type: 'child',
        tagline: 'Ground prompts with live web data and search results.',
        description: 'Connect prompts to web search, allowed domains, and multiple search providers to retrieve real-time information.',
        storyline: [
          'Add web search data sources to your Agentforce Data Library',
          'Ground prompts with relevant knowledge from websites',
          'Configure search providers (OpenAI, etc.) and domain restrictions',
          'Use Web Actions to retrieve live data at runtime',
        ],
        specs: {
          availability: 'GA',
          focus: 'Web data retrieval',
          searchProviders: 'OpenAI, Bing, Custom',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Web Search', icon: 'search', accent: '#4285F4', available: true, description: 'Retrieve real-time data from the open web' },
            { name: 'Domain Restrictions', icon: 'shield', accent: '#FE9339', available: true, description: 'Limit search to trusted domains only' },
            { name: 'Multiple Providers', icon: 'hub', accent: '#45C65A', available: true, description: 'Choose from OpenAI, Bing, or custom engines' },
            { name: 'Web Actions', icon: 'bolt', accent: '#7B5EA7', available: true, description: 'Fetch live data at runtime with API calls' },
          ],
        },
        releases: [
          {
            id: 'web-data-library',
            title: 'Add More Data Sources to your Agentforce Data Library with Web Search',
            date: '2025-05-01',
            dateLabel: "Spring '25",
            summary:
              'Web search data sources expand your Data Library so agents can retrieve answers from the open web.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_data_library_web_search.htm&release=254&type=5',
            accent: '#9C27B0',
            icon: 'library_add',
          },
          {
            id: 'web-retriever',
            title: 'Ground Prompts with Relevant Knowledge from Web Sites',
            date: '2025-07-01',
            dateLabel: "Summer '25",
            summary:
              'Prompt Builder web retriever connects prompts to external websites for real-time grounding.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_prompt_builder_web_retriever.htm&release=256&type=5',
            accent: '#9C27B0',
            icon: 'public',
          },
          {
            id: 'general-web-search-topic',
            title: 'Get Summarized Answers with the General Web Search Topic and Action',
            date: '2025-10-01',
            dateLabel: "Winter '26",
            summary:
              'The General Web Search topic and action provide summarized answers from the web inside agent conversations.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_get_summarized_answers_with_general_web_search.htm&release=258&type=5',
            accent: '#9C27B0',
            icon: 'summarize',
          },
          {
            id: 'openai-search-provider',
            title: 'Improve Web Search Results by Using OpenAI as a Search Provider (Beta)',
            date: '2025-12-01',
            dateLabel: "Winter '26",
            summary:
              'OpenAI becomes a search provider option so you can route web queries through OpenAI\'s search engine.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_improve_web_search_results_using_openai.htm&release=258&type=5',
            accent: '#9C27B0',
            icon: 'extension',
          },
          {
            id: 'allowed-domains',
            title: 'Improve Web Search Results By Using Allowed Domains',
            date: '2026-02-17',
            dateLabel: "Spring '26",
            summary:
              'Domain restrictions let you limit web search to trusted sites so agents stay within approved boundaries.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_domain_restriction.htm&release=260&type=5',
            accent: '#9C27B0',
            icon: 'verified',
          },
          {
            id: 'web-actions',
            title: 'Ground Prompts with Live Web Data with Web Actions',
            date: '2026-04-06',
            dateLabel: "Spring '26",
            summary:
              'Web Actions fetch live web data at runtime so prompts always have the most current information.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_prompt_builder_web_actions.htm&release=260&type=5',
            accent: '#9C27B0',
            icon: 'bolt',
          },
          {
            id: 'additional-search-provider',
            title: 'Improve Web Search Results by Using an Additional Search Provider Option',
            date: '2026-04-07',
            dateLabel: "Spring '26",
            summary:
              'Additional search provider options give you flexibility to choose the best search engine for your use case.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_search_provider_option.htm&release=260&type=5',
            accent: '#9C27B0',
            icon: 'tune',
          },
        ],
        useCases: ['Real-time web data retrieval', 'Domain-restricted search', 'Multi-provider search'],
      },
      {
        id: 'prompt-builder-general',
        symbol: 'Pg',
        name: 'General Features',
        label: 'General Features',
        icon: 'build',
        accent: '#9C27B0',
        type: 'child',
        tagline: 'Core prompt authoring and grounding capabilities.',
        description: 'Author prompts with CRM data, knowledge articles, and custom grounding sources.',
        storyline: [
          'Open Prompt Builder and create a new prompt template',
          'Ground prompts with CRM objects, fields, and relationships',
          'Test prompts with sample data before deployment',
          'Reuse prompt templates across multiple agents',
        ],
        specs: {
          availability: 'Preview 2026',
          focus: 'Prompt authoring + CRM grounding',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'CRM Grounding', icon: 'database', accent: '#0176D3', available: true, description: 'Connect prompts to Salesforce objects and fields' },
            { name: 'Knowledge Grounding', icon: 'book', accent: '#FFDB3C', available: true, description: 'Ground responses with knowledge articles' },
            { name: 'Template Reuse', icon: 'content_copy', accent: '#45C65A', available: true, description: 'Share prompts across multiple agents' },
          ],
        },
        releases: [
          {
            id: 'prompt-builder-preview',
            title: 'Prompt Builder Preview inside Agentforce Builder',
            date: '2026-01-05',
            dateLabel: 'Release 260',
            summary:
              'Prompt Builder preview lets you sculpt natural language prompts before deploying them into Agent Script flows.',
            url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
            accent: '#9C27B0',
            icon: 'preview',
          },
        ],
        useCases: ['Prompt authoring', 'CRM data grounding', 'Template reuse'],
      },
      {
        id: 'prompt-builder-limits',
        symbol: 'Pl',
        name: 'Limits & Guardrails',
        label: 'Limits & Guardrails',
        icon: 'shield_lock',
        accent: '#9C27B0',
        type: 'child',
        tagline: 'Configure limits and safety guardrails for prompts.',
        description: 'Set token limits, rate limits, and safety guardrails to control prompt execution.',
        storyline: [
          'Define token and rate limits for each prompt',
          'Configure safety guardrails to prevent harmful outputs',
          'Monitor limit usage in Observability dashboards',
        ],
        specs: {
          availability: 'Preview 2026',
          focus: 'Safety + Resource limits',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Token Limits', icon: 'data_usage', accent: '#EA001E', available: false, description: 'Control max tokens per prompt execution' },
            { name: 'Rate Limiting', icon: 'speed', accent: '#FE9339', available: false, description: 'Throttle prompt calls per time window' },
            { name: 'Safety Guardrails', icon: 'security', accent: '#45C65A', available: false, description: 'Block harmful or inappropriate outputs' },
          ],
        },
        releases: [],
        useCases: ['Resource management', 'Safety controls', 'Usage monitoring'],
      },
    ],
  },
];
