export const AGENTFORCE_TILES = [
  {
    id: 'agent-script',
    symbol: 'As',
    name: 'Agent Script',
    label: 'Agent Script',
    icon: 'architecture',
    accent: '#7B5EA7',
    tagline: 'Deterministic flows plus LLM reasoning inside the Builder.',
    description: 'Design structured agent journeys that combine determinism with reasoning in Agentforce Builder.',
    storyline: [
      'Open Agentforce Studio and create a new agent',
      'Compose deterministic steps with Agent Script reasoning nodes',
      'Preview and validate before publishing to production',
    ],
    specs: {
      availability: 'Beta from December 4, 2025',
      builder: 'New Agentforce Builder',
      focus: 'Determinism + LLM reasoning',
    },
    releases: [
      {
        id: 'agent-script-dreamforce-2025',
        title: 'Reveal Agent Script at Dreamforce 2025',
        date: '2025-10-13',
        dateLabel: 'Dreamforce 2025',
        summary:
          'Agent Script debuts inside Agentforce 360 as a new prompting tool that lets builders script "if/then" logic so AI agents stay flexible yet predictable.',
        url: 'https://techcrunch.com/2025/10/13/salesforce-announces-agentforce-360-as-enterprise-ai-competition-heats-up/',
        accent: '#7B5EA7',
        icon: 'flash_on',
      },
      {
        id: 'agent-script-beta-intro',
        title: 'Agent Script beta rolls into Agentforce 360 for hybrid reasoning',
        date: '2025-11-05',
        dateLabel: 'Nov 5, 2025',
        summary:
          'The beta release highlights hybrid reasoning with Agent Script guardrails plus Atlas-powered instructions that transform high-level prompts into deterministic branches.',
        url: 'https://www.salesforce.com/ap/news/press-releases/2025/10/14/welcome-to-the-agentic-enterprise-with-agentforce-360-salesforce-elevates-human-potential-in-the-age-of-ai-2/',
        accent: '#7B5EA7',
        icon: 'rocket_launch',
      },
      {
        id: 'agent-script-builder-beta',
        title: 'Build enterprise-ready agents with the new Agent Script view (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Agentforce Builder’s Script view documents deterministic steps, quick actions, and topics in one place so reasoning stays predictable.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'developer_mode',
      },
      {
        id: 'agent-script-reasoning-instructions',
        title: 'Reasoning instructions keep Agent Script predictable',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Guardrails let you decide where the LLM can flex and where the agent executes deterministic logic, eliminating surprises in topic transitions.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#reasoning',
        accent: '#7B5EA7',
        icon: 'gavel',
      },
      {
        id: 'agent-script-variables-conditions',
        title: 'Variables and conditions power repeatable decisions',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Store agent state, compare values, and branch to next actions or topics without relying solely on LLM memory.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#expressions',
        accent: '#7B5EA7',
        icon: 'tune',
      },
      {
        id: 'agent-script-combine-determinism',
        title: 'Combine Determinism and LLM Reasoning with Agent Script (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Agent Script introduces deterministic flows blended with LLM reasoning.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_script.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'architecture',
      },
      {
        id: 'agent-script-previews',
        title: 'Confidently Build Agents with In-Depth Agent Previews (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Previews help you understand how Agent Script flows behave.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_test.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'visibility',
      },
      {
        id: 'agent-script-editor-expansion',
        title: 'Canvas, quick actions, and DX editing for Agent Script',
        date: '2026-01-15',
        dateLabel: 'Jan 15, 2026',
        summary:
          'Canvas view summarizes script blocks, slash shortcuts add common expressions, and Agentforce DX/VS Code extensions keep syntax, autocomplete, and validation close at hand.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html',
        accent: '#7B5EA7',
        icon: 'code',
      },
      {
        id: 'agent-script-flow-control',
        title: 'Flow-of-control patterns show how to hand off topics',
        date: '2026-02-05',
        dateLabel: 'Feb 5, 2026',
        summary:
          'New patterns illustrate how to combine deterministic transitions and topic handoffs so the agent always knows the next step.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#flow-of-control',
        accent: '#7B5EA7',
        icon: 'swap_horiz',
      },
      {
        id: 'agent-script-patterns-library',
        title: 'Agent Script patterns and reference guide expand',
        date: '2026-03-01',
        dateLabel: 'Mar 1, 2026',
        summary:
          'The Agent Script documentation now highlights reusable patterns, code examples, and reference tables so builders can copy proven logic quickly.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#patterns',
        accent: '#7B5EA7',
        icon: 'library_books',
      },
    ],
  },
  {
    id: 'agentforce-voice',
    symbol: 'Av',
    name: 'Agentforce Voice',
    label: 'Agentforce Voice',
    icon: 'headset_mic',
    accent: '#06A59A',
    tagline: 'Enhanced Chat, Slack, and Email delivery for agents.',
    description: 'Connect agents to modern channels such as Slack, Enhanced Chat, and email delivery within the Builder.',
    storyline: [
      'Add channel connections in the new Builder',
      'Test conversations against Enhanced Chat v2',
      'Deploy agents to Slack or email with confidence',
    ],
    specs: {
      channels: 'Slack, Enhanced Chat, Email',
      release: 'January 2026',
    },
    releases: [
      {
        id: 'agentforce-voice-english-launch',
        title: 'Agentforce Voice launches with English-only support',
        date: '2025-10-13',
        dateLabel: 'Oct 13, 2025',
        summary: 'Agentforce Voice debuts in English so your teams can prototype telephony interactions with Builder agents.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_voice.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'language',
      },
      {
        id: 'agentforce-voice-billing-usage-types',
        title: 'New billable usage types for Agentforce Voice',
        date: '2025-10-24',
        dateLabel: 'Oct 24, 2025',
        summary: 'Define new billing buckets for telephony and track voice usage as part of Agentforce analytics.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_billing_flex_voice_usage_type.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'monetization_on',
      },
      {
        id: 'agentforce-voice-enable-service-agents',
        title: 'Enable voice conversations for Agentforce Service Agents',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary: 'Agentforce Voice now powers service agents that can answer calls, escalate to humans, and keep sessions secure.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_voice.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'support_agent',
      },
      {
        id: 'agentforce-voice-keyterm-prompting',
        title: 'Help your voice-enabled agent recognize key terms',
        date: '2025-12-15',
        dateLabel: 'Week of Dec 15, 2025',
        summary: 'Key-term prompting lets you highlight important phrases so Agentforce Voice senses critical triggers during calls.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_agent_voice_keyterm_prompting.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'settings_voice',
      },
      {
        id: 'agentforce-voice-minutes-usage',
        title: 'Introduce the Agentforce Voice minutes usage type',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Track Agentforce Voice minutes separately to understand telephony spend and optimize workloads.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_billing_voice_minutes.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'timer',
      },
      {
        title: 'Connect Agents to Enhanced Chat v2 in Agentforce Builder (Beta)',
        date: '2026-01-05',
        dateLabel: 'Week of Jan 5, 2026',
        summary: 'Enhanced Chat v2 connections are surfaced directly in the Builder.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_builder_connections.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'chat_bubble',
      },
      {
        title: 'Deploy Agents to Slack Quickly with the Slack Connection',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Slack connection deployment becomes fast and secure.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_slack_connection.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'share',
      },
      {
        title: 'Deliver Emails in the New Agentforce Builder',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Email delivery channels plug directly into the Builder flow.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_email_connections.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'email',
      },
      {
        id: 'agentforce-voice-sip-routing',
        title: 'Route Agentforce Voice calls using SIP',
        date: '2026-03-30',
        dateLabel: 'Mar 30, 2026',
        summary: 'SIP routing gives you flexibility to connect Agentforce Voice into existing telephony carriers.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_voice_with_sip.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'network_cell',
      },
      {
        id: 'agentforce-voice-french-support',
        title: 'Enable voice interactions in French',
        date: '2026-03-30',
        dateLabel: 'Mar 30, 2026',
        summary: 'Agentforce Voice now understands French prompts, unlocking multilingual voice assistants.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_voice_french_support.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'translate',
      },
    ],
  },
  {
    id: 'legacy-builder',
    symbol: 'Lb',
    name: 'Legacy Builder',
    label: 'Legacy Builder',
    icon: 'handyman',
    accent: '#0176D3',
    tagline: 'See how the new Builder replaces the classic workspace.',
    description: 'Track the transition from the Legacy Builder to the modern Agentforce Builder experience.',
    storyline: [
      'Understand where Builder capabilities migrated',
      'Map legacy flows to the new Agent Script structure',
      'Enable the new Builder for your organization',
    ],
    specs: {
      transition: 'Beta + GA',
      focus: 'Builder migration',
    },
    releases: [
      {
        id: 'legacy-escalate-reps',
        title: 'Escalate complex employee agent conversations to reps',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'When an employee agent needs human help, escalation routes conversations to the right rep without losing context.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_escalate_conversations_to_reps.htm&release=258&type=5',
        accent: '#0176D3',
        icon: 'support_agent',
      },
      {
        id: 'legacy-welcome-recommendations',
        title: 'Customize welcome recommendations in Agentforce Builder',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Fine-tune the welcome experience so intelligent recommendations greet customers with the right next steps.',
        url: 'https://help.salesforce.com/s/articleView?language=en_US&id=release-notes.rn_einstein_customize_welcome_reco_in_agentforce_builder.htm&release=258&type=5',
        accent: '#0176D3',
        icon: 'recommend',
      },
      {
        id: 'legacy-migrate-employee-agent',
        title: 'Easily migrate from Agentforce to an Employee Agent',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'A guided setup flow walks admins through converting a default Agentforce bot into an employee-facing agent.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_easily_migrate_af_to_aea.htm&release=258&type=5',
        accent: '#0176D3',
        icon: 'swap_horiz',
      },
      {
        id: 'legacy-enhanced-connections',
        title: 'Easily add agents to multiple channels with enhanced connections setup',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'The new connections panel streamlines attaching Agents to voice, chat, and digital channels from a single place.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_enhanced_connections_panel.htm&release=258&type=5',
        accent: '#0176D3',
        icon: 'settings_input_component',
      },
      {
        id: 'legacy-service-email-connection',
        title: 'Deliver emails with the Service Email connection',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary: 'Agentforce Builder now wires email delivery channels into classic service email pipelines.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_email_connection.htm&release=258&type=5',
        accent: '#0176D3',
        icon: 'email',
      },
      {
        title: 'New Agentforce Builder Availability in Agentforce Studio',
        date: '2026-02-20',
        dateLabel: 'Feb 20, 2026',
        summary: 'The new Builder lands in Agentforce Studio with usability improvements.',
        url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
        accent: '#0176D3',
        icon: 'new_releases',
      },
      {
        title: 'Build Complex Agents Faster with Canvas View Enhancements',
        date: '2026-01-05',
        dateLabel: 'Week of Jan 5, 2026',
        summary: 'Canvas View upgrades accelerate complex branching.',
        url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
        accent: '#0176D3',
        icon: 'grid_view',
      },
      {
        title: 'Connect Agents to Your Knowledge Sources in the New Builder',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Knowledge connections now live inside the modern Builder.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_data_library_new_builder.htm&release=260&type=5',
        accent: '#0176D3',
        icon: 'book',
      },
    ],
  },
  {
    id: 'testing-center',
    symbol: 'Tc',
    name: 'Testing Center',
    label: 'Testing Center',
    icon: 'bug_report',
    accent: '#FFDB3C',
    tagline: 'Preview and validation are now part of Builder testing.',
    description: 'Capture confidence with testing features such as previews and validation tools.',
    storyline: [
      'Kick off testing cycles inside the Builder',
      'Inspect agent previews before deployment',
      'Validate flows with the new guardrails',
    ],
    specs: {
      focus: 'Previews + Validation',
      status: 'Beta',
    },
    releases: [
      {
        title: 'Build High-Quality Agents with Validation Enhancements (Beta)',
        date: '2026-01-05',
        dateLabel: 'Week of Jan 5, 2026',
        summary: 'Validation tooling ships to harden agent quality.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_builder_validation.htm&release=260&type=5',
        accent: '#FFDB3C',
        icon: 'check_circle',
      },
      {
        title: 'Confidently Build Agents with In-Depth Agent Previews (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Agent previews help test interactions before release.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_test.htm&release=258&type=5',
        accent: '#FFDB3C',
        icon: 'visibility',
      },
    ],
  },
  {
    id: 'observability',
    symbol: 'Ob',
    name: 'Observability',
    label: 'Observability',
    icon: 'visibility',
    accent: '#00BFA5',
    tagline: 'Understand runtime health and resolution confidence.',
    description: 'Surface telemetry such as Task Resolution success and runtime guardrails.',
    storyline: [
      'Monitor agents in production',
      'Understand task coverage via logs',
      'Resolve issues with visibility into executions',
    ],
    specs: {
      focus: 'Runtime observability',
      release: 'GA January 2026',
    },
    releases: [
      {
        id: 'observability-agentforce-studio',
        title: 'Monitor your agents more easily with Agentforce Studio',
        date: '2025-09-01',
        dateLabel: 'Sep 2025',
        summary:
          'Agentforce Studio surfaces Observability dashboards so admins can review session health and move quickly from insights to action.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_studio.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'dashboard',
      },
      {
        id: 'observability-agent-optimization-beta',
        title: 'Explore Agentforce Optimization (Beta)',
        date: '2025-09-01',
        dateLabel: 'Sep 2025',
        summary:
          'Agentforce Optimization Beta surfaces early insights, traces, and moments to help you experiment with agent improvements.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_optimization.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'insights',
      },
      {
        id: 'observability-agent-optimization-ga',
        title: 'Agentforce Optimization GA unlocks better traces and intents',
        date: '2025-11-05',
        dateLabel: 'Nov 5, 2025',
        summary:
          'Session trace enhancements, voice agent support, and the renaming of Moments to Intents make optimization ready for production use.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_optimization_ga.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'trending_up',
      },
      {
        id: 'observability-agent-analytics-ga',
        title: 'Track agent performance and quality metrics with Agent Analytics',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'New dashboards show error rate, unique user count, action counts, and a Quality tab for service agents and employee agents.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_analytics_performance_quality_ga.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'bar_chart',
      },
      {
        id: 'observability-task-resolution-beta',
        title: 'Measure agent outcomes with Task Resolution (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Capture structured outcomes for each task so you can analyze success rates and drop-off points before going GA.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_task_resolution.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'assignment_turned_in',
      },
      {
        id: 'observability-agent-analytics-tableau',
        title: 'Gain dynamic insights with Agentforce Analytics powered by Tableau Next (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Tableau Next adds deeper dashboards and guided analytics so you can explore agent behavior across datasets.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_analytics.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'table_chart',
      },
      {
        id: 'observability-session-tracing',
        title: 'Gain visibility into agent behavior with Agentforce Session Tracing',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Session traces record the entire conversation so you can replay, debug, and audit every decision path.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_session_tracing.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'timeline',
      },
      {
        id: 'observability-knowledge-retrieval',
        title: 'Gain visibility into knowledge retrieval quality',
        date: '2025-12-04',
        dateLabel: 'Winter ’26',
        summary:
          'Track which knowledge results were surfaced so you can refine retrieval pipelines for accuracy and relevance.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_retrieval_quality.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'search',
      },
      {
        id: 'observability-task-resolution-ga',
        title: 'Task Resolution Support for New Agentforce Builder Agents',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Agents created with the new Builder gain Task Resolution.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_task_resolution_ga.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'task_alt',
      },
      {
        id: 'observability-enhancements-spring26',
        title: 'Observability enhancements: breadcrumb navigation, UI tweaks, and analytics metrics',
        date: '2026-03-30',
        dateLabel: 'Spring ’26',
        summary:
          'Optimization breadcrumb navigation, refreshed UI, and extra analytics metrics make it easier to spot trends.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_observability_enhancements.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'layers',
      },
      {
        id: 'observability-rag-metrics',
        title: 'Evaluate AI performance with new RAG metrics and enriched analytics',
        date: '2026-03-30',
        dateLabel: 'Spring ’26',
        summary:
          'New RAG metrics and enriched analytics help you understand how grounding sources influence answers.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_analytics_metrics.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'analytics',
      },
      {
        id: 'observability-voice-optimization',
        title: 'Voice optimization: session playback and dashboard enhancements',
        date: '2026-03-30',
        dateLabel: 'Spring ’26',
        summary:
          'Voice session playback and dashboard upgrades make it easier to audit conversation quality and agent decisions.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_optimization_voice.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'mic',
      },
    ],
  },
  {
    id: 'prompt-builder',
    symbol: 'Pb',
    name: 'Prompt Builder',
    label: 'Prompt Builder',
    icon: 'prompt',
    accent: '#9C27B0',
    tagline: 'Play with prompts before stitching them into agents.',
    description: 'Design prompts and knowledge grounding before wiring them into Agent Script flows.',
    storyline: [
      'Author prompt content with semantic context',
      'Ground prompts in knowledge and CRM data',
      'Reuse prompt blocks across agents',
    ],
    specs: {
      focus: 'Prompt experimentation',
      availability: 'Preview 2026',
    },
    releases: [
      {
        title: 'Prompt Builder Preview inside Agentforce Builder',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Prompt Builder preview lets you sculpt natural language before deployment.',
        url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
        accent: '#9C27B0',
        icon: 'build',
      },
    ],
  },
];
