export const AGENTFORCE_TILES = [
  {
    id: 'agentforce-grid',
    symbol: 'Ag',
    name: 'Agentforce Grid',
    label: 'Agentforce Grid',
    icon: 'grid_on',
    accent: '#7B5EA7',
    type: 'standalone',
    tagline: 'Enterprise agent orchestration and deployment.',
    description: 'Central hub for managing and deploying Agentforce agents across your organization.',
    storyline: [
      'Configure agent deployment settings',
      'Monitor active agents across channels',
      'Manage agent lifecycle and updates',
    ],
    specs: {
      availability: 'GA',
      focus: 'Agent orchestration',
    },
    releases: [],
    announcements: [
      {
        id: 'intelligent-context-ga',
        title: 'Intelligent Context GA',
        date: '2026-04-20',
        status: 'GA',
        icon: 'psychology',
        accent: '#FE9339',
        summary: 'Intelligent Context is now GA, providing agents with unified memory and real-time data harmonization across systems.',
        highlights: [
          'Unified agent memory across sessions',
          'Real-time data harmonization',
          '100+ zero-copy data connectors',
        ],
      },
      {
        id: 'curated-memory-pilot',
        title: 'Curated Long Term Memory',
        date: '2026-05-01',
        status: 'Pilot',
        icon: 'inventory',
        accent: '#FE9339',
        summary: 'Pilot program for curated agent memory — retain context across sessions with intelligent memory management.',
        highlights: [
          'Persistent memory across conversations',
          'Smart memory pruning and prioritization',
          'Privacy-aware memory controls',
        ],
      },
    ],
    useCases: ['Multi-agent deployment', 'Enterprise governance', 'Agent lifecycle management'],
  },
  {
    id: 'agentforce-development',
    symbol: 'Ad',
    name: 'Agentforce Development',
    label: 'Agentforce Development',
    icon: 'code',
    accent: '#7B5EA7',
    type: 'parent',
    tagline: 'Build agents with deterministic flows or classic patterns.',
    description: 'Choose between Agent Script for hybrid reasoning or Legacy Builder for traditional flows.',
    storyline: [
      'Select your development approach',
      'Build with deterministic or LLM-driven logic',
      'Deploy to multiple channels',
    ],
    specs: {
      builders: '2 approaches',
      focus: 'Agent authoring',
    },
    releases: [],
    announcements: [
      {
        id: 'agentforce-builder-ga',
        title: 'Agentforce Builder GA',
        date: '2026-04-20',
        status: 'GA',
        icon: 'new_releases',
        accent: '#7B5EA7',
        summary: 'The new Agentforce Builder is now generally available with enhanced canvas view, validation tools, and seamless agent authoring.',
        highlights: [
          'Canvas view for complex agent flows',
          'Enhanced validation and error checking',
          'Integrated testing and preview',
        ],
      },
      {
        id: 'agent-script-ga',
        title: 'Agentforce Script GA',
        date: '2026-04-20',
        status: 'GA',
        icon: 'architecture',
        accent: '#7B5EA7',
        summary: 'Agent Script moves from beta to GA, enabling deterministic flows with LLM reasoning for production-grade agents.',
        highlights: [
          'Combine determinism with LLM reasoning',
          'Variables and conditional branching',
          'DX tooling with VS Code extension',
        ],
      },
      {
        id: 'agentforce-gemini-ga',
        title: 'Agentforce on Gemini',
        date: '2026-05-01',
        status: 'GA',
        icon: 'auto_awesome',
        accent: '#7B5EA7',
        summary: 'Bring your own model — Agentforce now supports Google Gemini as an alternative LLM provider.',
        highlights: [
          'Google Gemini model support',
          'Multi-model orchestration',
          'Model selection per agent',
        ],
      },
    ],
    useCases: ['Agent development', 'Multi-channel deployment', 'Hybrid reasoning'],
    children: [
      {
        id: 'agent-script',
        symbol: 'As',
        name: 'Agent Script',
        label: 'Agent Script',
        icon: 'architecture',
        accent: '#7B5EA7',
        type: 'child',
        tagline: 'Deterministic flows plus LLM reasoning inside the Builder.',
        description: 'Design structured agent journeys that combine determinism with reasoning in Agentforce Builder.',
        storyline: [
          'Open Agentforce Studio and create a new agent',
          'Compose deterministic steps with Agent Script reasoning nodes',
          'Preview and validate before publishing to production',
        ],
        specs: {
          availability: 'Beta from December 4, 2025',
          builder: 'New Agentforce Builder',
          model: 'GPT-4.1',
          focus: 'Determinism + LLM reasoning',
        },
        capabilities: {
          channelSupport: [
            { name: 'Email', icon: 'email', accent: '#06A59A', available: true },
            { name: 'Slack', icon: 'chat', accent: '#E01E5A', available: true },
            { name: 'Service Agent', icon: 'support_agent', accent: '#0176D3', available: true },
            { name: 'Employee Agent', icon: 'badge', accent: '#9C27B0', available: true },
            { name: 'Enhanced Chat v2', icon: 'chat_bubble', accent: '#00BFA5', available: true },
            { name: 'Voice', icon: 'phone', accent: '#06A59A', available: false },
          ],
          features: [
            { name: 'Supports RAG', icon: 'library_books', accent: '#FFDB3C', available: true },
            { name: 'Support task resolution', icon: 'task_alt', accent: '#45C65A', available: true },
          ],
        },
        releases: [
      {
        id: 'agent-script-dreamforce-2025',
        title: 'Reveal Agent Script at Dreamforce 2025',
        date: '2025-10-13',
        dateLabel: 'Dreamforce 2025',
        summary:
          'Agent Script debuts inside Agentforce 360 as a new prompting tool that lets builders script "if/then" logic so AI agents stay flexible yet predictable.',
        url: 'https://techcrunch.com/2025/10/13/salesforce-announces-agentforce-360-as-enterprise-ai-competition-heats-up/',
        accent: '#7B5EA7',
        icon: 'flash_on',
      },
      {
        id: 'agent-script-beta-intro',
        title: 'Agent Script beta rolls into Agentforce 360 for hybrid reasoning',
        date: '2025-11-05',
        dateLabel: 'Nov 5, 2025',
        summary:
          'The beta release highlights hybrid reasoning with Agent Script guardrails plus Atlas-powered instructions that transform high-level prompts into deterministic branches.',
        url: 'https://www.salesforce.com/ap/news/press-releases/2025/10/14/welcome-to-the-agentic-enterprise-with-agentforce-360-salesforce-elevates-human-potential-in-the-age-of-ai-2/',
        accent: '#7B5EA7',
        icon: 'rocket_launch',
      },
      {
        id: 'agent-script-builder-beta',
        title: 'Build enterprise-ready agents with the new Agent Script view (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Agentforce Builder\'s Script view documents deterministic steps, quick actions, and topics in one place so reasoning stays predictable.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'developer_mode',
      },
      {
        id: 'agent-script-reasoning-instructions',
        title: 'Reasoning instructions keep Agent Script predictable',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Guardrails let you decide where the LLM can flex and where the agent executes deterministic logic, eliminating surprises in topic transitions.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#reasoning',
        accent: '#7B5EA7',
        icon: 'gavel',
      },
      {
        id: 'agent-script-variables-conditions',
        title: 'Variables and conditions power repeatable decisions',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Store agent state, compare values, and branch to next actions or topics without relying solely on LLM memory.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#expressions',
        accent: '#7B5EA7',
        icon: 'tune',
      },
      {
        id: 'agent-script-combine-determinism',
        title: 'Combine Determinism and LLM Reasoning with Agent Script (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Agent Script introduces deterministic flows blended with LLM reasoning.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_script.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'architecture',
      },
      {
        id: 'agent-script-previews',
        title: 'Confidently Build Agents with In-Depth Agent Previews (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Previews help you understand how Agent Script flows behave.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_test.htm&release=258&type=5',
        accent: '#7B5EA7',
        icon: 'visibility',
      },
      {
        id: 'agent-script-editor-expansion',
        title: 'Canvas, quick actions, and DX editing for Agent Script',
        date: '2026-01-15',
        dateLabel: 'Jan 15, 2026',
        summary:
          'Canvas view summarizes script blocks, slash shortcuts add common expressions, and Agentforce DX/VS Code extensions keep syntax, autocomplete, and validation close at hand.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html',
        accent: '#7B5EA7',
        icon: 'code',
      },
      {
        id: 'agent-script-flow-control',
        title: 'Flow-of-control patterns show how to hand off topics',
        date: '2026-02-05',
        dateLabel: 'Feb 5, 2026',
        summary:
          'New patterns illustrate how to combine deterministic transitions and topic handoffs so the agent always knows the next step.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#flow-of-control',
        accent: '#7B5EA7',
        icon: 'swap_horiz',
      },
      {
        id: 'agent-script-patterns-library',
        title: 'Agent Script patterns and reference guide expand',
        date: '2026-03-01',
        dateLabel: 'Mar 1, 2026',
        summary:
          'The Agent Script documentation now highlights reusable patterns, code examples, and reference tables so builders can copy proven logic quickly.',
        url: 'https://developer.salesforce.com/docs/ai/agentforce/guide/agent-script.html#patterns',
        accent: '#7B5EA7',
        icon: 'library_books',
      },
    ],
        useCases: ['Deterministic flows', 'Hybrid reasoning', 'Multi-channel support'],
      },
      {
        id: 'legacy-builder',
        symbol: 'Lb',
        name: 'Legacy Builder',
        label: 'Legacy Builder',
        icon: 'handyman',
        accent: '#0176D3',
        type: 'child',
        tagline: 'Classic agent builder for traditional flows.',
        description: 'Track the transition from the Legacy Builder to the modern Agentforce Builder experience.',
        storyline: [
          'Understand where Builder capabilities migrated',
          'Map legacy flows to the new Agent Script structure',
          'Enable the new Builder for your organization',
        ],
        specs: {
          transition: 'Beta + GA',
          model: 'GPT-4o',
          focus: 'Builder migration',
        },
        capabilities: {
          channelSupport: [
            { name: 'Email', icon: 'email', accent: '#06A59A', available: true },
            { name: 'Slack', icon: 'chat', accent: '#E01E5A', available: true },
            { name: 'Service Agent', icon: 'support_agent', accent: '#0176D3', available: true },
            { name: 'Employee Agent', icon: 'badge', accent: '#9C27B0', available: true },
            { name: 'Voice', icon: 'phone', accent: '#06A59A', available: true },
          ],
          features: [
            { name: 'Supports RAG', icon: 'library_books', accent: '#FFDB3C', available: true },
          ],
        },
        releases: [
          {
            id: 'legacy-escalate-reps',
            title: 'Escalate complex employee agent conversations to reps',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'When an employee agent needs human help, escalation routes conversations to the right rep without losing context.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_escalate_conversations_to_reps.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'support_agent',
          },
          {
            id: 'legacy-welcome-recommendations',
            title: 'Customize welcome recommendations in Agentforce Builder',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'Fine-tune the welcome experience so intelligent recommendations greet customers with the right next steps.',
            url: 'https://help.salesforce.com/s/articleView?language=en_US&id=release-notes.rn_einstein_customize_welcome_reco_in_agentforce_builder.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'recommend',
          },
          {
            id: 'legacy-migrate-employee-agent',
            title: 'Easily migrate from Agentforce to an Employee Agent',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'A guided setup flow walks admins through converting a default Agentforce bot into an employee-facing agent.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_easily_migrate_af_to_aea.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'swap_horiz',
          },
          {
            id: 'legacy-enhanced-connections',
            title: 'Easily add agents to multiple channels with enhanced connections setup',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary:
              'The new connections panel streamlines attaching Agents to voice, chat, and digital channels from a single place.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_enhanced_connections_panel.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'settings_input_component',
          },
          {
            id: 'legacy-service-email-connection',
            title: 'Deliver emails with the Service Email connection',
            date: '2025-12-04',
            dateLabel: "Winter '26",
            summary: 'Agentforce Builder now wires email delivery channels into classic service email pipelines.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_email_connection.htm&release=258&type=5',
            accent: '#0176D3',
            icon: 'email',
          },
          {
            title: 'New Agentforce Builder Availability in Agentforce Studio',
            date: '2026-02-20',
            dateLabel: 'Feb 20, 2026',
            summary: 'The new Builder lands in Agentforce Studio with usability improvements.',
            url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
            accent: '#0176D3',
            icon: 'new_releases',
          },
          {
            title: 'Build Complex Agents Faster with Canvas View Enhancements',
            date: '2026-01-05',
            dateLabel: 'Week of Jan 5, 2026',
            summary: 'Canvas View upgrades accelerate complex branching.',
            url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
            accent: '#0176D3',
            icon: 'grid_view',
          },
          {
            title: 'Connect Agents to Your Knowledge Sources in the New Builder',
            date: '2026-01-05',
            dateLabel: 'Release 260',
            summary: 'Knowledge connections now live inside the modern Builder.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_data_library_new_builder.htm&release=260&type=5',
            accent: '#0176D3',
            icon: 'book',
          },
        ],
        useCases: ['Legacy agent migration', 'Traditional flows', 'Multi-channel support'],
      },
    ],
  },
  {
    id: 'testing-center',
    symbol: 'Tc',
    name: 'Testing Center',
    label: 'Testing Center',
    icon: 'bug_report',
    accent: '#FFDB3C',
    type: 'standalone',
    tagline: 'Preview and validation are now part of Builder testing.',
    description: 'Capture confidence with testing features such as previews and validation tools.',
    storyline: [
      'Kick off testing cycles inside the Builder',
      'Inspect agent previews before deployment',
      'Validate flows with the new guardrails',
    ],
    specs: {
      focus: 'Previews + Validation',
      status: 'Beta',
    },
    announcements: [
      {
        id: 'testing-center-ga',
        title: 'New Testing Center',
        date: '2026-06-01',
        status: 'GA (June)',
        icon: 'bug_report',
        accent: '#FFDB3C',
        summary: 'The new Testing Center makes E2E agent testing easier with inline editing, run history, and custom scorers.',
        highlights: [
          'Inline test editing (no CSV files)',
          'Run history with comparison',
          'Custom LLM Judge scorers',
          'Enhanced JSON debugging',
        ],
      },
      {
        id: 'multi-turn-testing-pilot',
        title: 'Multi-Turn Conversation Testing',
        date: '2026-04-01',
        status: 'Pilot',
        icon: 'forum',
        accent: '#FFDB3C',
        summary: 'Pilot program for multi-turn conversation simulation with voice and text playback testing.',
        highlights: [
          'Generate realistic conversations',
          'Audio playback for voice testing',
          'Task resolution scorers',
        ],
      },
    ],
    releases: [
      {
        title: 'Build High-Quality Agents with Validation Enhancements (Beta)',
        date: '2026-01-05',
        dateLabel: 'Week of Jan 5, 2026',
        summary: 'Validation tooling ships to harden agent quality.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_builder_validation.htm&release=260&type=5',
        accent: '#FFDB3C',
        icon: 'check_circle',
      },
      {
        title: 'Confidently Build Agents with In-Depth Agent Previews (Beta)',
        date: '2025-12-04',
        dateLabel: 'Dec 4, 2025',
        summary: 'Agent previews help test interactions before release.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_builder_test.htm&release=258&type=5',
        accent: '#FFDB3C',
        icon: 'visibility',
      },
    ],
    useCases: ['Agent validation', 'Preview testing', 'Quality assurance'],
  },
  {
    id: 'agentforce-voice',
    symbol: 'Av',
    name: 'Agentforce Voice',
    label: 'Agentforce Voice',
    icon: 'headset_mic',
    accent: '#06A59A',
    type: 'standalone',
    tagline: 'Voice conversations for Agentforce Service agents.',
    description: 'Agentforce Voice enables Service agents to speak and understand voice conversations with customers. Uses speech-to-text models (such as Deepgram), Flash Planner with OpenAI GPT for reasoning, and text-to-speech models (such as ElevenLabs) to handle voice interactions. Requires Service Cloud Voice.',
    storyline: [
      'Customer speaks into phone',
      'Speech-to-text model converts spoken words to text',
      'Flash Planner processes intent using OpenAI GPT LLM',
      'Text response converted to audio using text-to-speech model',
      'Agent can escalate to human when needed',
    ],
    specs: {
      prerequisite: 'Service Cloud Voice required',
      providers: 'Speech-to-text, OpenAI GPT LLM, Text-to-speech',
      language: 'English only',
      concurrentCalls: '500 per org maximum',
      dataRetention: 'Zero data retention',
      routing: 'PSTN or SIP',
    },
    announcements: [
      {
        id: 'agentforce-voice-ga',
        title: 'Agentforce Voice GA',
        date: '2026-04-20',
        status: 'GA',
        icon: 'headset_mic',
        accent: '#06A59A',
        summary: 'AI Voice with Complete Context — natively leverages Salesforce data for seamless human handoffs and deterministic controls.',
        highlights: [
          'Complete context from Salesforce data',
          'Seamless agent-to-human escalations',
          'Turn-by-turn observability',
        ],
      },
      {
        id: 'agent-script-voice',
        title: 'Agent Script for Voice Agents',
        date: '2026-05-01',
        status: 'GA',
        icon: 'settings_voice',
        accent: '#06A59A',
        summary: 'Voice agents can now use Agent Script deterministic flows for predictable telephony experiences.',
        highlights: [
          'Deterministic voice flows',
          'Conditional branching for call routing',
          'Voice-specific guardrails',
        ],
      },
      {
        id: 'voice-multilingual-beta',
        title: 'Multi-Language Support',
        date: '2026-05-01',
        status: 'Beta (May/June)',
        icon: 'translate',
        accent: '#06A59A',
        summary: 'Expand voice support to Italian, Spanish (MX/ES), Japanese, Portuguese (BR/PT), and German.',
        highlights: [
          'Beta: 5 new languages (May/June)',
          'Early Q3: 10+ languages including ASEAN, Nordics, Chinese',
        ],
      },
      {
        id: 'voice-enhanced-chat',
        title: 'Voice for Enhanced Chat',
        date: '2026-05-01',
        status: 'GA (May)',
        icon: 'record_voice_over',
        accent: '#06A59A',
        summary: 'Guide decisions in the moment — help customers complete tasks without leaving the flow.',
        highlights: [
          'Voice and text in one conversation',
          'In-flow decision support',
          'Seamless mode switching',
        ],
      },
      {
        id: 'voice-mobile',
        title: 'Voice in Mobile',
        date: '2026-05-01',
        status: 'GA (May)',
        icon: 'phone_android',
        accent: '#06A59A',
        summary: 'Voice natively embedded in mobile apps — tap and speak hands-free without dialing.',
        highlights: [
          'In-app voice (no phone dialing)',
          'Hands-free task completion',
          'Secure in-session authentication',
        ],
      },
      {
        id: 'voice-whatsapp',
        title: 'Voice in WhatsApp',
        date: '2026-04-01',
        status: 'Beta',
        icon: 'chat',
        accent: '#06A59A',
        summary: 'Voice notes for low-effort messaging — switch to live voice without restarting the conversation.',
        highlights: [
          'Send voice notes instead of typing',
          'Escalate to live voice calls',
          'Continuous conversation thread',
        ],
      },
    ],
    useCases: [
      'Voice conversations with customers',
      'Understanding customer intent from spoken input',
      'Taking actions to resolve customer queries',
      'Escalating to human agents when needed',
    ],
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=ai.agentforce_voice.htm&type=5',
      setup: 'https://help.salesforce.com/s/articleView?id=ai.agent_connect_telephony_parent.htm&type=5',
      voiceSettings: 'https://help.salesforce.com/s/articleView?id=ai.agent_configure_voice_settings.htm&type=5',
      monitoring: 'https://help.salesforce.com/s/articleView?id=ai.monitor_voice_enabled_agents.htm&type=5',
    },
    releases: [
      {
        id: 'agentforce-voice-english-launch',
        title: 'Agentforce Voice launches with English-only support',
        date: '2025-10-13',
        dateLabel: 'Oct 13, 2025',
        summary: 'Agentforce Voice debuts in English so your teams can prototype telephony interactions with Builder agents.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_voice.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'language',
      },
      {
        id: 'agentforce-voice-billing-usage-types',
        title: 'New billable usage types for Agentforce Voice',
        date: '2025-10-24',
        dateLabel: 'Oct 24, 2025',
        summary: 'Define new billing buckets for telephony and track voice usage as part of Agentforce analytics.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_billing_flex_voice_usage_type.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'monetization_on',
      },
      {
        id: 'agentforce-voice-enable-service-agents',
        title: 'Enable voice conversations for Agentforce Service Agents',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary: 'Agentforce Voice now powers service agents that can answer calls, escalate to humans, and keep sessions secure.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_voice.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'support_agent',
      },
      {
        id: 'agentforce-voice-keyterm-prompting',
        title: 'Help your voice-enabled agent recognize key terms',
        date: '2025-12-15',
        dateLabel: 'Week of Dec 15, 2025',
        summary: 'Key-term prompting lets you highlight important phrases so Agentforce Voice senses critical triggers during calls.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_agent_voice_keyterm_prompting.htm&release=258&type=5',
        accent: '#06A59A',
        icon: 'settings_voice',
      },
      {
        id: 'agentforce-voice-minutes-usage',
        title: 'Introduce the Agentforce Voice minutes usage type',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Track Agentforce Voice minutes separately to understand telephony spend and optimize workloads.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_billing_voice_minutes.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'timer',
      },
      {
        id: 'agentforce-voice-sip-routing',
        title: 'Route Agentforce Voice calls using SIP',
        date: '2026-03-30',
        dateLabel: 'Mar 30, 2026',
        summary: 'SIP routing gives you flexibility to connect Agentforce Voice into existing telephony carriers.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_agentforce_voice_with_sip.htm&release=260&type=5',
        accent: '#06A59A',
        icon: 'network_cell',
      },
    ],
  },
  {
    id: 'observability',
    symbol: 'Ob',
    name: 'Observability',
    label: 'Observability',
    icon: 'visibility',
    accent: '#00BFA5',
    type: 'parent',
    tagline: 'Full-stack observability from metrics to root cause.',
    description: 'Comprehensive observability framework combining metrics, traces, execution data, and real-time monitoring across the full Agentforce lifecycle.',
    storyline: [
      'Turn on Session Tracing to record every conversation',
      'Monitor aggregate metrics in Agent Analytics dashboards',
      'Debug specific sessions with Agent Optimization',
      'Analyze platform performance with latency breakdowns',
      'Get proactive alerts via Agent Health Monitoring',
    ],
    specs: {
      focus: 'Runtime observability',
      layers: '5 observability layers',
      dataModel: 'Session Tracing Data Model (STDM)',
    },
    announcements: [
      {
        id: 'agent-health-monitoring',
        title: 'Agent Health Monitoring',
        date: '2026-05-01',
        status: 'GA (May)',
        icon: 'monitor_heart',
        accent: '#00BFA5',
        summary: 'Near real-time monitoring and alerting on key operational health metrics with proactive issue resolution.',
        highlights: [
          'Real-time error tracking (5-min intervals)',
          'Customizable threshold alerts',
          'Latency and escalation monitoring',
          'Email notifications with cooldown',
        ],
      },
    ],
    useCases: [
      'Production monitoring and alerting',
      'Quality assurance and testing',
      'Root cause analysis and debugging',
      'Performance optimization',
      'Compliance and audit trails',
    ],
    releases: [
      {
        id: 'observability-agentforce-studio',
        title: 'Monitor your agents more easily with Agentforce Studio',
        date: '2025-09-01',
        dateLabel: 'Sep 2025',
        summary:
          'Agentforce Studio surfaces Observability dashboards so admins can review session health and move quickly from insights to action.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agentforce_studio.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'dashboard',
      },
      {
        id: 'observability-agent-optimization-beta',
        title: 'Explore Agentforce Optimization (Beta)',
        date: '2025-09-01',
        dateLabel: 'Sep 2025',
        summary:
          'Agentforce Optimization Beta surfaces early insights, traces, and moments to help you experiment with agent improvements.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_optimization.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'insights',
      },
      {
        id: 'observability-agent-optimization-ga',
        title: 'Agentforce Optimization GA unlocks better traces and intents',
        date: '2025-11-05',
        dateLabel: 'Nov 5, 2025',
        summary:
          'Session trace enhancements, voice agent support, and the renaming of Moments to Intents make optimization ready for production use.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_optimization_ga.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'trending_up',
      },
      {
        id: 'observability-agent-analytics-ga',
        title: 'Track agent performance and quality metrics with Agent Analytics',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'New dashboards show error rate, unique user count, action counts, and a Quality tab for service agents and employee agents.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_analytics_performance_quality_ga.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'bar_chart',
      },
      {
        id: 'observability-task-resolution-beta',
        title: 'Measure agent outcomes with Task Resolution (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Capture structured outcomes for each task so you can analyze success rates and drop-off points before going GA.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_task_resolution.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'assignment_turned_in',
      },
      {
        id: 'observability-agent-analytics-tableau',
        title: 'Gain dynamic insights with Agentforce Analytics powered by Tableau Next (Beta)',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Tableau Next adds deeper dashboards and guided analytics so you can explore agent behavior across datasets.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_analytics.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'table_chart',
      },
      {
        id: 'observability-session-tracing',
        title: 'Gain visibility into agent behavior with Agentforce Session Tracing',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Session traces record the entire conversation so you can replay, debug, and audit every decision path.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_session_tracing.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'timeline',
      },
      {
        id: 'observability-knowledge-retrieval',
        title: 'Gain visibility into knowledge retrieval quality',
        date: '2025-12-04',
        dateLabel: 'Winter \'26',
        summary:
          'Track which knowledge results were surfaced so you can refine retrieval pipelines for accuracy and relevance.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_retrieval_quality.htm&release=258&type=5',
        accent: '#00BFA5',
        icon: 'search',
      },
      {
        id: 'observability-task-resolution-ga',
        title: 'Task Resolution Support for New Agentforce Builder Agents',
        date: '2026-01-05',
        dateLabel: 'Release 260',
        summary: 'Agents created with the new Builder gain Task Resolution.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_agent_task_resolution_ga.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'task_alt',
      },
      {
        id: 'observability-enhancements-spring26',
        title: 'Observability enhancements: breadcrumb navigation, UI tweaks, and analytics metrics',
        date: '2026-03-30',
        dateLabel: 'Spring \'26',
        summary:
          'Optimization breadcrumb navigation, refreshed UI, and extra analytics metrics make it easier to spot trends.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_observability_enhancements.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'layers',
      },
      {
        id: 'observability-rag-metrics',
        title: 'Evaluate AI performance with new RAG metrics and enriched analytics',
        date: '2026-03-30',
        dateLabel: 'Spring \'26',
        summary:
          'New RAG metrics and enriched analytics help you understand how grounding sources influence answers.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_analytics_metrics.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'analytics',
      },
      {
        id: 'observability-voice-optimization',
        title: 'Voice optimization: session playback and dashboard enhancements',
        date: '2026-03-30',
        dateLabel: 'Spring \'26',
        summary:
          'Voice session playback and dashboard upgrades make it easier to audit conversation quality and agent decisions.',
        url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_optimization_voice.htm&release=260&type=5',
        accent: '#00BFA5',
        icon: 'mic',
      },
      {
        id: 'observability-health-monitoring-beta',
        title: 'Agent Health Monitoring (Beta) — Proactive alerting for production agents',
        date: '2026-04-15',
        dateLabel: 'Spring \'26',
        summary:
          'Real-time monitoring tracks error rates, latency, and escalations every 5 minutes with customizable threshold alerts.',
        url: 'https://www.salesforce.com/blog/agent-monitoring/',
        accent: '#00BFA5',
        icon: 'monitor_heart',
      },
    ],
    children: [
      {
        id: 'agent-analytics',
        symbol: 'Aa',
        name: 'Agent Analytics',
        label: 'Agent Analytics',
        icon: 'bar_chart',
        accent: '#00BFA5',
        type: 'child',
        tagline: 'Aggregate KPIs across all agent interactions.',
        description: 'Built on Session Tracing Data Model (STDM). Provides metrics dashboards showing deflection rates, escalations, quality scores, and session outcomes.',
        storyline: [
          'Admin opens Agentforce Studio Analytics tab',
          'Selects Service Agent Analytics dashboard',
          'Reviews Total Sessions, Deflection Rate (78%), Escalation Rate (12%)',
          'Notices deflection dropped to 52% this week — signals a problem',
          'Drills into Agent Optimization to find root cause',
        ],
        flowSteps: [
          {
            stage: 'Issue',
            icon: 'error',
            accent: '#EA001E',
            title: 'Deflection rate suddenly drops 26 points',
            description: 'VP notices customer escalations spiking in the quarterly review — deflection fell from 78% to 52%',
          },
          {
            stage: 'Detect',
            icon: 'bar_chart',
            accent: '#0176D3',
            title: 'Open Agent Analytics dashboard',
            description: 'Filter by date range and channel — see billing dispute sessions show 34% escalation vs 12% baseline',
          },
          {
            stage: 'Diagnose',
            icon: 'troubleshoot',
            accent: '#FE9339',
            title: 'Identify the pattern',
            description: 'Quality scores dropped for billing dispute intent — signals either content gap or performance issue',
          },
          {
            stage: 'Resolve',
            icon: 'check_circle',
            accent: '#45C65A',
            title: 'Drill into Agent Optimization',
            description: 'Use session-level traces to find root cause — wrong article or slow query (see next flows)',
          },
        ],
        specs: {
          availability: 'GA (Winter \'26)',
          dataModel: 'Session Tracing Data Model (STDM)',
          dashboards: 'Service Agent, Employee Agent, Overview',
          metrics: 'Deflection, Escalation, Quality Score, Latency',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Deflection Rate Tracking', icon: 'trending_down', accent: '#45C65A', available: true },
            { name: 'Quality Scores (1-5)', icon: 'star', accent: '#FFDB3C', available: true },
            { name: 'Error Rate Monitoring', icon: 'error', accent: '#EA001E', available: true },
            { name: 'Average Latency', icon: 'speed', accent: '#00BFA5', available: true },
          ],
        },
        releases: [],
        useCases: [
          'Detect anomalies in agent performance',
          'Track deflection and escalation trends',
          'Monitor quality scores across agents',
          'Executive reporting and KPI dashboards',
        ],
      },
      {
        id: 'session-tracing',
        symbol: 'St',
        name: 'Agentforce Session Tracing',
        label: 'Session Tracing',
        icon: 'timeline',
        accent: '#00BFA5',
        type: 'child',
        tagline: 'Turn on the cameras — record every conversation.',
        description: 'Captures full execution path of every session in Data Cloud. Records user input, intent classification, retrieval queries, LLM prompts/responses, and actions invoked.',
        storyline: [
          'Admin enables Session Tracing in Setup → Einstein Audit, Analytics, and Monitoring',
          'Every conversation Aria has is now recorded in Data Cloud',
          'Session data includes: user input, reasoning steps, knowledge retrieval, actions, responses',
          'Data flows to DLOs/DMOs in Session Tracing Data Model (STDM)',
          'Without this, the next 3 observability layers do not exist',
        ],
        flowSteps: [
          {
            stage: 'Issue',
            icon: 'error',
            accent: '#EA001E',
            title: 'No visibility into agent behavior',
            description: 'Agent launched in production but team has no data on what users are asking or how the agent responds',
          },
          {
            stage: 'Detect',
            icon: 'timeline',
            accent: '#0176D3',
            title: 'Enable Session Tracing in Setup',
            description: 'Navigate to Setup → Einstein Audit, Analytics, and Monitoring → turn on Session Tracing',
          },
          {
            stage: 'Diagnose',
            icon: 'troubleshoot',
            accent: '#FE9339',
            title: 'Data starts flowing to Data Cloud',
            description: 'Every conversation is now captured — user input, reasoning, retrieval, actions, responses all logged',
          },
          {
            stage: 'Resolve',
            icon: 'check_circle',
            accent: '#45C65A',
            title: 'Foundation for all observability',
            description: 'Agent Analytics, Optimization, and Platform Tracing now have data to analyze',
          },
        ],
        specs: {
          availability: 'GA (Winter \'26)',
          dataModel: 'DLOs/DMOs in Data Cloud',
          storage: 'Data 360 (Data Cloud)',
          retention: 'Configurable',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Turn-by-turn capture', icon: 'record_voice_over', accent: '#00BFA5', available: true },
            { name: 'LLM prompt/response logs', icon: 'chat', accent: '#7B5EA7', available: true },
            { name: 'Action execution traces', icon: 'play_arrow', accent: '#0176D3', available: true },
            { name: 'Retrieval query logs', icon: 'search', accent: '#FFDB3C', available: true },
          ],
        },
        releases: [],
        useCases: [
          'Deterministic visibility into agent execution',
          'Debugging incorrect responses',
          'Compliance and audit trails',
          'Training data for model improvements',
        ],
      },
      {
        id: 'agent-optimization',
        symbol: 'Ao',
        name: 'Agent Optimization',
        label: 'Agent Optimization',
        icon: 'insights',
        accent: '#00BFA5',
        type: 'child',
        tagline: 'Find the culprit — debug logic and retrieval.',
        description: 'Analyzes correctness of agent decisions. Includes Quality Scores (1-5) calculated by LLM, identifies knowledge gaps, and highlights retrieval failures.',
        storyline: [
          'Admin pulls up Agent Optimization in Agentforce Studio',
          'Filters sessions from Tuesday tagged "billing dispute"',
          'Traces one session step-by-step: User asks "Why was I charged twice?"',
          'Step 2: Aria searches Knowledge Base → returns wrong article',
          'Step 3: Aria gives confident but incorrect answer → User escalates',
          'Root cause: Knowledge article for billing disputes was outdated',
        ],
        flowSteps: [
          {
            stage: 'Issue',
            icon: 'error',
            accent: '#EA001E',
            title: 'Agent gives wrong answers',
            description: 'User asks "Why was I charged twice?" but agent returns outdated refund policy article from 2019',
          },
          {
            stage: 'Detect',
            icon: 'insights',
            accent: '#0176D3',
            title: 'Filter by intent and quality score',
            description: 'Open Agent Optimization, filter sessions tagged "billing dispute" with Quality Score < 3',
          },
          {
            stage: 'Diagnose',
            icon: 'troubleshoot',
            accent: '#FE9339',
            title: 'Review session trace',
            description: 'See retrieval action returned article KB-2019-45 (archived) instead of KB-2025-12 (current policy)',
          },
          {
            stage: 'Resolve',
            icon: 'check_circle',
            accent: '#45C65A',
            title: 'Fix knowledge article metadata',
            description: 'Update KB-2025-12 with keywords "double charge" and "duplicate billing", archive outdated article',
          },
        ],
        specs: {
          availability: 'GA (Fall \'25)',
          qualityScores: 'LLM-calculated (1-5 scale)',
          intents: 'Clustered and tagged weekly',
          voice: 'Session playback supported',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Intent clustering', icon: 'category', accent: '#9C27B0', available: true },
            { name: 'Quality Score analysis', icon: 'star_rate', accent: '#FFDB3C', available: true },
            { name: 'Knowledge gap detection', icon: 'help_outline', accent: '#EA001E', available: true },
            { name: 'Voice playback', icon: 'play_circle', accent: '#06A59A', available: true },
          ],
        },
        releases: [],
        useCases: [
          'Debug incorrect agent responses',
          'Identify knowledge article gaps',
          'Analyze retrieval quality (RAG)',
          'Improve topic instructions',
        ],
      },
      {
        id: 'platform-tracing',
        symbol: 'Pt',
        name: 'Agent Platform Tracing',
        label: 'Platform Tracing',
        icon: 'memory',
        accent: '#00BFA5',
        type: 'child',
        tagline: 'Why is Aria so slow? Find the bottleneck.',
        description: 'Breaks down execution time across system components: LLM inference, retrieval latency, Flow execution, and Apex/SOQL performance.',
        storyline: [
          'Engineer notices Aria is slow — 8-10 seconds per turn',
          'Opens Agent Platform Tracing and X-rays infrastructure',
          'Latency breakdown: LLM call (1.2s), Knowledge retrieval (0.8s), Flow execution (6.4s)',
          'Drills into Flow → Apex invocation inside Flow',
          'Finds unoptimized SOQL query hitting 50,000 records every turn',
          'Fixes SOQL query → Aria response time drops to under 2 seconds',
        ],
        flowSteps: [
          {
            stage: 'Issue',
            icon: 'error',
            accent: '#EA001E',
            title: 'Agent is too slow',
            description: 'Users complain Aria takes 8-10 seconds to respond — timeout errors increasing',
          },
          {
            stage: 'Detect',
            icon: 'memory',
            accent: '#0176D3',
            title: 'Open Agent Platform Tracing',
            description: 'X-ray infrastructure to see latency breakdown: LLM 1.2s ✓ | Retrieval 0.8s ✓ | Flow 6.4s ✗',
          },
          {
            stage: 'Diagnose',
            icon: 'troubleshoot',
            accent: '#FE9339',
            title: 'Drill into Flow execution',
            description: 'Flow calls Apex, which runs SOQL query scanning 50,000 Account records on every turn',
          },
          {
            stage: 'Resolve',
            icon: 'check_circle',
            accent: '#45C65A',
            title: 'Optimize the SOQL query',
            description: 'Add indexed filter to reduce query to 200 records — response time drops from 8s to under 2s',
          },
        ],
        specs: {
          availability: 'Pilot / Limited Release',
          metrics: 'LLM, Retrieval, Flow, Apex, SOQL latency',
          granularity: 'Component-level breakdown',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'LLM inference time', icon: 'psychology', accent: '#7B5EA7', available: true },
            { name: 'Retrieval latency', icon: 'search', accent: '#FFDB3C', available: false },
            { name: 'Flow execution time', icon: 'account_tree', accent: '#0176D3', available: false },
            { name: 'Apex/SOQL analysis', icon: 'code', accent: '#EA001E', available: false },
          ],
        },
        releases: [],
        useCases: [
          'Identify latency bottlenecks',
          'Optimize slow SOQL queries',
          'Debug Flow performance issues',
          'Reduce timeout errors',
        ],
      },
      {
        id: 'health-monitoring',
        symbol: 'Hm',
        name: 'Agent Health Monitoring',
        label: 'Health Monitoring',
        icon: 'monitor_heart',
        accent: '#00BFA5',
        type: 'child',
        tagline: 'Prevent recurrence — proactive alerting.',
        description: 'Real-time monitoring tracks error rates, latency spikes, and escalation anomalies every 5 minutes. Enables customizable threshold alerts with email notifications.',
        storyline: [
          'Admin configures alert: "Notify me if error rate > 5% for 15 minutes"',
          'Tuesday 10:15 AM: Error rate spikes to 8% (billing dispute intent)',
          'Alert triggers email: "Aria error rate exceeded threshold"',
          'Admin investigates before customers complain',
          'Proactive detection → faster MTTR → prevents customer escalations',
        ],
        flowSteps: [
          {
            stage: 'Issue',
            icon: 'error',
            accent: '#EA001E',
            title: 'Error rate spikes unexpectedly',
            description: 'Tuesday 10:15 AM — error rate jumps to 8% for billing dispute sessions (baseline is 2%)',
          },
          {
            stage: 'Detect',
            icon: 'monitor_heart',
            accent: '#0176D3',
            title: 'Alert triggers automatically',
            description: 'Email sent: "Aria error rate exceeded 5% threshold" — admin notified before customers complain',
          },
          {
            stage: 'Diagnose',
            icon: 'troubleshoot',
            accent: '#FE9339',
            title: 'Check Health Monitoring dashboard',
            description: 'Dashboard shows error spike correlates with billing dispute intent — possible knowledge gap',
          },
          {
            stage: 'Resolve',
            icon: 'check_circle',
            accent: '#45C65A',
            title: 'Use Agent Optimization to fix',
            description: 'Drill into Agent Optimization to find root cause — update knowledge article or fix query',
          },
        ],
        specs: {
          availability: 'Beta (Spring \'26)',
          frequency: 'Every 5 minutes',
          alerting: 'Email with 30-min cooldown',
          metrics: 'Error rate, latency, escalation rate',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Real-time error tracking', icon: 'error', accent: '#EA001E', available: true },
            { name: 'Latency spike detection', icon: 'speed', accent: '#00BFA5', available: true },
            { name: 'Escalation anomalies', icon: 'trending_up', accent: '#FFDB3C', available: true },
            { name: 'Custom threshold alerts', icon: 'notifications', accent: '#0176D3', available: true },
          ],
        },
        releases: [],
        useCases: [
          'Proactive issue detection',
          'Prevent silent failures',
          'Reduce MTTR (Mean Time To Resolution)',
          'Production confidence for scaling AI agents',
        ],
      },
      {
        id: 'broken-agent-story',
        symbol: 'Us',
        name: 'The Case of the Broken Agent',
        label: 'Use Case Story',
        icon: 'auto_stories',
        accent: '#00BFA5',
        type: 'child',
        tagline: 'A story in 4 acts — how observability saved Aria.',
        description: 'Acme Corp just launched their new Agentforce customer service agent — "Aria". Thousands of customers are chatting with Aria daily about orders, returns, and billing. This is how they used the 5 observability layers to detect, debug, and fix a major incident.',
        storyline: [
          '🎬 THE PROBLEM — Week 2: Something is broken',
          'Acme Corp launched Aria (Agentforce agent) 2 weeks ago — deflection was 78%',
          'Now deflection drops to 52% and escalations spike',
          'Customers are frustrated, VP demands answers',
          '',
          '🔍 DETECT — Use Agent Analytics to spot the anomaly',
          'VP opens Agent Analytics dashboard in Agentforce Studio',
          'Sees deflection rate dropped 26 points in billing dispute sessions',
          'Escalation rate jumped from 12% to 34% for those conversations',
          '',
          '🧪 DIAGNOSE — Use Session Tracing + Optimization to find root cause',
          'Admin filters Agent Optimization by "billing dispute" tag',
          'Finds the pattern: Wrong knowledge article being returned',
          'User asks "Why was I charged twice?" → Aria returns outdated policy article → User escalates',
          'Then opens Agent Platform Tracing — notices Flow taking 6.4 seconds',
          'Root cause found: SOQL query scanning 50,000 records on every turn',
          '',
          '✅ RESOLVE — Fix content + optimize performance',
          'Admin updates the billing dispute knowledge article with correct policy',
          'Engineer adds indexed filter to SOQL query, reducing scan to 200 records',
          'Response time drops from 8 seconds to under 2 seconds',
          'Deflection rate climbs back to 80% within 3 days',
          'Team now monitors all 4 layers weekly to catch issues early',
        ],
        specs: {
          type: 'Use Case Example',
          company: 'Acme Corp (fictional)',
          agent: 'Aria (Agentforce Service Agent)',
          outcome: 'Deflection rate recovered from 52% to 80%',
          incident: 'Billing disputes returning wrong knowledge articles + slow SOQL query',
          resolution: 'Updated knowledge article + optimized SOQL query',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Session Tracing', icon: 'videocam', accent: '#00BFA5', available: true },
            { name: 'Agent Analytics', icon: 'bar_chart', accent: '#00BFA5', available: true },
            { name: 'Agent Optimization', icon: 'insights', accent: '#00BFA5', available: true },
            { name: 'Platform Tracing', icon: 'memory', accent: '#00BFA5', available: true },
          ],
        },
        releases: [],
        useCases: [
          'Production monitoring workflow',
          'Root cause analysis methodology',
          'Cross-layer debugging example',
          'Knowledge gap detection',
          'SOQL query optimization',
          'Observability best practices',
        ],
      },
    ],
  },
  {
    id: 'prompt-builder',
    symbol: 'Pb',
    name: 'Prompt Builder',
    label: 'Prompt Builder',
    icon: 'edit_note',
    accent: '#9C27B0',
    type: 'parent',
    tagline: 'Design and ground prompts with data and knowledge.',
    description: 'Author prompts with knowledge grounding, web data, and CRM context before wiring them into Agent Script flows.',
    storyline: [
      'Author prompt content with semantic context',
      'Ground prompts in knowledge, CRM data, and web sources',
      'Configure limits and guardrails',
      'Reuse prompt blocks across agents',
    ],
    specs: {
      focus: 'Prompt experimentation + Grounding',
      availability: 'Preview 2026',
    },
    announcements: [
      {
        id: 'data-library-enhancements',
        title: 'Data Library Enhancements',
        date: '2026-05-01',
        status: 'Beta',
        icon: 'library_books',
        accent: '#9C27B0',
        summary: 'Enhanced Data Library with expanded web search, domain restrictions, and custom grounding sources.',
        highlights: [
          'Expanded web data sources',
          'Domain restriction controls',
          'Custom retriever support',
        ],
      },
    ],
    releases: [],
    useCases: ['Prompt authoring', 'Knowledge grounding', 'Web data retrieval'],
    children: [
      {
        id: 'prompt-builder-web',
        symbol: 'Pw',
        name: 'Web Grounding',
        label: 'Web Grounding',
        icon: 'language',
        accent: '#9C27B0',
        type: 'child',
        tagline: 'Ground prompts with live web data and search results.',
        description: 'Connect prompts to web search, allowed domains, and multiple search providers to retrieve real-time information.',
        storyline: [
          'Add web search data sources to your Agentforce Data Library',
          'Ground prompts with relevant knowledge from websites',
          'Configure search providers (OpenAI, etc.) and domain restrictions',
          'Use Web Actions to retrieve live data at runtime',
        ],
        specs: {
          availability: 'GA',
          focus: 'Web data retrieval',
          searchProviders: 'OpenAI, Bing, Custom',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Web Search', icon: 'search', accent: '#4285F4', available: true, description: 'Retrieve real-time data from the open web' },
            { name: 'Domain Restrictions', icon: 'shield', accent: '#FE9339', available: true, description: 'Limit search to trusted domains only' },
            { name: 'Multiple Providers', icon: 'hub', accent: '#45C65A', available: true, description: 'Choose from OpenAI, Bing, or custom engines' },
            { name: 'Web Actions', icon: 'bolt', accent: '#7B5EA7', available: true, description: 'Fetch live data at runtime with API calls' },
          ],
        },
        releases: [
          {
            id: 'web-data-library',
            title: 'Add More Data Sources to your Agentforce Data Library with Web Search',
            date: '2025-05-01',
            dateLabel: "Spring '25",
            summary:
              'Web search data sources expand your Data Library so agents can retrieve answers from the open web.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_data_library_web_search.htm&release=254&type=5',
            accent: '#9C27B0',
            icon: 'library_add',
          },
          {
            id: 'web-retriever',
            title: 'Ground Prompts with Relevant Knowledge from Web Sites',
            date: '2025-07-01',
            dateLabel: "Summer '25",
            summary:
              'Prompt Builder web retriever connects prompts to external websites for real-time grounding.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_prompt_builder_web_retriever.htm&release=256&type=5',
            accent: '#9C27B0',
            icon: 'public',
          },
          {
            id: 'general-web-search-topic',
            title: 'Get Summarized Answers with the General Web Search Topic and Action',
            date: '2025-10-01',
            dateLabel: "Winter '26",
            summary:
              'The General Web Search topic and action provide summarized answers from the web inside agent conversations.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_get_summarized_answers_with_general_web_search.htm&release=258&type=5',
            accent: '#9C27B0',
            icon: 'summarize',
          },
          {
            id: 'openai-search-provider',
            title: 'Improve Web Search Results by Using OpenAI as a Search Provider (Beta)',
            date: '2025-12-01',
            dateLabel: "Winter '26",
            summary:
              'OpenAI becomes a search provider option so you can route web queries through OpenAI\'s search engine.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_improve_web_search_results_using_openai.htm&release=258&type=5',
            accent: '#9C27B0',
            icon: 'extension',
          },
          {
            id: 'allowed-domains',
            title: 'Improve Web Search Results By Using Allowed Domains',
            date: '2026-02-17',
            dateLabel: "Spring '26",
            summary:
              'Domain restrictions let you limit web search to trusted sites so agents stay within approved boundaries.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_domain_restriction.htm&release=260&type=5',
            accent: '#9C27B0',
            icon: 'verified',
          },
          {
            id: 'web-actions',
            title: 'Ground Prompts with Live Web Data with Web Actions',
            date: '2026-04-06',
            dateLabel: "Spring '26",
            summary:
              'Web Actions fetch live web data at runtime so prompts always have the most current information.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_prompt_builder_web_actions.htm&release=260&type=5',
            accent: '#9C27B0',
            icon: 'bolt',
          },
          {
            id: 'additional-search-provider',
            title: 'Improve Web Search Results by Using an Additional Search Provider Option',
            date: '2026-04-07',
            dateLabel: "Spring '26",
            summary:
              'Additional search provider options give you flexibility to choose the best search engine for your use case.',
            url: 'https://help.salesforce.com/s/articleView?id=release-notes.rn_einstein_search_provider_option.htm&release=260&type=5',
            accent: '#9C27B0',
            icon: 'tune',
          },
        ],
        useCases: ['Real-time web data retrieval', 'Domain-restricted search', 'Multi-provider search'],
      },
      {
        id: 'prompt-builder-general',
        symbol: 'Pg',
        name: 'General Features',
        label: 'General Features',
        icon: 'build',
        accent: '#9C27B0',
        type: 'child',
        tagline: 'Core prompt authoring and grounding capabilities.',
        description: 'Author prompts with CRM data, knowledge articles, and custom grounding sources.',
        storyline: [
          'Open Prompt Builder and create a new prompt template',
          'Ground prompts with CRM objects, fields, and relationships',
          'Test prompts with sample data before deployment',
          'Reuse prompt templates across multiple agents',
        ],
        specs: {
          availability: 'Preview 2026',
          focus: 'Prompt authoring + CRM grounding',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'CRM Grounding', icon: 'database', accent: '#0176D3', available: true, description: 'Connect prompts to Salesforce objects and fields' },
            { name: 'Knowledge Grounding', icon: 'book', accent: '#FFDB3C', available: true, description: 'Ground responses with knowledge articles' },
            { name: 'Template Reuse', icon: 'content_copy', accent: '#45C65A', available: true, description: 'Share prompts across multiple agents' },
          ],
        },
        releases: [
          {
            id: 'prompt-builder-preview',
            title: 'Prompt Builder Preview inside Agentforce Builder',
            date: '2026-01-05',
            dateLabel: 'Release 260',
            summary:
              'Prompt Builder preview lets you sculpt natural language prompts before deploying them into Agent Script flows.',
            url: 'https://help.salesforce.com/s/articleView?id=ai.agent_builder_intro.htm&type=5',
            accent: '#9C27B0',
            icon: 'preview',
          },
        ],
        useCases: ['Prompt authoring', 'CRM data grounding', 'Template reuse'],
      },
      {
        id: 'prompt-builder-limits',
        symbol: 'Pl',
        name: 'Limits & Guardrails',
        label: 'Limits & Guardrails',
        icon: 'shield_lock',
        accent: '#9C27B0',
        type: 'child',
        tagline: 'Configure limits and safety guardrails for prompts.',
        description: 'Set token limits, rate limits, and safety guardrails to control prompt execution.',
        storyline: [
          'Define token and rate limits for each prompt',
          'Configure safety guardrails to prevent harmful outputs',
          'Monitor limit usage in Observability dashboards',
        ],
        specs: {
          availability: 'Preview 2026',
          focus: 'Safety + Resource limits',
        },
        capabilities: {
          channelSupport: [],
          features: [
            { name: 'Token Limits', icon: 'data_usage', accent: '#EA001E', available: false, description: 'Control max tokens per prompt execution' },
            { name: 'Rate Limiting', icon: 'speed', accent: '#FE9339', available: false, description: 'Throttle prompt calls per time window' },
            { name: 'Safety Guardrails', icon: 'security', accent: '#45C65A', available: false, description: 'Block harmful or inappropriate outputs' },
          ],
        },
        releases: [],
        useCases: ['Resource management', 'Safety controls', 'Usage monitoring'],
      },
    ],
  },
];
