// Agentic Enterprise Platform Announcements
// Maps to the 6 Agentforce Hub tiles: agentforce-grid, agentforce-development, testing-center, agentforce-voice, observability, prompt-builder

export const AGENTIC_SYSTEMS = [
  {
    id: 'system-engagement',
    name: 'System of Engagement',
    icon: 'groups',
    accent: '#0176D3',
    description: 'Where customers and employees interact with AI',
    examples: ['Voice', 'Mobile', 'Digital', 'ChatGPT', 'Slack', 'Agent API'],
  },
  {
    id: 'system-agency',
    name: 'System of Agency',
    icon: 'smart_toy',
    accent: '#7B5EA7',
    description: 'How AI agents orchestrate, reason, and execute',
    layers: [
      { label: 'Experience', items: ['Voice', 'Mobile', 'Digital', 'ChatGPT', 'Slack', 'Agent API'] },
      { label: 'Orchestrate', items: ['Multi-Agent (A2A)', 'Delegation', 'Escalations', 'BYO Agent via A2A'] },
      { label: 'Control', items: ['Agentforce Builder', 'Agentforce Script', 'MCP'] },
      { label: 'Operate', items: ['Optimization', 'Analytics', 'Tracing', 'Audit', 'OpenTelemetry'] },
    ],
  },
  {
    id: 'system-work',
    name: 'System of Work',
    icon: 'business_center',
    accent: '#06A59A',
    description: 'All Salesforce cloud apps and workflows',
    examples: ['Customer 360', 'Sales Cloud', 'Service Cloud', 'Industries'],
  },
  {
    id: 'system-context',
    name: 'System of Context',
    icon: 'storage',
    accent: '#FE9339',
    description: 'Unified data and memory for agents',
    examples: ['Harmonization', 'CDP', 'MDM', 'Agent Memory', '100+ zero-copy connectors'],
  },
];

export const ANNOUNCEMENTS = {
  ga: [
    {
      id: 'agentforce-builder-ga',
      title: 'Agentforce Builder GA',
      date: '2026-04-20',
      tileId: 'agentforce-development',
      icon: 'new_releases',
      accent: '#7B5EA7',
      summary: 'The new Agentforce Builder is now generally available with enhanced canvas view, validation tools, and seamless agent authoring.',
      highlights: [
        'Canvas view for complex agent flows',
        'Enhanced validation and error checking',
        'Integrated testing and preview',
      ],
    },
    {
      id: 'agent-script-ga',
      title: 'Agentforce Script GA',
      date: '2026-04-20',
      tileId: 'agentforce-development',
      icon: 'architecture',
      accent: '#7B5EA7',
      summary: 'Agent Script moves from beta to GA, enabling deterministic flows with LLM reasoning for production-grade agents.',
      highlights: [
        'Combine determinism with LLM reasoning',
        'Variables and conditional branching',
        'DX tooling with VS Code extension',
      ],
    },
    {
      id: 'intelligent-context-ga',
      title: 'Intelligent Context GA',
      date: '2026-04-20',
      tileId: 'agentforce-grid',
      icon: 'psychology',
      accent: '#FE9339',
      summary: 'Intelligent Context is now GA, providing agents with unified memory and real-time data harmonization across systems.',
      highlights: [
        'Unified agent memory across sessions',
        'Real-time data harmonization',
        '100+ zero-copy data connectors',
      ],
    },
    {
      id: 'agentforce-voice-ga',
      title: 'Agentforce Voice GA',
      date: '2026-04-20',
      tileId: 'agentforce-voice',
      icon: 'headset_mic',
      accent: '#06A59A',
      summary: 'AI Voice with Complete Context — natively leverages Salesforce data for seamless human handoffs and deterministic controls.',
      highlights: [
        'Complete context from Salesforce data',
        'Seamless agent-to-human escalations',
        'Turn-by-turn observability',
      ],
    },
  ],
  beta: [
    {
      id: 'curated-memory-pilot',
      title: 'Curated Long Term Memory',
      date: '2026-05-01',
      status: 'Pilot',
      tileId: 'agentforce-grid',
      icon: 'inventory',
      accent: '#FE9339',
      summary: 'Pilot program for curated agent memory — retain context across sessions with intelligent memory management.',
      highlights: [
        'Persistent memory across conversations',
        'Smart memory pruning and prioritization',
        'Privacy-aware memory controls',
      ],
    },
    {
      id: 'data-library-enhancements',
      title: 'Agentforce Data Library Enhancements',
      date: '2026-05-01',
      status: 'Beta',
      tileId: 'prompt-builder',
      icon: 'library_books',
      accent: '#9C27B0',
      summary: 'Enhanced Data Library with expanded web search, domain restrictions, and custom grounding sources.',
      highlights: [
        'Expanded web data sources',
        'Domain restriction controls',
        'Custom retriever support',
      ],
    },
    {
      id: 'agentforce-gemini-ga',
      title: 'Agentforce on Gemini',
      date: '2026-05-01',
      status: 'GA',
      tileId: 'agentforce-development',
      icon: 'auto_awesome',
      accent: '#7B5EA7',
      summary: 'Bring your own model — Agentforce now supports Google Gemini as an alternative LLM provider.',
      highlights: [
        'Google Gemini model support',
        'Multi-model orchestration',
        'Model selection per agent',
      ],
    },
    {
      id: 'agent-script-voice',
      title: 'Agent Script for Voice Agents',
      date: '2026-05-01',
      status: 'GA',
      tileId: 'agentforce-voice',
      icon: 'settings_voice',
      accent: '#06A59A',
      summary: 'Voice agents can now use Agent Script deterministic flows for predictable telephony experiences.',
      highlights: [
        'Deterministic voice flows',
        'Conditional branching for call routing',
        'Voice-specific guardrails',
      ],
    },
    {
      id: 'testing-center-ga',
      title: 'New Testing Center',
      date: '2026-06-01',
      status: 'GA (June)',
      tileId: 'testing-center',
      icon: 'bug_report',
      accent: '#FFDB3C',
      summary: 'The new Testing Center makes E2E agent testing easier with inline editing, run history, and custom scorers.',
      highlights: [
        'Inline test editing (no CSV files)',
        'Run history with comparison',
        'Custom LLM Judge scorers',
        'Enhanced JSON debugging',
      ],
    },
    {
      id: 'multi-turn-testing-pilot',
      title: 'Multi-Turn Conversation Testing',
      date: '2026-04-01',
      status: 'Pilot',
      tileId: 'testing-center',
      icon: 'forum',
      accent: '#FFDB3C',
      summary: 'Pilot program for multi-turn conversation simulation with voice and text playback testing.',
      highlights: [
        'Generate realistic conversations',
        'Audio playback for voice testing',
        'Task resolution scorers',
      ],
    },
    {
      id: 'agent-health-monitoring',
      title: 'Agent Health Monitoring',
      date: '2026-05-01',
      status: 'GA (May)',
      tileId: 'observability',
      icon: 'monitor_heart',
      accent: '#00BFA5',
      summary: 'Near real-time monitoring and alerting on key operational health metrics with proactive issue resolution.',
      highlights: [
        'Real-time error tracking (5-min intervals)',
        'Customizable threshold alerts',
        'Latency and escalation monitoring',
        'Email notifications with cooldown',
      ],
    },
  ],
  roadmap: [
    {
      id: 'voice-multilingual-beta',
      title: 'Agentforce Voice Multi-Language Support',
      date: '2026-05-01',
      dateLabel: 'May/June Beta',
      tileId: 'agentforce-voice',
      icon: 'translate',
      accent: '#06A59A',
      summary: 'Expand voice support to Italian, Spanish (MX/ES), Japanese, Portuguese (BR/PT), and German.',
      highlights: [
        'Beta: 5 new languages (May/June)',
        'Early Q3: 10+ languages including ASEAN, Nordics, Chinese',
      ],
    },
    {
      id: 'voice-digital-channels',
      title: 'Agentforce Voice for Digital Channels',
      date: '2026-06-01',
      dateLabel: 'Q2 2026 GA',
      tileId: 'agentforce-voice',
      icon: 'chat_bubble',
      accent: '#06A59A',
      summary: 'Make every digital channel voice-first with conversational experiences and dual text/speech support.',
      highlights: [
        'Enhanced Chat with voice',
        'Mobile voice integration',
        'WhatsApp voice notes (Beta)',
      ],
    },
    {
      id: 'voice-enhanced-chat',
      title: 'Agentforce Voice for Enhanced Chat',
      date: '2026-05-01',
      dateLabel: 'May GA',
      tileId: 'agentforce-voice',
      icon: 'record_voice_over',
      accent: '#06A59A',
      summary: 'Guide decisions in the moment — help customers complete tasks without leaving the flow.',
      highlights: [
        'Voice and text in one conversation',
        'In-flow decision support',
        'Seamless mode switching',
      ],
    },
    {
      id: 'voice-mobile',
      title: 'Agentforce Voice in Mobile',
      date: '2026-05-01',
      dateLabel: 'May GA',
      tileId: 'agentforce-voice',
      icon: 'phone_android',
      accent: '#06A59A',
      summary: 'Voice natively embedded in mobile apps — tap and speak hands-free without dialing.',
      highlights: [
        'In-app voice (no phone dialing)',
        'Hands-free task completion',
        'Secure in-session authentication',
      ],
    },
    {
      id: 'voice-whatsapp',
      title: 'Agentforce Voice in WhatsApp',
      date: '2026-04-01',
      dateLabel: 'Beta Now',
      tileId: 'agentforce-voice',
      icon: 'chat',
      accent: '#06A59A',
      summary: 'Voice notes for low-effort messaging — switch to live voice without restarting the conversation.',
      highlights: [
        'Send voice notes instead of typing',
        'Escalate to live voice calls',
        'Continuous conversation thread',
      ],
    },
  ],
};

export const VOICE_LANGUAGE_ROADMAP = [
  {
    phase: 'In GA',
    dateLabel: 'Now',
    languages: ['English', 'French'],
    accent: '#45C65A',
  },
  {
    phase: 'Beta',
    dateLabel: 'May / June',
    languages: ['Italian', 'Spanish (MX/ES)', 'Japanese', 'Portuguese (BR/PT)', 'German'],
    accent: '#FFDB3C',
  },
  {
    phase: 'Beta',
    dateLabel: 'Early Q3',
    languages: ['10+ languages including ASEAN, Nordics, Chinese'],
    accent: '#FE9339',
  },
];
