export const JOURNEYS = {
  service: {
    messaging: {
      id: 'messaging-lifecycle',
      name: 'Messaging: First Contact to Resolution',
      description: 'End-to-end journey for chat and messaging interactions',
      phases: [
        { id: 'pre-contact', label: 'Before Contact', icon: 'schedule', color: '#0176D3' },
        { id: 'first-contact', label: 'First Contact', icon: 'chat', color: '#06A59A' },
        { id: 'agent-assist', label: 'Agent Handling', icon: 'support_agent', color: '#FFDB3C' },
        { id: 'resolution', label: 'Resolution', icon: 'check_circle', color: '#45C65A' },
        { id: 'post-resolution', label: 'After Resolution', icon: 'insights', color: '#7B5EA7' },
      ],
      mapping: {
        'pre-contact': [],
        'first-contact': ['einstein-bots', 'reply-recommendations'],
        'agent-assist': ['service-replies', 'article-recommendations', 'service-assistant', 'real-time-translations'],
        'resolution': ['work-summaries', 'conv-summaries', 'conv-catch-up'],
        'post-resolution': ['conversation-mining', 'knowledge-creation'],
      },
    },
    cases: {
      id: 'case-lifecycle',
      name: 'Cases: Intake to Resolution',
      description: 'Complete case management workflow from creation to closure',
      phases: [
        { id: 'intake', label: 'Case Intake', icon: 'inbox', color: '#0176D3' },
        { id: 'triage', label: 'Classification & Routing', icon: 'route', color: '#06A59A' },
        { id: 'investigation', label: 'Investigation', icon: 'search', color: '#FFDB3C' },
        { id: 'resolution', label: 'Resolution', icon: 'task_alt', color: '#45C65A' },
        { id: 'closure', label: 'Closure & Learning', icon: 'archive', color: '#7B5EA7' },
      ],
      mapping: {
        'intake': [],
        'triage': ['case-classification', 'case-routing'],
        'investigation': ['article-recommendations', 'service-replies', 'enhanced-summaries', 'service-assistant'],
        'resolution': ['work-summaries', 'search-answers'],
        'closure': ['case-wrap-up', 'knowledge-creation', 'conversation-mining'],
      },
    },
    voice: {
      id: 'voice-lifecycle',
      name: 'Voice: Call Start to Follow-up',
      description: 'Phone support journey from initial contact through post-call activities',
      phases: [
        { id: 'pre-call', label: 'Before Call', icon: 'phone_paused', color: '#0176D3' },
        { id: 'call-start', label: 'Call Starts', icon: 'phone_in_talk', color: '#06A59A' },
        { id: 'call-handling', label: 'Call Handling', icon: 'record_voice_over', color: '#FFDB3C' },
        { id: 'call-end', label: 'Call Wrap-up', icon: 'phone_disabled', color: '#45C65A' },
        { id: 'post-call', label: 'Post-Call', icon: 'analytics', color: '#7B5EA7' },
      ],
      mapping: {
        'pre-call': [],
        'call-start': ['agentforce-voice'],
        'call-handling': ['article-recommendations', 'conv-intelligence'],
        'call-end': ['work-summaries', 'conv-summaries', 'conv-catch-up'],
        'post-call': ['conversation-mining'],
      },
    },
    email: {
      id: 'email-lifecycle',
      name: 'Email: Inbox to Resolution',
      description: 'Email support workflow from receipt to case closure',
      phases: [
        { id: 'receipt', label: 'Email Receipt', icon: 'mail', color: '#0176D3' },
        { id: 'classification', label: 'Classification', icon: 'label', color: '#06A59A' },
        { id: 'drafting', label: 'Response Drafting', icon: 'edit', color: '#FFDB3C' },
        { id: 'sending', label: 'Send & Track', icon: 'send', color: '#45C65A' },
        { id: 'follow-up', label: 'Follow-up', icon: 'schedule_send', color: '#7B5EA7' },
      ],
      mapping: {
        'receipt': [],
        'classification': ['article-recommendations'],
        'drafting': ['service-replies', 'knowledge-creation', 'email-templates'],
        'sending': ['service-agent'],
        'follow-up': ['knowledge-creation'],
      },
    },
    field_service: {
      id: 'field-service-lifecycle',
      name: 'Field Service: Dispatch to Completion',
      description: 'Mobile technician workflow from job assignment to closure',
      phases: [
        { id: 'pre-dispatch', label: 'Pre-Dispatch', icon: 'schedule', color: '#0176D3' },
        { id: 'dispatch', label: 'Dispatch', icon: 'local_shipping', color: '#06A59A' },
        { id: 'on-site', label: 'On-Site Work', icon: 'engineering', color: '#FFDB3C' },
        { id: 'completion', label: 'Job Completion', icon: 'done_all', color: '#45C65A' },
        { id: 'follow-up', label: 'Follow-up', icon: 'replay', color: '#7B5EA7' },
      ],
      mapping: {
        'pre-dispatch': ['recommend-builder', 'scheduling-agent'],
        'dispatch': ['pre-work-brief'],
        'on-site': ['fs-agent', 'next-best-action'],
        'completion': ['work-summaries'],
        'follow-up': [],
      },
    },
    knowledge: {
      id: 'knowledge-lifecycle',
      name: 'Knowledge: Creation to Consumption',
      description: 'Knowledge article lifecycle from authoring to agent use',
      phases: [
        { id: 'creation', label: 'Creation', icon: 'add_circle', color: '#0176D3' },
        { id: 'editing', label: 'Editing & Review', icon: 'edit_note', color: '#06A59A' },
        { id: 'publishing', label: 'Publishing', icon: 'publish', color: '#FFDB3C' },
        { id: 'consumption', label: 'Agent Use', icon: 'menu_book', color: '#45C65A' },
        { id: 'optimization', label: 'Optimization', icon: 'tune', color: '#7B5EA7' },
      ],
      mapping: {
        'creation': ['knowledge-creation'],
        'editing': ['knowledge-edits'],
        'publishing': [],
        'consumption': ['article-recommendations', 'search-answers', 'service-agent', 'service-ai-grounding'],
        'optimization': [],
      },
    },
  },
  sales: {
    leads: {
      id: 'lead-lifecycle',
      name: 'Lead: Capture to Conversion',
      description: 'Lead management from initial capture through conversion',
      phases: [
        { id: 'capture', label: 'Capture', icon: 'person_add', color: '#0176D3' },
        { id: 'qualification', label: 'Qualification', icon: 'fact_check', color: '#06A59A' },
        { id: 'nurturing', label: 'Nurturing', icon: 'auto_mode', color: '#FFDB3C' },
        { id: 'conversion', label: 'Conversion', icon: 'stars', color: '#45C65A' },
      ],
      mapping: {
        'capture': ['agentforce-lead-generation'],
        'qualification': ['einstein-lead-scoring', 'agentforce-qualification', 'einstein-behavior-scoring'],
        'nurturing': ['agentforce-lead-nurturing'],
        'conversion': [],
      },
    },
    opportunities: {
      id: 'opportunity-lifecycle',
      name: 'Opportunity: Creation to Close',
      description: 'Deal progression from opportunity creation to won/lost',
      phases: [
        { id: 'creation', label: 'Creation', icon: 'add_business', color: '#0176D3' },
        { id: 'discovery', label: 'Discovery', icon: 'search', color: '#06A59A' },
        { id: 'proposal', label: 'Proposal', icon: 'description', color: '#FFDB3C' },
        { id: 'negotiation', label: 'Negotiation', icon: 'handshake', color: '#E31754' },
        { id: 'close', label: 'Close', icon: 'celebration', color: '#45C65A' },
      ],
      mapping: {
        'creation': ['einstein-opportunity-scoring'],
        'discovery': ['einstein-coach', 'einstein-conversation-insights', 'agentforce-sales-coach'],
        'proposal': ['agentforce-pipeline-management'],
        'negotiation': ['agentforce-sales-management'],
        'close': [],
      },
    },
    accounts: {
      id: 'account-lifecycle',
      name: 'Account: Acquisition to Expansion',
      description: 'Account management from initial sale through expansion',
      phases: [
        { id: 'prospecting', label: 'Prospecting', icon: 'search', color: '#0176D3' },
        { id: 'acquisition', label: 'Acquisition', icon: 'store', color: '#06A59A' },
        { id: 'onboarding', label: 'Onboarding', icon: 'login', color: '#FFDB3C' },
        { id: 'growth', label: 'Growth', icon: 'trending_up', color: '#45C65A' },
        { id: 'renewal', label: 'Renewal', icon: 'autorenew', color: '#7B5EA7' },
      ],
      mapping: {
        'prospecting': ['agentforce-prospecting', 'einstein-recommended-connections'],
        'acquisition': [],
        'onboarding': [],
        'growth': ['agentforce-account-management'],
        'renewal': ['agentforce-account-management'],
      },
    },
    activities: {
      id: 'activity-lifecycle',
      name: 'Activities: Planning to Execution',
      description: 'Sales activity workflow from planning to follow-up',
      phases: [
        { id: 'planning', label: 'Planning', icon: 'event', color: '#0176D3' },
        { id: 'execution', label: 'Execution', icon: 'play_arrow', color: '#06A59A' },
        { id: 'logging', label: 'Logging', icon: 'edit', color: '#FFDB3C' },
        { id: 'insights', label: 'Insights', icon: 'insights', color: '#7B5EA7' },
      ],
      mapping: {
        'planning': ['einstein-coach'],
        'execution': ['einstein-conversation-insights'],
        'logging': ['einstein-activity-capture'],
        'insights': ['einstein-email-insights'],
      },
    },
  },
};
