export const MATURITY_MODEL = {
  service: {
    messaging: {
      id: 'messaging-maturity',
      name: 'Messaging Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Messaging channels configured', 'Omni-Channel routing enabled'],
          capabilities: ['einstein-bots', 'reply-recommendations'],
          outcomes: ['20% deflection rate', 'Basic automation', 'Faster response time'],
          timeToValue: '4-6 weeks',
          description: 'Start with bot deflection and basic agent assistance',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Knowledge Base with 3+ articles', 'Historical chat transcripts'],
          capabilities: ['service-replies', 'article-recommendations', 'work-summaries', 'conv-summaries', 'real-time-translations'],
          outcomes: ['40% faster replies', '15% CSAT improvement', 'Reduced average handle time'],
          timeToValue: '8-12 weeks',
          description: 'Add GenAI assistance to improve agent productivity',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', '1000+ closed transcripts', 'Conversation data'],
          capabilities: ['conversation-mining', 'conv-catch-up', 'knowledge-creation'],
          outcomes: ['Data-driven bot strategy', 'Process optimization', 'Continuous improvement'],
          timeToValue: '12-16 weeks',
          description: 'Leverage analytics to optimize support operations',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license', 'Mature knowledge base'],
          capabilities: ['service-agent', 'service-assistant', 'proactive-service'],
          outcomes: ['End-to-end automation', 'Scale without hiring', '60%+ deflection rate'],
          timeToValue: '16-24 weeks',
          description: 'Deploy fully autonomous AI agents',
        },
      ],
    },
    cases: {
      id: 'cases-maturity',
      name: 'Case Management Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['400+ closed cases from past 6 months'],
          capabilities: ['case-classification', 'case-routing'],
          outcomes: ['Faster case triaging', 'Improved data quality', 'Reduced manual entry'],
          timeToValue: '4-6 weeks',
          description: 'Automate case classification and routing',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Knowledge articles published'],
          capabilities: ['article-recommendations', 'service-replies', 'enhanced-summaries', 'work-summaries'],
          outcomes: ['40% faster resolution', 'Better agent enablement', 'Consistent responses'],
          timeToValue: '8-12 weeks',
          description: 'Assist agents with AI-powered recommendations',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Case history data'],
          capabilities: ['conversation-mining', 'case-wrap-up', 'search-answers', 'knowledge-creation'],
          outcomes: ['Streamlined closing', 'Better trend reporting', 'Knowledge gap closure'],
          timeToValue: '12-16 weeks',
          description: 'Extract insights and optimize processes',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['service-assistant', 'service-agent'],
          outcomes: ['Real-time agent guidance', 'Automated case handling', 'Expert-level support'],
          timeToValue: '16-24 weeks',
          description: 'Enable autonomous case management',
        },
      ],
    },
    voice: {
      id: 'voice-maturity',
      name: 'Voice Support Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Service Cloud Voice deployed', 'Call recording enabled'],
          capabilities: ['conv-intelligence', 'article-recommendations'],
          outcomes: ['Call quality insights', 'Agent coaching', 'Knowledge access during calls'],
          timeToValue: '8-12 weeks',
          description: 'Set up voice infrastructure and basic analytics',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Call transcripts available'],
          capabilities: ['conv-summaries', 'conv-catch-up', 'work-summaries'],
          outcomes: ['Reduced after-call work', 'Better call transfers', 'Improved documentation'],
          timeToValue: '12-16 weeks',
          description: 'Add AI-powered call summaries and assistance',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Historical call data'],
          capabilities: ['conversation-mining'],
          outcomes: ['Trend identification', 'Quality assurance automation', 'Process improvement'],
          timeToValue: '16-20 weeks',
          description: 'Analyze call patterns for optimization',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['agentforce-voice'],
          outcomes: ['Automated voice support', 'Natural IVR', 'Scale phone operations'],
          timeToValue: '20-28 weeks',
          description: 'Deploy autonomous voice agents',
        },
      ],
    },
    email: {
      id: 'email-maturity',
      name: 'Email Support Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Email-to-Case enabled', 'Email routing configured'],
          capabilities: ['article-recommendations'],
          outcomes: ['Knowledge access', 'Faster triage', 'Improved responses'],
          timeToValue: '4-6 weeks',
          description: 'Set up basic email routing and knowledge recommendations',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Knowledge Base with articles'],
          capabilities: ['service-replies', 'email-templates', 'knowledge-creation'],
          outcomes: ['Faster email drafting', 'Consistent responses', 'Template library growth'],
          timeToValue: '8-12 weeks',
          description: 'Add AI-powered email drafting and templates',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Historical email data'],
          capabilities: [],
          outcomes: ['Email analytics', 'Response time optimization'],
          timeToValue: '12-16 weeks',
          description: 'Analyze email patterns for optimization',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['service-agent'],
          outcomes: ['Automated email responses', 'End-to-end email automation'],
          timeToValue: '16-24 weeks',
          description: 'Deploy autonomous email agents',
        },
      ],
    },
    field_service: {
      id: 'field-service-maturity',
      name: 'Field Service Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Field Service Lightning deployed', 'Work order data'],
          capabilities: ['next-best-action', 'recommend-builder'],
          outcomes: ['Upsell opportunities', 'Skill prediction', 'Resource optimization'],
          timeToValue: '6-8 weeks',
          description: 'Implement predictive recommendations',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Asset and service history'],
          capabilities: ['pre-work-brief', 'work-summaries'],
          outcomes: ['Better prepared technicians', 'Faster job completion', 'Improved documentation'],
          timeToValue: '10-14 weeks',
          description: 'Add AI-powered technician assistance',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Field service analytics'],
          capabilities: [],
          outcomes: ['Performance analytics', 'First-time fix rate improvement'],
          timeToValue: '14-18 weeks',
          description: 'Analyze field operations for optimization',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['fs-agent', 'scheduling-agent'],
          outcomes: ['Autonomous scheduling', 'Self-service technician support'],
          timeToValue: '18-26 weeks',
          description: 'Deploy autonomous field service agents',
        },
      ],
    },
    knowledge: {
      id: 'knowledge-maturity',
      name: 'Knowledge Management Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Salesforce Knowledge enabled', '10+ articles published'],
          capabilities: ['article-recommendations'],
          outcomes: ['Agent knowledge access', 'Article discovery', 'Faster resolution'],
          timeToValue: '2-4 weeks',
          description: 'Enable basic article recommendations',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Article usage data'],
          capabilities: ['knowledge-creation', 'knowledge-edits', 'search-answers', 'service-ai-grounding'],
          outcomes: ['Automated article creation', 'Better article quality', 'Trusted AI responses'],
          timeToValue: '8-12 weeks',
          description: 'Add AI-powered content creation and editing',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Knowledge analytics'],
          capabilities: [],
          outcomes: ['Content gap analysis', 'Article performance insights'],
          timeToValue: '12-16 weeks',
          description: 'Optimize knowledge base with analytics',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['service-agent'],
          outcomes: ['Self-service knowledge bot', 'Automated content curation'],
          timeToValue: '16-24 weeks',
          description: 'Deploy autonomous knowledge agents',
        },
      ],
    },
  },
  sales: {
    leads: {
      id: 'leads-maturity',
      name: 'Lead Management Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Historical lead conversion data'],
          capabilities: ['einstein-lead-scoring', 'einstein-behavior-scoring'],
          outcomes: ['Lead prioritization', 'Improved conversion rates', 'Sales focus'],
          timeToValue: '4-6 weeks',
          description: 'Implement predictive lead scoring',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Marketing automation connected'],
          capabilities: ['agentforce-qualification'],
          outcomes: ['Automated qualification', 'Faster lead routing', 'Better SDR productivity'],
          timeToValue: '8-12 weeks',
          description: 'Add AI-powered lead qualification',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Lead engagement data'],
          capabilities: ['agentforce-lead-nurturing'],
          outcomes: ['Personalized nurture', 'Engagement tracking', 'Conversion acceleration'],
          timeToValue: '12-16 weeks',
          description: 'Implement intelligent nurturing',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['agentforce-lead-generation', 'agentforce-prospecting'],
          outcomes: ['Autonomous prospecting', 'Scale lead generation', 'Meeting automation'],
          timeToValue: '16-24 weeks',
          description: 'Deploy autonomous lead generation',
        },
      ],
    },
    opportunities: {
      id: 'opportunities-maturity',
      name: 'Opportunity Management Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Historical win/loss data', 'Opportunity stages defined'],
          capabilities: ['einstein-opportunity-scoring', 'einstein-forecasting'],
          outcomes: ['Win probability insights', 'Better forecasting', 'Deal prioritization'],
          timeToValue: '6-8 weeks',
          description: 'Implement predictive opportunity scoring',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Sales call data'],
          capabilities: ['einstein-coach', 'einstein-conversation-insights'],
          outcomes: ['Real-time coaching', 'Call insights', 'Best practice adoption'],
          timeToValue: '10-14 weeks',
          description: 'Add coaching and conversation intelligence',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Pipeline data'],
          capabilities: ['agentforce-pipeline-management'],
          outcomes: ['Pipeline hygiene', 'Deal progression', 'Forecast accuracy'],
          timeToValue: '14-18 weeks',
          description: 'Optimize pipeline management with AI',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['agentforce-sales-management', 'agentforce-sales-coach'],
          outcomes: ['Automated deal management', 'AI coaching', 'Strategic guidance'],
          timeToValue: '18-26 weeks',
          description: 'Deploy autonomous sales management',
        },
      ],
    },
    accounts: {
      id: 'accounts-maturity',
      name: 'Account Management Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Contact data', 'Email integration'],
          capabilities: ['einstein-recommended-connections', 'einstein-activity-capture'],
          outcomes: ['Warm introductions', 'Better data hygiene', 'Relationship mapping'],
          timeToValue: '4-6 weeks',
          description: 'Build foundational account intelligence',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Email tracking enabled'],
          capabilities: ['einstein-email-insights'],
          outcomes: ['Engagement tracking', 'Follow-up timing', 'Email effectiveness'],
          timeToValue: '8-10 weeks',
          description: 'Enhance communication tracking',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Account health data'],
          capabilities: ['agentforce-prospecting'],
          outcomes: ['Account research', 'Buying signal detection', 'Targeted outreach'],
          timeToValue: '12-16 weeks',
          description: 'Implement account intelligence',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license', 'Customer 360 data'],
          capabilities: ['agentforce-account-management'],
          outcomes: ['Proactive expansion', 'Renewal automation', 'Customer lifetime value growth'],
          timeToValue: '16-24 weeks',
          description: 'Enable autonomous account management',
        },
      ],
    },
    activities: {
      id: 'activities-maturity',
      name: 'Sales Activities Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Email integration', 'Calendar sync'],
          capabilities: ['einstein-activity-capture', 'einstein-email-insights'],
          outcomes: ['Automated data entry', 'Engagement tracking', 'Better CRM hygiene'],
          timeToValue: '4-6 weeks',
          description: 'Automate activity tracking',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Call recording enabled'],
          capabilities: ['einstein-coach', 'einstein-conversation-insights'],
          outcomes: ['Real-time coaching', 'Call insights', 'Best practice adoption'],
          timeToValue: '8-12 weeks',
          description: 'Add coaching and conversation intelligence',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Activity history data'],
          capabilities: [],
          outcomes: ['Activity analytics', 'Performance insights', 'Rep benchmarking'],
          timeToValue: '12-16 weeks',
          description: 'Analyze activity patterns',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['agentforce-sales-coach', 'agentforce-prospecting'],
          outcomes: ['AI coaching', 'Automated prospecting', 'Meeting generation'],
          timeToValue: '16-24 weeks',
          description: 'Deploy autonomous sales assistance',
        },
      ],
    },
    campaigns: {
      id: 'campaigns-maturity',
      name: 'Campaign Management Maturity Roadmap',
      levels: [
        {
          id: 'foundation',
          name: 'Foundation',
          order: 1,
          color: '#0176D3',
          icon: 'foundation',
          prerequisites: ['Campaign tracking enabled', 'Historical campaign data'],
          capabilities: ['einstein-behavior-scoring', 'einstein-send-time-optimization'],
          outcomes: ['Engagement scoring', 'Optimized send times', 'Better targeting'],
          timeToValue: '6-8 weeks',
          description: 'Implement predictive campaign optimization',
        },
        {
          id: 'augmentation',
          name: 'Augmentation',
          order: 2,
          color: '#FFDB3C',
          icon: 'auto_awesome',
          prerequisites: ['Level 1 complete', 'Multi-channel campaigns'],
          capabilities: ['einstein-campaign-insights'],
          outcomes: ['Campaign performance insights', 'Channel effectiveness', 'Budget optimization'],
          timeToValue: '10-14 weeks',
          description: 'Add campaign analytics and insights',
        },
        {
          id: 'insights',
          name: 'Insights',
          order: 3,
          color: '#7B5EA7',
          icon: 'insights',
          prerequisites: ['Level 2 complete', 'Revenue attribution data'],
          capabilities: ['einstein-attribution'],
          outcomes: ['Multi-touch attribution', 'Marketing ROI', 'Data-driven budget allocation'],
          timeToValue: '14-18 weeks',
          description: 'Implement attribution modeling',
        },
        {
          id: 'autonomous',
          name: 'Autonomous',
          order: 4,
          color: '#E31754',
          icon: 'memory',
          prerequisites: ['Level 3 complete', 'Agentforce license'],
          capabilities: ['agentforce-lead-nurturing'],
          outcomes: ['Automated nurture campaigns', 'Personalized journeys', 'Scale marketing'],
          timeToValue: '18-26 weeks',
          description: 'Deploy autonomous campaign management',
        },
      ],
    },
  },
};
