export const CAPABILITIES = [
  // PREDICTIVE ERA
  {
    id: 'einstein-lead-scoring',
    symbol: 'Ls',
    name: 'Lead Scoring',
    fullName: 'Einstein Lead Scoring',
    era: 'predictive',
    channels: ['leads'],
    description: 'Automatically score and prioritize leads based on likelihood to convert.',
    storyline: [
      'Einstein analyzes historical conversion patterns across your CRM data',
      'Machine learning models score each lead based on firmographic and behavioral signals',
      'Sales reps see prioritized lead lists with confidence scores',
      'Focus efforts on high-value opportunities with data-driven insights',
    ],
    useCases: ['Lead prioritization', 'Sales productivity', 'Conversion rate optimization'],
    specs: {
      model: 'AutoML',
      target: 'Lead Conversion',
      availability: 'GA',
    },
    icon: 'trending_up',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.einstein_sales_lead_scoring.htm',
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/einstein-lead-scoring',
    },
    jobsToBeDone: ['reduce-time', 'increase-revenue', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'einstein-opportunity-scoring',
    symbol: 'Os',
    name: 'Opportunity Scoring',
    fullName: 'Einstein Opportunity Scoring',
    era: 'predictive',
    channels: ['opportunities'],
    description: 'Predict win probability for opportunities and identify at-risk deals.',
    storyline: [
      'Einstein examines won and lost opportunity patterns',
      'Predictive models calculate win likelihood based on stage, activity, and account factors',
      'Reps receive actionable insights on which deals need attention',
      'Pipeline health improves through data-driven deal management',
    ],
    useCases: ['Pipeline management', 'Win rate improvement', 'Deal risk identification'],
    specs: {
      model: 'Gradient Boosted Trees',
      target: 'Opportunity Win Probability',
      availability: 'GA',
    },
    icon: 'query_stats',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.einstein_sales_opportunity_scoring.htm',
    },
    jobsToBeDone: ['increase-revenue', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'einstein-forecasting',
    symbol: 'Ef',
    name: 'Forecasting',
    fullName: 'Einstein Forecasting',
    era: 'predictive',
    channels: ['forecasting'],
    description: 'AI-powered revenue forecasting with predictive analytics.',
    storyline: [
      'Einstein analyzes pipeline trends, historical win rates, and rep performance',
      'Predictive models generate accurate revenue forecasts',
      'Sales leaders receive category-level predictions and confidence intervals',
      'Adjust strategies based on forecast insights and trend analysis',
    ],
    useCases: ['Revenue planning', 'Quota management', 'Resource allocation'],
    specs: {
      model: 'Time Series Analysis',
      target: 'Revenue Prediction',
      availability: 'GA',
    },
    icon: 'assessment',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.sales_core_forecasts.htm',
    },
    jobsToBeDone: ['empower-agents', 'increase-revenue'],
    maturityLevel: 'foundation',
  },
  {
    id: 'einstein-coach',
    symbol: 'Ec',
    name: 'Coach',
    fullName: 'Einstein Coach',
    era: 'predictive',
    channels: ['opportunities', 'activities'],
    description: 'Real-time coaching recommendations to help reps close deals faster.',
    storyline: [
      'Einstein monitors deal progress and rep activities',
      'Coaching insights surface based on best practices from top performers',
      'Reps receive timely recommendations on next best actions',
      'Improve sales effectiveness through continuous AI-driven guidance',
    ],
    useCases: ['Sales enablement', 'Rep productivity', 'Best practice adoption'],
    specs: {
      model: 'Pattern Recognition',
      target: 'Sales Actions',
      availability: 'GA',
    },
    icon: 'school',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.einstein_sales_coach.htm',
    },
    jobsToBeDone: ['empower-agents', 'increase-revenue'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'einstein-conversation-insights',
    symbol: 'Ci',
    name: 'Conversation Insights',
    fullName: 'Einstein Conversation Insights',
    era: 'predictive',
    channels: ['activities'],
    description: 'Analyze sales calls to extract key moments, objections, and action items.',
    storyline: [
      'Einstein transcribes and analyzes recorded sales conversations',
      'Key moments like pricing discussions and objections are automatically tagged',
      'Reps review highlights and coaching recommendations post-call',
      'Managers gain visibility into talk patterns and deal risks',
    ],
    useCases: ['Call coaching', 'Objection handling', 'Deal insight extraction'],
    specs: {
      model: 'NLP + Speech Recognition',
      target: 'Call Transcription',
      availability: 'GA',
    },
    icon: 'record_voice_over',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.sales_conversation_insights.htm',
    },
    jobsToBeDone: ['empower-agents', 'improve-data'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'einstein-activity-capture',
    symbol: 'Ac',
    name: 'Activity Capture',
    fullName: 'Einstein Activity Capture',
    era: 'predictive',
    channels: ['activities', 'contacts'],
    description: 'Automatically sync emails and calendar events from Outlook or Gmail to Salesforce.',
    storyline: [
      'Einstein connects to your email and calendar systems',
      'Relevant emails and meetings are automatically captured in Salesforce',
      'Contact relationships are updated based on email engagement',
      'Reps spend less time on data entry and more time selling',
    ],
    useCases: ['Data hygiene', 'Activity tracking', 'Contact relationship mapping'],
    specs: {
      model: 'Pattern Matching',
      target: 'Email/Calendar Sync',
      availability: 'GA',
    },
    icon: 'sync',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.einstein_sales_activity_capture.htm',
    },
    jobsToBeDone: ['automate', 'improve-data'],
    maturityLevel: 'foundation',
  },
  {
    id: 'einstein-email-insights',
    symbol: 'Ei',
    name: 'Email Insights',
    fullName: 'Einstein Email Insights',
    era: 'predictive',
    channels: ['activities'],
    description: 'Track email opens, clicks, and engagement to optimize outreach.',
    storyline: [
      'Einstein monitors email engagement metrics for sent messages',
      'Reps receive notifications when prospects open emails or click links',
      'Engagement data helps prioritize follow-up actions',
      'Optimize email timing and messaging based on engagement patterns',
    ],
    useCases: ['Email effectiveness', 'Prospect engagement', 'Follow-up timing'],
    specs: {
      model: 'Event Tracking',
      target: 'Email Engagement',
      availability: 'GA',
    },
    icon: 'mark_email_read',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.einstein_sales_email_insights.htm',
    },
    jobsToBeDone: ['empower-agents', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'einstein-recommended-connections',
    symbol: 'Rc',
    name: 'Recommended Connections',
    fullName: 'Einstein Recommended Connections',
    era: 'predictive',
    channels: ['contacts', 'accounts'],
    description: 'Discover warm introduction paths through your network.',
    storyline: [
      'Einstein maps relationships between your team and target accounts',
      'Recommends colleagues who have existing connections to prospects',
      'Reps request introductions through Salesforce',
      'Increase conversion rates through warm outreach',
    ],
    useCases: ['Warm introductions', 'Relationship mapping', 'Account-based selling'],
    specs: {
      model: 'Graph Analysis',
      target: 'Contact Networks',
      availability: 'GA',
    },
    icon: 'share',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.einstein_sales_recommended_connections.htm',
    },
    jobsToBeDone: ['increase-revenue', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'einstein-campaign-insights',
    symbol: 'Cm',
    name: 'Campaign Insights',
    fullName: 'Einstein Campaign Insights',
    era: 'predictive',
    channels: ['campaigns'],
    description: 'Measure campaign effectiveness and optimize marketing spend.',
    storyline: [
      'Einstein analyzes campaign performance across channels',
      'Attribution models connect marketing touches to revenue outcomes',
      'Marketing teams see which campaigns drive the most pipeline',
      'Optimize budget allocation based on campaign ROI insights',
    ],
    useCases: ['Campaign optimization', 'Marketing attribution', 'Budget planning'],
    specs: {
      model: 'Multi-Touch Attribution',
      target: 'Campaign ROI',
      availability: 'GA',
    },
    icon: 'campaign',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.campaigns_einstein_insights.htm',
    },
    jobsToBeDone: ['increase-revenue', 'reduce-cost'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'einstein-behavior-scoring',
    symbol: 'Bs',
    name: 'Behavior Scoring',
    fullName: 'Einstein Behavior Scoring',
    era: 'predictive',
    channels: ['leads', 'campaigns'],
    description: 'Score leads based on website, email, and content engagement behavior.',
    storyline: [
      'Einstein tracks prospect interactions across digital touchpoints',
      'Behavioral signals are weighted based on conversion patterns',
      'Marketing and sales teams see engagement scores in real time',
      'Prioritize leads showing strong buying intent',
    ],
    useCases: ['Lead prioritization', 'Marketing qualification', 'Engagement tracking'],
    specs: {
      model: 'Behavioral Analytics',
      target: 'Engagement Score',
      availability: 'GA',
    },
    icon: 'insights',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.pardot_einstein_behavior_scoring.htm',
    },
    jobsToBeDone: ['increase-revenue', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'einstein-attribution',
    symbol: 'At',
    name: 'Attribution',
    fullName: 'Einstein Attribution',
    era: 'predictive',
    channels: ['campaigns'],
    description: 'Multi-touch attribution to understand marketing impact on revenue.',
    storyline: [
      'Einstein tracks all marketing touchpoints in the buyer journey',
      'Attribution models assign credit to campaigns based on their influence',
      'Marketing leaders see which channels drive the most ROI',
      'Data-driven insights guide budget allocation and campaign strategy',
    ],
    useCases: ['Marketing ROI', 'Budget optimization', 'Channel effectiveness'],
    specs: {
      model: 'Multi-Touch Attribution',
      target: 'Campaign Credit',
      availability: 'GA',
    },
    icon: 'account_tree',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.einstein_sales_attribution.htm',
    },
    jobsToBeDone: ['increase-revenue', 'reduce-cost'],
    maturityLevel: 'insights',
  },
  {
    id: 'einstein-send-time-optimization',
    symbol: 'St',
    name: 'Send Time Optimization',
    fullName: 'Einstein Send Time Optimization',
    era: 'predictive',
    channels: ['campaigns'],
    description: 'Determine optimal send times for email campaigns to maximize engagement.',
    storyline: [
      'Einstein analyzes when each recipient is most likely to engage with emails',
      'Predictive models calculate personalized optimal send times',
      'Campaigns automatically schedule sends based on individual preferences',
      'Increase open rates and engagement through timing optimization',
    ],
    useCases: ['Email optimization', 'Engagement improvement', 'Campaign effectiveness'],
    specs: {
      model: 'Time Series Prediction',
      target: 'Send Time',
      availability: 'GA',
    },
    icon: 'schedule_send',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.pardot_einstein_send_time_optimization.htm',
    },
    jobsToBeDone: ['increase-revenue', 'automate'],
    maturityLevel: 'augmentation',
  },

  // AGENTIC ERA
  {
    id: 'agentforce-lead-generation',
    symbol: 'Lg',
    name: 'Lead Generation',
    fullName: 'Agentforce Lead Generation',
    era: 'agentic',
    channels: ['leads'],
    description: 'Autonomous agents that research, identify, and qualify new leads at scale.',
    storyline: [
      'Agentforce agents research target accounts and identify decision makers',
      'AI agents qualify leads through automated outreach and conversation',
      'High-quality leads are routed to sales reps with context and insights',
      'Scale lead generation efforts without adding headcount',
    ],
    useCases: ['Lead discovery', 'Prospecting automation', 'Pipeline generation'],
    specs: {
      model: 'LLM + Reasoning',
      target: 'Lead Identification',
      availability: 'Beta',
    },
    icon: 'person_search',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['scale-ops', 'increase-revenue', 'automate'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'agentforce-qualification',
    symbol: 'Qf',
    name: 'Qualification',
    fullName: 'Agentforce Qualification',
    era: 'agentic',
    channels: ['leads'],
    description: 'AI agents that autonomously qualify inbound leads through intelligent conversations.',
    storyline: [
      'Agentforce agents engage with inbound leads via chat, email, or forms',
      'AI conducts discovery conversations to assess fit and buying intent',
      'Qualified leads are scored and routed to appropriate sales teams',
      'Unqualified leads are nurtured automatically until they meet criteria',
    ],
    useCases: ['Lead qualification', 'Inbound routing', 'Sales efficiency'],
    specs: {
      model: 'LLM + Grounding',
      target: 'Lead Qualification',
      availability: 'Beta',
    },
    icon: 'fact_check',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['scale-ops', 'automate', 'increase-revenue'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'agentforce-lead-nurturing',
    symbol: 'Ln',
    name: 'Lead Nurturing',
    fullName: 'Agentforce Lead Nurturing',
    era: 'agentic',
    channels: ['leads', 'campaigns'],
    description: 'Autonomous nurture campaigns that adapt based on prospect behavior and engagement.',
    storyline: [
      'Agentforce agents monitor lead engagement and behavior signals',
      'AI personalizes nurture content and cadence for each prospect',
      'Agents detect buying signals and escalate hot leads to sales',
      'Maintain engagement until prospects are ready to buy',
    ],
    useCases: ['Marketing automation', 'Lead warming', 'Conversion acceleration'],
    specs: {
      model: 'LLM + RAG',
      target: 'Nurture Personalization',
      availability: 'Pilot',
    },
    icon: 'auto_mode',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['scale-ops', 'increase-revenue'],
    maturityLevel: 'insights',
  },
  {
    id: 'agentforce-sales-management',
    symbol: 'Sm',
    name: 'Sales Management',
    fullName: 'Agentforce Sales Management',
    era: 'agentic',
    channels: ['opportunities', 'accounts'],
    description: 'AI-powered sales manager that provides strategic guidance and automates deal management.',
    storyline: [
      'Agentforce agents analyze pipeline health and identify at-risk deals',
      'AI provides strategic recommendations for deal acceleration',
      'Agents automate routine tasks like data updates and follow-ups',
      'Sales managers focus on coaching while agents handle operational work',
    ],
    useCases: ['Pipeline management', 'Deal coaching', 'Forecast accuracy'],
    specs: {
      model: 'LLM + Reasoning',
      target: 'Sales Strategy',
      availability: 'Pilot',
    },
    icon: 'manage_accounts',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['empower-agents', 'increase-revenue'],
    maturityLevel: 'insights',
  },
  {
    id: 'agentforce-pipeline-management',
    symbol: 'Pm',
    name: 'Pipeline Management',
    fullName: 'Agentforce Pipeline Management',
    era: 'agentic',
    channels: ['opportunities'],
    description: 'Autonomous pipeline hygiene and deal progression recommendations.',
    storyline: [
      'Agentforce agents continuously monitor pipeline health metrics',
      'AI identifies stalled deals and suggests next best actions',
      'Agents automatically update deal stages and close dates based on activity',
      'Keep pipeline accurate and actionable with minimal manual effort',
    ],
    useCases: ['Pipeline hygiene', 'Deal progression', 'Forecast reliability'],
    specs: {
      model: 'LLM + CRM Integration',
      target: 'Pipeline Health',
      availability: 'Beta',
    },
    icon: 'account_balance_wallet',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['automate', 'improve-data', 'increase-revenue'],
    maturityLevel: 'insights',
  },
  {
    id: 'agentforce-account-management',
    symbol: 'Am',
    name: 'Account Management',
    fullName: 'Agentforce Account Management',
    era: 'agentic',
    channels: ['accounts', 'opportunities'],
    description: 'AI agents that proactively identify expansion and renewal opportunities.',
    storyline: [
      'Agentforce agents monitor account health and usage signals',
      'AI identifies upsell, cross-sell, and renewal opportunities',
      'Agents draft personalized outreach and schedule touchpoints',
      'Maximize customer lifetime value through proactive account management',
    ],
    useCases: ['Customer expansion', 'Renewal management', 'Account growth'],
    specs: {
      model: 'LLM + Customer 360',
      target: 'Account Strategy',
      availability: 'Pilot',
    },
    icon: 'corporate_fare',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['increase-revenue', 'empower-agents'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'agentforce-sales-coach',
    symbol: 'Sc',
    name: 'Sales Coach',
    fullName: 'Agentforce Sales Coach',
    era: 'agentic',
    channels: ['opportunities', 'activities'],
    description: 'AI coaching agent that provides personalized guidance and skill development.',
    storyline: [
      'Agentforce agents analyze rep performance and identify skill gaps',
      'AI provides real-time coaching during deal execution',
      'Agents recommend training content and role-play scenarios',
      'Accelerate rep ramp time and improve win rates through continuous coaching',
    ],
    useCases: ['Rep enablement', 'Skill development', 'Performance improvement'],
    specs: {
      model: 'LLM + Performance Analytics',
      target: 'Sales Coaching',
      availability: 'Pilot',
    },
    icon: 'support_agent',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['empower-agents', 'increase-revenue'],
    maturityLevel: 'insights',
  },
  {
    id: 'agentforce-prospecting',
    symbol: 'Ps',
    name: 'Prospecting',
    fullName: 'Agentforce Prospecting',
    era: 'agentic',
    channels: ['leads', 'accounts'],
    description: 'Autonomous prospecting agents that research accounts and book meetings.',
    storyline: [
      'Agentforce agents research target accounts and identify buying signals',
      'AI crafts personalized outreach across email, LinkedIn, and phone',
      'Agents handle objections and qualify interest through multi-touch sequences',
      'Book qualified meetings directly on rep calendars',
    ],
    useCases: ['Outbound sales', 'Meeting generation', 'Account research'],
    specs: {
      model: 'LLM + Multi-Channel',
      target: 'Meeting Booking',
      availability: 'Beta',
    },
    icon: 'search',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=sf.agentforce_sales.htm',
    },
    jobsToBeDone: ['scale-ops', 'increase-revenue', 'automate'],
    maturityLevel: 'autonomous',
  },
];
