export const CAPABILITIES = [
  {
    id: 'case-classification',
    symbol: 'Ec',
    name: 'Case Classification',
    fullName: 'Einstein Case Classification',
    era: 'predictive',
    channels: ['cases'],
    description: 'Predicts picklist and checkbox field values on new cases based on past cases to reduce manual entry.',
    storyline: ['Case arrives', 'Einstein analyzes subject/description', 'Fields are predicted automatically'],
    useCases: ['Faster case triaging', 'Improved data quality'],
    specs: { model: 'AutoML', target: 'Case Fields', apiVersion: 'API 49.0+', confidenceThreshold: 'Configurable' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/service_case_class',
      docs: 'https://help.salesforce.com/s/articleView?id=service.cc_service_what_is.htm&type=5',
      considerations: 'https://help.salesforce.com/s/articleView?id=service.cc_service_considerations.htm&type=5',
      fieldDocs: 'https://help.salesforce.com/s/articleView?id=service.cc_service_field_considerations.htm&type=5',
      video: 'https://salesforce.vidyard.com/watch/SVYoP4cGZbsbeAhcLjGRiF',
    },
    setupRequirements: 'Minimum 400 closed cases from past 6 months (10,000+ ideal for accuracy); Service Cloud Einstein add-on (or Try Einstein for 1 model); supports picklist and checkbox fields; API Version 49.0+; Try Einstein only supports recommendations (not routing)',
    jobsToBeDone: ['improve-data', 'reduce-time', 'automate'],
    maturityLevel: 'foundation',
  },
  {
    id: 'case-routing',
    symbol: 'Er',
    name: 'Case Routing',
    fullName: 'Einstein Case Routing',
    era: 'predictive',
    channels: ['cases'],
    description: 'Uses predicted field values to ensure cases reach the right agent or queue immediately.',
    storyline: ['Einstein predicts case category', 'Omni-Channel uses prediction to find expert', 'Case is pushed to agent'],
    useCases: ['Reducing transfers', 'Faster first response'],
    specs: { logic: 'Omni-Channel', trigger: 'Classification', integration: 'Omni-Channel Supervisor' },
    icon: 'analytics',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.omnichannel_einstein_case_routing.htm&type=5',
      rulesDocs: 'https://help.salesforce.com/s/articleView?id=service.cc_service_rules.htm&type=5',
      video: 'https://salesforce.vidyard.com/watch/SVYoP4cGZbsbeAhcLjGRiF',
    },
    setupRequirements: 'Service Cloud Einstein add-on required (NOT available in Try Einstein); Case Classification must be active with "Automate Value" enabled; Omni-Channel integration required',
    jobsToBeDone: ['reduce-time', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'case-wrap-up',
    symbol: 'Ew',
    name: 'Case Wrap-Up',
    fullName: 'Einstein Case Wrap-Up',
    era: 'predictive',
    channels: ['cases'],
    description: 'Suggests values for fields like "Resolution" or "Root Cause" when an agent is closing a case.',
    storyline: ['Agent begins closing case', 'Einstein suggests wrap-up values', 'Agent confirms and saves'],
    useCases: ['Streamlined closing', 'Better trend reporting'],
    specs: { trigger: 'Status: Closed', feedback: 'Real-time', fields: 'Subject + Description only' },
    icon: 'analytics',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.cc_service_what_is.htm&type=5',
      video: null
    },
    setupRequirements: 'Minimum 400 closed cases from past 6 months with subject/description; accuracy improves with 1,000+ and chat transcripts included; ONLY works with LiveChat (not customizable like Classification); only uses Subject and Description fields',
    jobsToBeDone: ['improve-data', 'reduce-time'],
    maturityLevel: 'insights',
  },
  {
    id: 'article-recommendations',
    symbol: 'Ar',
    name: 'Article Recommendations',
    fullName: 'Einstein Article Recommendations',
    era: 'predictive',
    channels: ['cases', 'messaging', 'voice', 'email', 'knowledge'],
    description: 'Automatically finds and recommends the best knowledge articles to resolve cases faster.',
    storyline: ['Agent views case', 'Einstein searches knowledge base', 'Top articles are surfaced in sidebar'],
    useCases: ['Agent enablement', 'Consistency in support'],
    specs: { tech: 'Vectorized Search', accuracy: 'High' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/einstein-article-recommendations-for-service',
      docs: 'https://help.salesforce.com/s/articleView?id=service.einstein_article_recommendations_introduction.htm&type=5',
      video: null,
    },
    setupRequirements: 'Three or more published knowledge articles',
    jobsToBeDone: ['empower-agents', 'reduce-time', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'reply-recommendations',
    symbol: 'Rr',
    name: 'Reply Recommendations',
    fullName: 'Reply Recommendations',
    era: 'predictive',
    channels: ['messaging'],
    description: 'Suggests pre-trained reply recommendations to agents during live chat sessions to speed up response times.',
    storyline: ['Customer sends message', 'Einstein analyzes past transcripts', 'Agent selects best recommended reply'],
    useCases: ['Faster agent responses', 'Consistent messaging quality'],
    specs: { engine: 'NLU', minimum: '1,000 closed chat transcripts' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/einstein-reply-recommendations-for-service',
      docs: 'https://help.salesforce.com/s/articleView?id=service.reply_rec_intro.htm&type=5',
      video: null,
    },
    setupRequirements: 'Einstein needs at least 1,000 closed chat transcripts in a given language, that contain four or more chat turns. A "turn" is a line in the chat conversation with terms or phrases that can help Einstein learn.',
    jobsToBeDone: ['reduce-time', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'conversation-mining',
    symbol: 'Em',
    name: 'Conversation Mining',
    fullName: 'Einstein Conversation Mining',
    era: 'predictive',
    channels: ['cases', 'messaging', 'voice'],
    description: 'Analyzes case and chat transcripts to uncover common customer problems and automation opportunities.',
    storyline: ['Manager selects transcripts', 'Einstein extracts recurring patterns', 'New bot intents are identified'],
    useCases: ['Data-driven bot strategy', 'Process optimization'],
    specs: { insight: 'Unsupervised ML', output: 'Intent Map' },
    icon: 'analytics',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.conversation_mining_intro.htm&type=5',
      video: null,
    },
    setupRequirements: null,
    jobsToBeDone: ['automate', 'reduce-cost'],
    maturityLevel: 'insights',
  },
  {
    id: 'work-summaries',
    symbol: 'Ws',
    name: 'Work Summaries',
    fullName: 'Einstein Work Summaries',
    era: 'generative',
    channels: ['cases', 'messaging', 'voice', 'field_service'],
    description: 'Automatically drafts case summaries, issues, and resolutions based on interaction history.',
    storyline: ['Interaction ends', 'Einstein drafts the wrap-up summary', 'Agent saves to record'],
    useCases: ['Reduced after-call work', 'Standardized logging'],
    specs: { model: 'LLM Generative', speed: 'Near-instant', trigger: 'Auto at call end', outputs: 'Summary/Issue/Resolution' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/projects/customer-service-replies-and-work-summaries',
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_work_summaries_ai.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.work_summaries_voice_activate.htm&type=5',
      video: null,
    },
    setupRequirements: 'Enable Einstein Work Summaries in Setup; activate Voice Call Summaries; add Wrap Up component to Voice Call page layout; map generated outputs to Salesforce object fields',
    jobsToBeDone: ['reduce-time', 'automate'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'enhanced-summaries',
    symbol: 'Gs',
    name: 'Enhanced Summaries',
    fullName: 'Enhanced Summaries (Case)',
    era: 'generative',
    channels: ['cases'],
    description: 'Provides agents with a concise overview of complex, long-running cases they are inheriting.',
    storyline: ['Agent opens old case', 'GenAI summarizes 20+ emails/notes', 'Agent is briefed in seconds'],
    useCases: ['Faster case transfers', 'Manager escalation reviews'],
    specs: { volume: 'Multi-document', length: 'Concise', grounding: 'Service AI Grounding with Cases' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.generative_ai_enhanced_summaries.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.enhanced_summaries_case_setup.htm&type=5',
      usageDocs: 'https://help.salesforce.com/s/articleView?id=service.case_summaries_use.htm&type=5',
      video: null
    },
    setupRequirements: 'CRITICAL: Requires Service AI Grounding with Cases enabled; role-based configurations for summary customization; Enhanced Summaries User permission set required; character limits configurable',
    jobsToBeDone: ['empower-agents', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'knowledge-creation',
    symbol: 'Kc',
    name: 'Knowledge Creation',
    fullName: 'Einstein Knowledge Creation',
    era: 'generative',
    channels: ['cases', 'messaging', 'email', 'knowledge'],
    description: 'Drafts articles directly from resolved cases to grow the company knowledge base organically.',
    storyline: ['Case resolved', 'Einstein drafts a "How-to"', 'Article is reviewed for publishing'],
    useCases: ['Closing knowledge gaps', 'Crowdsourced expertise'],
    specs: { workflow: 'Integrated Review', source: 'Case + Conversations', grounding: 'Case data', responseTypes: 'Article templates', similarCheck: 'Checks for existing similar articles' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.knowledge_creation_parent.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.knowledge_creation_set_up.htm&type=5',
      fieldDocs: 'https://help.salesforce.com/s/articleView?id=service.knowledge_creation_learn_knowledge_fields.htm&type=5',
      video: null
    },
    setupRequirements: 'Einstein Generative AI + Knowledge enabled; checks for similar articles before drafting; field mapping for article fields; supports case grounding',
    jobsToBeDone: ['automate', 'scale-ops'],
    maturityLevel: 'insights',
  },
  {
    id: 'service-replies',
    symbol: 'Sr',
    name: 'Service Replies',
    fullName: 'Einstein Service Replies',
    era: 'generative',
    channels: ['cases', 'messaging', 'email'],
    description: 'Generates personalized, grounded drafts for agents to use when replying to customers.',
    storyline: ['Customer sends query', 'Einstein drafts perfect response', 'Agent clicks send'],
    useCases: ['Speeding up replies', 'Consistent brand voice'],
    specs: { base: 'Knowledge Articles + Agentforce Data Library', grounding: 'CRM Data + Data Cloud', model: 'LLM Generative', customization: 'Prompt Builder templates' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/einstein-service-replies',
      docs: 'https://help.salesforce.com/s/articleView?id=service.reply_recs_generative_ai_service_replies.htm&type=5',
      messagingDocs: 'https://help.salesforce.com/s/articleView?id=service.reply_recs_service_replies_msg_intro.htm&type=5',
      emailDocs: 'https://help.salesforce.com/s/articleView?id=service.reply_recs_service_replies_email_intro.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.reply_recs_servicec_replies_email_give_agents_access.htm&type=5',
      promptBuilderDocs: 'https://help.salesforce.com/s/articleView?id=service.reply_recs_service_replies_email_prompt_builder.htm&type=5',
      video: null,
    },
    setupRequirements: 'Einstein 1 Service Edition OR Enterprise/Unlimited + Einstein for Service Add-on; assign Email Response User permission set (for email) or Einstein Reply Recommendations User permission set (for messaging/chat); can be grounded in Agentforce Data Library (requires Data 360); customize via Service Replies prompt templates in Prompt Builder',
    jobsToBeDone: ['reduce-time', 'empower-agents', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'search-answers',
    symbol: 'Sa',
    name: 'AI-Generated Search Answers',
    fullName: 'AI-Generated Search Answers',
    era: 'generative',
    channels: ['cases', 'knowledge'],
    description: 'Provides a direct, generated answer at the top of search results instead of just listing links.',
    storyline: ['Agent searches "Policy"', 'Einstein reads top article', 'Einstein generates summary answer'],
    useCases: ['Faster information retrieval', 'Reduced reading time'],
    specs: { tech: 'RAG with Einstein Retrievers', trust: 'Einstein Trust Layer', language: 'English only' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=ai.search_es_agent_access_search_answers.htm&type=5',
      ragDocs: 'https://help.salesforce.com/s/articleView?id=ai.prompt_builder_ground_rag.htm&type=5',
      video: null
    },
    setupRequirements: 'CRITICAL: Legacy "Search Answers" deprecated Spring \'25; now requires Data Cloud version "AI-Generated Search Answers from Data Cloud sources"; assign two permission sets: Einstein Search Answers + Einstein AI-Generated Search Answers; must disable legacy versions before enabling Data Cloud version; requires Service Cloud data kit to map Knowledge to Data Cloud DMO; 24-hour activation period; English only',
    jobsToBeDone: ['reduce-time', 'empower-agents'],
    maturityLevel: 'insights',
  },
  {
    id: 'service-assistant',
    symbol: 'Aa',
    name: 'Service Assistant',
    fullName: 'Agentforce Service Assistant',
    era: 'agentic',
    channels: ['cases', 'messaging'],
    description: 'An intelligent companion in the Service Console that plans actions and assists agents in real-time.',
    storyline: ['Agent asks "Can you help?"', 'Assistant plans investigation', 'Assistant suggests deep actions'],
    useCases: ['Expert guidance for all agents', 'Workflow automation'],
    specs: { engine: 'Atlas Reasoning', interface: 'Sidepanel', grounding: 'Service AI Grounding + Agentforce Data Library' },
    icon: 'memory',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/agentforce-service-planner-quick-look/get-to-know-agentforce-service-planner',
      docs: 'https://help.salesforce.com/s/articleView?id=service.sp_start_setup.htm&type=5',
      groundingDocs: 'https://help.salesforce.com/s/articleView?id=service.sp_comps.htm&type=5',
      prepDocs: 'https://help.salesforce.com/s/articleView?id=service.sp_prep.htm&type=5',
      video: null,
    },
    setupRequirements: 'CRITICAL: Service AI Grounding with Cases required; optional: Agentforce Data Library for Knowledge grounding; permissions: Data Cloud Architect, Knowledge User; renamed from Agentforce Service Planner',
    jobsToBeDone: ['empower-agents', 'automate'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'einstein-bots',
    symbol: 'Eb',
    name: 'Einstein Bots',
    fullName: 'Einstein Bots',
    era: 'predictive',
    channels: ['messaging'],
    description: 'Intelligent chatbots that automate common tasks and deflect basic queries via messaging.',
    storyline: ['Customer types "Hello"', 'Bot identifies intent', 'Bot executes automated flow'],
    useCases: ['24/7 basic support', 'Handling high volumes'],
    specs: { engine: 'NLU + Einstein Intent', tools: 'Flow Builder', channels: 'Chat, SMS, WhatsApp, Facebook Messenger', compliance: 'HIPAA, SOC2 (GA features only)', conversations: '25 per user/month included' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/service_bots',
      docs: 'https://help.salesforce.com/s/articleView?id=bots_service_intro.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=bots_service_setup_overview.htm&type=5',
      nluDocs: 'https://help.salesforce.com/s/articleView?id=bots_service_intro.htm&type=5',
      video: null,
    },
    setupRequirements: 'Service Cloud license + Chat or Messaging license; Lightning Experience enabled; 25 Einstein Bots conversations per user per month included; requires Embedded Chat button on community/site; Salesforce Knowledge if serving articles; permissions: Customize Application OR Modify Metadata OR Manage Bots; HIPAA and SOC2 certified (GA features only)',
    jobsToBeDone: ['scale-ops', 'automate', 'reduce-cost'],
    maturityLevel: 'foundation',
  },
  {
    id: 'conv-summaries',
    symbol: 'Cs',
    name: 'Conv Summaries',
    fullName: 'Conversation Summaries',
    era: 'generative',
    channels: ['messaging', 'voice'],
    description: 'Generates concise summaries of ongoing or completed conversations for faster context.',
    storyline: ['Chat reaches 50+ lines', 'Einstein creates contextual snippet', 'New agent reads it in 2 seconds'],
    useCases: ['Improved hand-offs', 'Supervisor monitoring'],
    specs: { latency: 'Real-time', precision: 'Detailed', triggers: 'High line count, supervisor monitoring, transfer' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/projects/customer-service-replies-and-work-summaries',
      docs: 'https://help.salesforce.com/s/articleView?id=service.cc_generative_ai_ccu.htm&type=5',
      video: null,
    },
    setupRequirements: 'Enable Einstein Generative AI in Setup; part of Conversation Catch-Up feature',
    jobsToBeDone: ['empower-agents', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'conv-catch-up',
    symbol: 'Cc',
    name: 'Conv Catch-Up',
    fullName: 'Conversation Catch-Up',
    era: 'generative',
    channels: ['messaging', 'voice'],
    description: 'Provides a "catch-up" summary specifically for agents being transferred into a live chat.',
    storyline: ['Agent 1 transfers chat', 'Agent 2 gets "Catch-up" alert', 'Agent 2 responds with full context'],
    useCases: ['Eliminating repetitive questions', 'Seamless transfers'],
    specs: { trigger: 'Transfer event, bot-to-agent, supervisor monitoring', speed: 'Instant', tech: 'Real-time LLM' },
    icon: 'auto_awesome',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.cc_generative_ai_ccu.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Enable Einstein Generative AI; turn on Supervisor Summaries and/or Agent Summaries in Work Summaries setup; assign "View Conversation Catch-Up" permission set',
    jobsToBeDone: ['empower-agents', 'increase-csat'],
    maturityLevel: 'insights',
  },
  {
    id: 'service-agent',
    symbol: 'As',
    name: 'Service Agent',
    fullName: 'Agentforce Service Agent',
    era: 'agentic',
    channels: ['messaging', 'email', 'knowledge'],
    description: 'Fully autonomous AI agent that manages entire customer interactions across messaging channels.',
    storyline: ['Customer asks for refund', 'Agent reasons over policy', 'Agent initiates refund securely'],
    useCases: ['End-to-end automation', 'Scaling without hiring'],
    specs: { logic: 'Atlas Reasoning Engine', safety: 'Einstein Trust Layer', channels: 'Enhanced Chat v1/v2, SMS, WhatsApp, Email, Mobile SDK (iOS/Android Beta)', escalation: 'Seamless human handoff' },
    icon: 'memory',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/agentforce-agents-quick-look',
      docs: 'https://help.salesforce.com/s/articleView?id=ai.agent_digital_channels_parent.htm&type=5',
      serviceAgentDocs: 'https://help.salesforce.com/s/articleView?id=ai.agent_service.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=ai.service_agent_setup.htm&type=5',
      emailDocs: 'https://help.salesforce.com/s/articleView?id=ai.agent_email_parent.htm&type=5',
      emailConfigDocs: 'https://help.salesforce.com/s/articleView?id=ai.service_agent_email_configuration.htm&type=5',
      devGuide: 'https://developer.salesforce.com/docs/platform/agentforce/guide/agent-sdk-before-you-begin',
      video: null,
    },
    setupRequirements: 'Create agent from Service Agent template in Agent Builder; configure Enhanced Chat channel with Routing Type: Agentforce Service Agent; select fallback queue; set up Knowledge domain for grounding; configure escalation flow for human handoff; requires Messaging Session object on queue; enable Show Sources in Knowledge settings; Email channel: requires Service Email Connection in Legacy Builder, email template with [[[LEGAL_DISCLOSURE]]] placeholder, 5,000 inbound emails/day default limit',
    jobsToBeDone: ['scale-ops', 'automate', 'reduce-cost'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'proactive-service',
    symbol: 'Ps',
    name: 'Proactive Service',
    fullName: 'Proactive Service for Self-Service',
    era: 'agentic',
    channels: ['messaging'],
    description: 'Initiates self-service help proactively based on business signals (e.g., shipment delay).',
    storyline: ['Event: Item out of stock', 'Agent triggers messaging outreach', 'Customer resolves via Bot'],
    useCases: ['Reducing inbound inquiries', 'Improving CSAT'],
    specs: { trigger: 'Data Cloud Signals + Detection Flows (scheduled/triggered)', outreach: 'Enhanced Chat v1 only', intelligence: 'Data 360 + Agentforce', fulfillment: 'Unified Catalog or Guided Troubleshooting', limitation: 'Not compatible with Enhanced Chat v2' },
    icon: 'memory',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.proactive_service.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.proactive_service_setup.htm&type=5',
      video: null,
    },
    setupRequirements: 'Enterprise, Performance, Unlimited, or Developer Edition + AF1; install Proactive Service Intelligence package; create Data 360 Salesforce connection; configure Enhanced Chat v1 channel (v2 NOT compatible); set up Agentforce Service Agent with General FAQ and Escalation topics; create detection flow (scheduled or Data Cloud-triggered); assign Proactive Services For Internal Users permission set to admins and Proactive Services For Community User to Experience Cloud users; 8-step configuration process',
    jobsToBeDone: ['increase-csat', 'scale-ops'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'conv-intelligence',
    symbol: 'Ci',
    name: 'Conv Insights',
    fullName: 'Einstein Conversation Insights',
    era: 'predictive',
    channels: ['voice'],
    description: 'Analyzes call recordings to identify key moments, action items, rep talk/listen ratios, and custom keyword mentions for coaching and quality assurance.',
    storyline: ['Call recorded & transcribed', 'Einstein analyzes key moments and keywords', 'Manager reviews insights for coaching', 'Rep performance improves'],
    useCases: ['Quality assurance automation', 'Coaching reps on talk/listen ratios', 'Tracking product mentions', 'Identifying training opportunities'],
    specs: { tech: 'Audio processing + NLP', insights: 'Up to 100 custom insights', keywords: '25 per insight', features: 'Talk/listen ratios, keyword tracking' },
    icon: 'analytics',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_conversation_insights_intro.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Requires Einstein Conversation Insights license; Service Cloud Voice; speaker identification via telephony provider or Optimal Speaker Separation; available for both Service and Sales Cloud',
    jobsToBeDone: ['empower-agents', 'improve-data'],
    maturityLevel: 'foundation',
  },
  {
    id: 'sentiment-journey',
    symbol: 'Sj',
    name: 'Sentiment Journey',
    fullName: 'Sentiment Journey for Call Conversations',
    era: 'predictive',
    channels: ['voice'],
    description: 'Analyzes voice calls in real-time to provide turn-by-turn sentiment scores for agents and customers with visual sentiment journey graphs.',
    storyline: ['Customer and agent converse on call', 'Telephony AI analyzes speech patterns in real-time', 'Sentiment Journey graph shows emotional trajectory', 'Supervisor identifies coaching moments post-call'],
    useCases: ['Quality assurance automation', 'Rep coaching and training', 'Real-time escalation triggers', 'CSAT prediction and correlation'],
    specs: { source: 'Telephony Provider AI', tech: 'NLP + Audio Analysis', fields: 'Agent/Customer Sentiment Score', accuracy: 'High', visual: 'Sentiment Journey graph' },
    icon: 'analytics',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_conversation_sentiments.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Service Cloud Voice with sentiment-capable telephony (Amazon Connect Contact Lens or partner); EventBridge rule for Contact Lens; Call Audio Player component on Voice Call layout; optionally add Agent/Customer Sentiment Score fields to layout and reports',
    jobsToBeDone: ['empower-agents', 'improve-data', 'reduce-cost'],
    maturityLevel: 'insights',
  },
  {
    id: 'nba-voice-intelligence',
    symbol: 'Nv',
    name: 'Next Best Action (Voice)',
    fullName: 'Next Best Action with Conversation Intelligence',
    era: 'predictive',
    channels: ['voice', 'messaging'],
    description: 'Shows real-time recommendations to agents based on intelligence signals from telephony or keyword detection during conversations.',
    storyline: ['Customer expresses frustration during call', 'Telephony detects negative sentiment signal', 'Conversation Intelligence rule triggers', 'Next Best Action recommends retention offer', 'Agent executes recommendation in real-time'],
    useCases: ['Proactive retention and win-back offers', 'Real-time supervisor escalation', 'Compliance and legal reminders', 'Upsell and cross-sell automation'],
    specs: { triggers: 'Intelligence Signals + Keywords', engine: 'Recommendation Strategy', actions: 'NBA / Flow / Alert', latency: 'Near-instant', detection: 'Case-insensitive exact match' },
    icon: 'analytics',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_intelligence_take_action_on_signals.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.voice_conversation_intelligence_nba.htm&type=5',
      keywordDocs: 'https://help.salesforce.com/s/articleView?id=service.voice_trigger_action_with_keywords.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Create Conversation Intelligence Rules in Setup; define intelligence signals in telephony system or configure keyword triggers; build Recommendation Strategy; add Next Best Action component to page layout; requires Customize Application permission',
    jobsToBeDone: ['empower-agents', 'increase-revenue', 'increase-csat', 'automate'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'agentforce-voice',
    symbol: 'Av',
    name: 'Agentforce Voice',
    fullName: 'Agentforce Voice',
    era: 'agentic',
    channels: ['voice'],
    description: 'Autonomous AI agents that understand customer intent from spoken input and handle complete voice conversations, replacing traditional IVR with intelligent, conversational experiences.',
    storyline: ['Customer calls and speaks naturally', 'Agentforce Voice understands intent', 'Agent autonomously resolves query', 'Escalates to human when needed'],
    useCases: ['24/7 autonomous phone support', 'Intelligent IVR replacement', 'High-volume call deflection', 'Seamless human escalation'],
    specs: { engine: 'Atlas Reasoning Engine', tech: 'Speech-to-text + NLU + Text-to-speech', trust: 'Einstein Trust Layer', availability: '24/7', escalation: 'Built-in human handoff', mobile: 'iOS/Android SDK (Beta)' },
    icon: 'memory',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=ai.agentforce_voice.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=ai.agent_connect_telephony_parent.htm&type=5',
      devGuide: 'https://developer.salesforce.com/docs/platform/agentforce/overview',
      partnerGuide: 'https://developer.salesforce.com/docs/platform/agentforce-partners/guide/agentforce-voice-overview',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Service Cloud Voice must be turned on (complete setup not required for CCaaS); configure Agentforce Service Agent in Agent Builder or Legacy Builder; connect telephony system (Amazon Connect, Genesys, CCaaS partners); full Service Cloud Voice setup enables seamless agent escalation and context passing',
    jobsToBeDone: ['scale-ops', 'automate', 'reduce-cost'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'email-prompt-templates',
    symbol: 'Et',
    name: 'Email Prompt Templates',
    fullName: 'Pre-Made Email Prompt Templates for Service',
    era: 'generative',
    channels: ['email'],
    description: 'Pre-made Prompt Builder templates that generate personalized email drafts grounded in case and customer data.',
    storyline: ['Agent composes email', 'Selects pre-made prompt template (Introduction/Follow-up/Acknowledgment)', 'Einstein drafts personalized reply', 'Agent reviews and sends'],
    useCases: ['Faster email composition', 'Consistent brand voice', 'Case-grounded responses'],
    specs: { type: 'Prompt Builder templates', grounding: 'Case + Customer data', templates: 'Introduction, Follow-up, Acknowledgment' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.service_replies_email_prompt_templates.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.reply_recs_service_replies_email_prompt_builder.htm&type=5',
      video: null
    },
    setupRequirements: 'Assign two permission sets: Prompt Template User + Einstein Service Email Assistant User; templates accessed via Email Compose interface',
    jobsToBeDone: ['automate', 'reduce-time', 'empower-agents'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'email-summaries',
    symbol: 'Es',
    name: 'Email Summaries',
    fullName: 'Einstein Work Summaries for Email',
    era: 'generative',
    channels: ['email'],
    description: 'Automatically summarizes single emails or entire email threads on cases to help agents quickly understand context.',
    storyline: ['Agent opens case with email thread', 'Einstein analyzes email messages', 'Summary generated in Einstein Email Summaries component', 'Agent gets context instantly'],
    useCases: ['Faster case context understanding', 'Reduced email reading time', 'Better handoff efficiency'],
    specs: { model: 'LLM Generative', speed: 'Near-instant', customization: 'Prompt Builder (summary length)', component: 'Einstein Email Summaries' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.work_summaries_email_show.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.work_summaries_email_activate.htm&type=5',
      componentDocs: 'https://help.salesforce.com/s/articleView?id=service.work_summaries_email_component.htm&type=5',
      video: null
    },
    setupRequirements: 'Email-to-Case enabled; Einstein Generative AI + Work Summaries enabled; activate Email Message Summaries in Einstein Work Summaries setup; add Einstein Email Summaries component to Case page layout; assign permission sets: Work Summaries User + Execute Prompt Templates',
    jobsToBeDone: ['reduce-time', 'empower-agents'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'next-best-action',
    symbol: 'Nb',
    name: 'Next Best Action',
    fullName: 'Einstein Next Best Action',
    era: 'predictive',
    channels: ['field_service'],
    description: 'Recommends optimal up-sell and cross-sell opportunities at the moment of job completion.',
    storyline: ['Technician finishes repair', 'Einstein suggests "Battery Upgrade"', 'Technician adds to work order'],
    useCases: ['Increasing field revenue', 'Proactive maintenance'],
    specs: { tech: 'Recommendation Strategy (Flow-based)', ui: 'App & Console', object: 'Recommendation object', integration: 'Works with Einstein Recommendation Builder', template: 'Parts to Work Orders for FSL' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/users/rodrigovp97/trailmixes/next-best-action',
      docs: 'https://help.salesforce.com/s/articleView?id=platform.nba_implementation_checklist.htm&type=5',
      componentDocs: 'https://help.salesforce.com/s/articleView?id=platform.nba_lab_cmp.htm&type=5',
      video: null,
    },
    setupRequirements: 'Build Recommendation Strategy; add Next Best Action component to page layout; requires Customize Application permission; integrates with Einstein Recommendation Builder for Field Service',
    jobsToBeDone: ['increase-revenue', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'recommend-builder',
    symbol: 'Rb',
    name: 'Recommend Builder',
    fullName: 'Einstein Recommendation Builder',
    era: 'predictive',
    channels: ['field_service'],
    description: 'Allows builds of custom recommendation models to predict parts, skills, or objects for field jobs.',
    storyline: ['Historical work orders analyzed', 'Einstein predicts "Skill: HVAC Senior"', 'Dispatcher assigns correctly'],
    useCases: ['Optimizing first-time fix rates', 'Resource allocation'],
    specs: { tool: 'Declarative Builder', target: 'Any Standard Object', tech: 'AutoML-based', buildTime: '30 minutes to 24 hours', validation: 'Data Checker', quality: 'Quality scorecard provided' },
    icon: 'analytics',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=sales.custom_ai_recommendation_builder_setup.htm&type=5',
      buildDocs: 'https://help.salesforce.com/s/articleView?id=sales.custom_ai_recommendation_builder_create.htm&type=5',
      templateDocs: 'https://help.salesforce.com/s/articleView?id=sales.custom_ai_recommendation_builder_parts_template.htm&type=5',
      video: null
    },
    setupRequirements: 'Field Service template: "Parts to Work Orders"; run Data Checker validation before building; 30 minutes to 24 hours build time; quality scorecard provided after build; declarative builder (no code)',
    jobsToBeDone: ['automate', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'pre-work-brief',
    symbol: 'Pb',
    name: 'Pre-Work Brief',
    fullName: 'Pre-Work Brief (GenAI)',
    era: 'generative',
    channels: ['field_service'],
    description: 'Gathers all customer history and asset info into a short, easy-to-read brief for a mobile technician.',
    storyline: ['Technician arrives on site', 'Opens mobile phone', 'GenAI gives 3-point summary of asset history'],
    useCases: ['Better prepared technicians', 'Enhanced customer experience'],
    specs: { output: 'Mobile Optimized', source: 'Asset & Case History', platform: 'Field Service mobile app (Android/iOS)', voiceSupport: 'iOS Siri shortcuts' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.mfs_einstein_pre_work_brief.htm&type=5',
      video: null
    },
    setupRequirements: 'License: Einstein for Field Service add-on OR Agentforce for Field Service add-on OR Einstein 1 Field Service Edition; Field Service mobile app (Android/iOS); Lightning Data Service for Field Service Mobile prerequisite; iOS Siri shortcuts: "Hey Siri, tell me about my next job in Field Service"',
    jobsToBeDone: ['empower-agents', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'fs-agent',
    symbol: 'Af',
    name: 'FS Agent',
    fullName: 'Agentforce Field Service Agent',
    era: 'agentic',
    channels: ['field_service'],
    description: 'An autonomous agent that manages technician questions and administrative field tasks.',
    storyline: ['Technician asks "How many bolts?"', 'Agent checks PDF manual', 'Agent supplies specs instantly'],
    useCases: ['Mobile self-sufficiency', 'Reduced back-office calls'],
    specs: { tech: 'Retrieval Augmented Plan', ui: 'FSL Mobile App', template: 'Field Service Mobile Work', platform: 'iOS/Android with Siri shortcuts', capabilities: 'Find/summarize records, post-work summaries, knowledge answers, scheduling' },
    icon: 'memory',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.mfs_overview.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.fs_einstein_copilot_example_post_work_summary.htm&type=5',
      video: null
    },
    setupRequirements: 'Template: "Field Service Mobile Work" from Agent Builder; License: Einstein for Field Service add-on OR Agentforce for Field Service add-on; Field Service mobile app (Android/iOS); iOS Siri shortcuts support; capabilities: find/summarize records, post-work summaries, knowledge answers, scheduling',
    jobsToBeDone: ['empower-agents', 'reduce-cost'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'scheduling-agent',
    symbol: 'As',
    name: 'Scheduling Agent',
    fullName: 'Agentforce Scheduling Agent',
    era: 'agentic',
    channels: ['field_service'],
    description: 'Manages complex rescheduling and scheduling tasks autonomously for customers.',
    storyline: ["Customer texts 'Can't make it'", 'Agent finds new slot', 'Agent updates job in FSL'],
    useCases: ['Appointment flexibility', 'Dispatcher relief'],
    specs: { logic: 'Optimization Engine', flow: 'Conversational', template: 'Scheduling Agent for Field Service', actions: 'Get Time Slots, Schedule Appointment, Get Appointments By Criteria', monitoring: 'Agentforce Scheduling Supervisor View', additionalFeatures: 'Fill Schedule Gaps, Summarize Scheduling Issues, Summarize Service Appointment Notes (Beta)' },
    icon: 'memory',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.fs_einstein_agentforce_scheduling_agent.htm&type=5',
      configDocs: 'https://help.salesforce.com/s/articleView?id=service.fs_einstein_agentforce_scheduling_configure.htm&type=5',
      supervisorDocs: 'https://help.salesforce.com/s/articleView?id=service.fs_agentforce_supervisor_view_parent.htm&type=5',
      permissionsDocs: 'https://help.salesforce.com/s/articleView?id=service.fs_agentforce_supervisor_view_parent.htm&type=5',
      video: null
    },
    setupRequirements: 'Template: "Scheduling Agent for Field Service" from Agent Builder; capabilities: customer-initiated scheduling, dispatcher-prompted outreach, proactive asset scheduling; standard actions: Get Time Slots, Schedule Appointment, Get Appointments By Criteria; monitoring via Agentforce Scheduling Supervisor View; additional features: Fill Schedule Gaps, Summarize Scheduling Issues, Summarize Service Appointment Notes (Beta)',
    jobsToBeDone: ['automate', 'increase-csat'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'knowledge-edits',
    symbol: 'Ke',
    name: 'Knowledge Edits',
    fullName: 'Einstein Knowledge Edits',
    era: 'generative',
    channels: ['knowledge'],
    description: 'Helps knowledge managers rewrite, shorten, or change the tone of existing articles.',
    storyline: ['Clunky article text highlighted', 'Einstein rewrites for clarity', 'Manager publishes professional version'],
    useCases: ['Faster article lifecycle', 'Better readability'],
    specs: { feature: 'Tone & Style control', tool: 'Knowledge Console', styles: 'Conciseness, Grammar, Readability', access: 'Edit quick action → "Revise with Einstein" toolbar button' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.knowledge_creation_einstein_edits.htm&type=5',
      video: null
    },
    setupRequirements: 'Same as Einstein Knowledge Creation; predefined styles: Conciseness, Grammar, Readability; accessed via article Edit quick action → "Revise with Einstein" toolbar button',
    jobsToBeDone: ['automate', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'service-ai-grounding',
    symbol: 'Sg',
    name: 'Service AI Grounding',
    fullName: 'Service AI Grounding',
    era: 'generative',
    channels: ['knowledge', 'cases'],
    description: 'Grounds generative AI responses in verified Salesforce Knowledge articles and CRM data to ensure accurate, trusted outputs.',
    storyline: ['Agent or bot asks a question', 'Einstein Trust Layer retrieves grounding data', 'GenAI generates a grounded, accurate response'],
    useCases: ['Trusted AI outputs', 'Reducing hallucinations'],
    specs: { tech: 'RAG + Einstein Trust Layer', source: 'Knowledge + CRM', casesFields: 'Subject + Description required', knowledgeFields: 'Title + Summary required', language: 'English only' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/grounding-an-agent-with-data',
      docs: 'https://help.salesforce.com/s/articleView?id=service.einstein_generative_ai_enable_grounding.xml&type=5',
      knowledgeDocs: 'https://help.salesforce.com/s/articleView?id=service.einstein_generative_ai_ground_knowledge.htm&type=5',
      dataLibraryDocs: 'https://help.salesforce.com/s/articleView?id=ai.data_library_concept.htm&type=5',
      video: null,
    },
    setupRequirements: 'Case grounding: Subject + Description fields required; Case Feed NOT supported as grounding source; Knowledge grounding: via Agentforce Data Libraries (chunks and indexes articles); only Salesforce Knowledge supported (NOT Unified Knowledge or Enterprise Knowledge); Title + Summary required for Knowledge; permissions: Data Cloud Architect, Knowledge User; field-level security applies; English only currently',
    jobsToBeDone: ['improve-data', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'real-time-translations',
    symbol: 'Rt',
    name: 'Real-Time Translations',
    fullName: 'Real-Time Translations',
    era: 'generative',
    channels: ['messaging', 'email'],
    description: 'Translates customer and agent messages in real-time during messaging conversations, enabling cross-language support.',
    storyline: ['Customer messages in Spanish', "GenAI translates to agent's language", 'Agent replies and customer sees translation'],
    useCases: ['Global customer support', 'Eliminating language barriers'],
    specs: { type: 'Real-time machine translation', channels: 'Enhanced Messaging + Enhanced Chat + Service Email', customization: 'Custom terminology support (.csv, .tsx, .tmx)', monitoring: 'Supervisor translation', languages: 'Up to 10 custom languages' },
    icon: 'auto_awesome',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.real_time_translations_intro.htm&type=5',
      messagingDocs: 'https://help.salesforce.com/s/articleView?id=service.realtime_translation_messaging.htm&type=5',
      emailDocs: 'https://help.salesforce.com/s/articleView?id=service.realtime_translation_email.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.messaging_translate_2.htm&type=5',
      video: null,
    },
    setupRequirements: 'Enable Real-Time Translations in Setup under Real-Time Translations page; turn on for Enhanced Chat and Enhanced Messaging; optionally upload custom terminology file (.csv, .tsx, or .tmx) for up to 10 languages to preserve brand terms; recommend adding disclosure in Start Conversation auto-response or chat window Terms and Conditions; supervisor translation capability available',
    jobsToBeDone: ['scale-ops', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
];
