export const CAPABILITIES = [
  {
    id: 'case-classification',
    symbol: 'Ec',
    name: 'Case Classification',
    fullName: 'Einstein Case Classification',
    era: 'predictive',
    channels: ['cases'],
    description: 'Predicts picklist and checkbox field values on new cases based on past cases to reduce manual entry.',
    storyline: ['Case arrives', 'Einstein analyzes subject/description', 'Fields are predicted automatically'],
    useCases: ['Faster case triaging', 'Improved data quality'],
    specs: { model: 'AutoML', target: 'Case Fields' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/service_case_class',
      docs: null,
      video: 'https://salesforce.vidyard.com/watch/SVYoP4cGZbsbeAhcLjGRiF',
    },
    setupRequirements: 'At least 400 closed cases from the past 6 months are needed to build the model, with 1,000+ ideal for better accuracy;',
    jobsToBeDone: ['improve-data', 'reduce-time', 'automate'],
    maturityLevel: 'foundation',
  },
  {
    id: 'case-routing',
    symbol: 'Er',
    name: 'Case Routing',
    fullName: 'Einstein Case Routing',
    era: 'predictive',
    channels: ['cases'],
    description: 'Uses predicted field values to ensure cases reach the right agent or queue immediately.',
    storyline: ['Einstein predicts case category', 'Omni-Channel uses prediction to find expert', 'Case is pushed to agent'],
    useCases: ['Reducing transfers', 'Faster first response'],
    specs: { logic: 'Omni-Channel', trigger: 'Classification' },
    icon: 'analytics',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.cc_service_rules.htm&type=5',
      video: 'https://salesforce.vidyard.com/watch/SVYoP4cGZbsbeAhcLjGRiF',
    },
    setupRequirements: null,
    jobsToBeDone: ['reduce-time', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'case-wrap-up',
    symbol: 'Ew',
    name: 'Case Wrap-Up',
    fullName: 'Einstein Case Wrap-Up',
    era: 'predictive',
    channels: ['cases'],
    description: 'Suggests values for fields like "Resolution" or "Root Cause" when an agent is closing a case.',
    storyline: ['Agent begins closing case', 'Einstein suggests wrap-up values', 'Agent confirms and saves'],
    useCases: ['Streamlined closing', 'Better trend reporting'],
    specs: { trigger: 'Status: Closed', feedback: 'Real-time' },
    icon: 'analytics',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: 'Minimum 400 closed cases from past 6 months with subject/description; accuracy improves with 1,000+ and chat transcripts included',
    jobsToBeDone: ['improve-data', 'reduce-time'],
    maturityLevel: 'insights',
  },
  {
    id: 'article-recommendations',
    symbol: 'Ar',
    name: 'Article Recommendations',
    fullName: 'Einstein Article Recommendations',
    era: 'predictive',
    channels: ['cases', 'messaging', 'voice', 'email', 'knowledge'],
    description: 'Automatically finds and recommends the best knowledge articles to resolve cases faster.',
    storyline: ['Agent views case', 'Einstein searches knowledge base', 'Top articles are surfaced in sidebar'],
    useCases: ['Agent enablement', 'Consistency in support'],
    specs: { tech: 'Vectorized Search', accuracy: 'High' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/einstein-article-recommendations-for-service',
      docs: 'https://help.salesforce.com/s/articleView?id=service.einstein_article_recommendations_introduction.htm&type=5',
      video: null,
    },
    setupRequirements: 'Three or more published knowledge articles',
    jobsToBeDone: ['empower-agents', 'reduce-time', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'reply-recommendations',
    symbol: 'Rr',
    name: 'Reply Recommendations',
    fullName: 'Reply Recommendations',
    era: 'predictive',
    channels: ['messaging'],
    description: 'Suggests pre-trained reply recommendations to agents during live chat sessions to speed up response times.',
    storyline: ['Customer sends message', 'Einstein analyzes past transcripts', 'Agent selects best recommended reply'],
    useCases: ['Faster agent responses', 'Consistent messaging quality'],
    specs: { engine: 'NLU', minimum: '1,000 closed chat transcripts' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/einstein-reply-recommendations-for-service',
      docs: 'https://help.salesforce.com/s/articleView?id=service.reply_rec_intro.htm&type=5',
      video: null,
    },
    setupRequirements: 'Einstein needs at least 1,000 closed chat transcripts in a given language, that contain four or more chat turns. A "turn" is a line in the chat conversation with terms or phrases that can help Einstein learn.',
    jobsToBeDone: ['reduce-time', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'conversation-mining',
    symbol: 'Em',
    name: 'Conversation Mining',
    fullName: 'Einstein Conversation Mining',
    era: 'predictive',
    channels: ['cases', 'messaging', 'voice'],
    description: 'Analyzes case and chat transcripts to uncover common customer problems and automation opportunities.',
    storyline: ['Manager selects transcripts', 'Einstein extracts recurring patterns', 'New bot intents are identified'],
    useCases: ['Data-driven bot strategy', 'Process optimization'],
    specs: { insight: 'Unsupervised ML', output: 'Intent Map' },
    icon: 'analytics',
    links: {
      trailhead: null,
      docs: 'https://help.salesforce.com/s/articleView?id=service.conversation_mining_intro.htm&type=5',
      video: null,
    },
    setupRequirements: null,
    jobsToBeDone: ['automate', 'reduce-cost'],
    maturityLevel: 'insights',
  },
  {
    id: 'work-summaries',
    symbol: 'Ws',
    name: 'Work Summaries',
    fullName: 'Einstein Work Summaries',
    era: 'generative',
    channels: ['cases', 'messaging', 'voice', 'field_service'],
    description: 'Automatically drafts case summaries, issues, and resolutions based on interaction history.',
    storyline: ['Interaction ends', 'Einstein drafts the wrap-up summary', 'Agent saves to record'],
    useCases: ['Reduced after-call work', 'Standardized logging'],
    specs: { model: 'LLM Generative', speed: 'Near-instant', trigger: 'Auto at call end', outputs: 'Summary/Issue/Resolution' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/projects/customer-service-replies-and-work-summaries',
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_work_summaries_ai.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.work_summaries_voice_activate.htm&type=5',
      video: null,
    },
    setupRequirements: 'Enable Einstein Work Summaries in Setup; activate Voice Call Summaries; add Wrap Up component to Voice Call page layout; map generated outputs to Salesforce object fields',
    jobsToBeDone: ['reduce-time', 'automate'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'enhanced-summaries',
    symbol: 'Gs',
    name: 'Enhanced Summaries',
    fullName: 'Enhanced Summaries (Case)',
    era: 'generative',
    channels: ['cases'],
    description: 'Provides agents with a concise overview of complex, long-running cases they are inheriting.',
    storyline: ['Agent opens old case', 'GenAI summarizes 20+ emails/notes', 'Agent is briefed in seconds'],
    useCases: ['Faster case transfers', 'Manager escalation reviews'],
    specs: { volume: 'Multi-document', length: 'Concise' },
    icon: 'auto_awesome',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['empower-agents', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'knowledge-creation',
    symbol: 'Kc',
    name: 'Knowledge Creation',
    fullName: 'Einstein Knowledge Creation',
    era: 'generative',
    channels: ['cases', 'messaging', 'email', 'knowledge'],
    description: 'Drafts articles directly from resolved cases to grow the company knowledge base organically.',
    storyline: ['Case resolved', 'Einstein drafts a "How-to"', 'Article is reviewed for publishing'],
    useCases: ['Closing knowledge gaps', 'Crowdsourced expertise'],
    specs: { workflow: 'Integrated Review', source: 'Case + Conversations' },
    icon: 'auto_awesome',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['automate', 'scale-ops'],
    maturityLevel: 'insights',
  },
  {
    id: 'service-replies',
    symbol: 'Sr',
    name: 'Service Replies',
    fullName: 'Einstein Service Replies',
    era: 'generative',
    channels: ['cases', 'messaging', 'email'],
    description: 'Generates personalized, grounded drafts for agents to use when replying to customers.',
    storyline: ['Customer sends query', 'Einstein drafts perfect response', 'Agent clicks send'],
    useCases: ['Speeding up replies', 'Consistent brand voice'],
    specs: { base: 'Knowledge Articles', grounding: 'CRM Data' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/einstein-service-replies?_ga=2.264459791.1293857143.1757594962-209827848.1757594492',
      docs: null,
      video: null,
    },
    setupRequirements: null,
    jobsToBeDone: ['reduce-time', 'empower-agents', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'search-answers',
    symbol: 'Sa',
    name: 'Search Answers',
    fullName: 'Einstein Search Answers',
    era: 'generative',
    channels: ['cases', 'knowledge'],
    description: 'Provides a direct, generated answer at the top of search results instead of just listing links.',
    storyline: ['Agent searches "Policy"', 'Einstein reads top article', 'Einstein generates summary answer'],
    useCases: ['Faster information retrieval', 'Reduced reading time'],
    specs: { tech: 'RAG', trust: 'Einstein Trust Layer' },
    icon: 'auto_awesome',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['reduce-time', 'empower-agents'],
    maturityLevel: 'insights',
  },
  {
    id: 'service-assistant',
    symbol: 'Aa',
    name: 'Service Assistant',
    fullName: 'Agentforce Service Assistant',
    era: 'agentic',
    channels: ['cases', 'messaging'],
    description: 'An intelligent companion in the Service Console that plans actions and assists agents in real-time.',
    storyline: ['Agent asks "Can you help?"', 'Assistant plans investigation', 'Assistant suggests deep actions'],
    useCases: ['Expert guidance for all agents', 'Workflow automation'],
    specs: { engine: 'Atlas Reasoning', interface: 'Sidepanel' },
    icon: 'memory',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/agentforce-service-planner-quick-look/get-to-know-agentforce-service-planner',
      docs: null,
      video: null,
    },
    setupRequirements: 'Workbook note: renamed from Agentforce Service Planner.',
    jobsToBeDone: ['empower-agents', 'automate'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'einstein-bots',
    symbol: 'Eb',
    name: 'Einstein Bots',
    fullName: 'Einstein Bots',
    era: 'predictive',
    channels: ['messaging'],
    description: 'Intelligent chatbots that automate common tasks and deflect basic queries via messaging.',
    storyline: ['Customer types "Hello"', 'Bot identifies intent', 'Bot executes automated flow'],
    useCases: ['24/7 basic support', 'Handling high volumes'],
    specs: { engine: 'NLU', tools: 'Flow Builder' },
    icon: 'analytics',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['scale-ops', 'automate', 'reduce-cost'],
    maturityLevel: 'foundation',
  },
  {
    id: 'conv-summaries',
    symbol: 'Cs',
    name: 'Conv Summaries',
    fullName: 'Conversation Summaries',
    era: 'generative',
    channels: ['messaging', 'voice'],
    description: 'Generates concise summaries of ongoing or completed conversations for faster context.',
    storyline: ['Chat reaches 50+ lines', 'Einstein creates contextual snippet', 'New agent reads it in 2 seconds'],
    useCases: ['Improved hand-offs', 'Supervisor monitoring'],
    specs: { latency: 'Real-time', precision: 'Detailed', triggers: 'High line count, supervisor monitoring, transfer' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/projects/customer-service-replies-and-work-summaries',
      docs: 'https://help.salesforce.com/s/articleView?id=service.cc_generative_ai_ccu.htm&type=5',
      video: null,
    },
    setupRequirements: 'Enable Einstein Generative AI in Setup; part of Conversation Catch-Up feature',
    jobsToBeDone: ['empower-agents', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'conv-catch-up',
    symbol: 'Cc',
    name: 'Conv Catch-Up',
    fullName: 'Conversation Catch-Up',
    era: 'generative',
    channels: ['messaging', 'voice'],
    description: 'Provides a "catch-up" summary specifically for agents being transferred into a live chat.',
    storyline: ['Agent 1 transfers chat', 'Agent 2 gets "Catch-up" alert', 'Agent 2 responds with full context'],
    useCases: ['Eliminating repetitive questions', 'Seamless transfers'],
    specs: { trigger: 'Transfer event, bot-to-agent, supervisor monitoring', speed: 'Instant', tech: 'Real-time LLM' },
    icon: 'auto_awesome',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.cc_generative_ai_ccu.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Enable Einstein Generative AI; turn on Supervisor Summaries and/or Agent Summaries in Work Summaries setup; assign "View Conversation Catch-Up" permission set',
    jobsToBeDone: ['empower-agents', 'increase-csat'],
    maturityLevel: 'insights',
  },
  {
    id: 'service-agent',
    symbol: 'As',
    name: 'Service Agent',
    fullName: 'Agentforce Service Agent',
    era: 'agentic',
    channels: ['messaging', 'email', 'knowledge'],
    description: 'Fully autonomous AI agent that manages entire customer interactions across messaging channels.',
    storyline: ['Customer asks for refund', 'Agent reasons over policy', 'Agent initiates refund securely'],
    useCases: ['End-to-end automation', 'Scaling without hiring'],
    specs: { logic: 'Atlas Engine', safety: 'Einstein Trust Layer' },
    icon: 'memory',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['scale-ops', 'automate', 'reduce-cost'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'proactive-service',
    symbol: 'Ps',
    name: 'Proactive Service',
    fullName: 'Proactive Service for Self-Service',
    era: 'agentic',
    channels: ['messaging'],
    description: 'Initiates self-service help proactively based on business signals (e.g., shipment delay).',
    storyline: ['Event: Item out of stock', 'Agent triggers messaging outreach', 'Customer resolves via Bot'],
    useCases: ['Reducing inbound inquiries', 'Improving CSAT'],
    specs: { trigger: 'Data Cloud Signals', outreach: 'Digital' },
    icon: 'memory',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: 'Workbook note: renamed from Self Service portals to Proactive Service.',
    jobsToBeDone: ['increase-csat', 'scale-ops'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'conv-intelligence',
    symbol: 'Ci',
    name: 'Conv Insights',
    fullName: 'Einstein Conversation Insights',
    era: 'predictive',
    channels: ['voice'],
    description: 'Analyzes call recordings to identify key moments, action items, rep talk/listen ratios, and custom keyword mentions for coaching and quality assurance.',
    storyline: ['Call recorded & transcribed', 'Einstein analyzes key moments and keywords', 'Manager reviews insights for coaching', 'Rep performance improves'],
    useCases: ['Quality assurance automation', 'Coaching reps on talk/listen ratios', 'Tracking product mentions', 'Identifying training opportunities'],
    specs: { tech: 'Audio processing + NLP', insights: 'Up to 100 custom insights', keywords: '25 per insight', features: 'Talk/listen ratios, keyword tracking' },
    icon: 'analytics',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_conversation_insights_intro.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Requires Einstein Conversation Insights license; Service Cloud Voice; speaker identification via telephony provider or Optimal Speaker Separation; available for both Service and Sales Cloud',
    jobsToBeDone: ['empower-agents', 'improve-data'],
    maturityLevel: 'foundation',
  },
  {
    id: 'sentiment-journey',
    symbol: 'Sj',
    name: 'Sentiment Journey',
    fullName: 'Sentiment Journey for Call Conversations',
    era: 'predictive',
    channels: ['voice'],
    description: 'Analyzes voice calls in real-time to provide turn-by-turn sentiment scores for agents and customers with visual sentiment journey graphs.',
    storyline: ['Customer and agent converse on call', 'Telephony AI analyzes speech patterns in real-time', 'Sentiment Journey graph shows emotional trajectory', 'Supervisor identifies coaching moments post-call'],
    useCases: ['Quality assurance automation', 'Rep coaching and training', 'Real-time escalation triggers', 'CSAT prediction and correlation'],
    specs: { source: 'Telephony Provider AI', tech: 'NLP + Audio Analysis', fields: 'Agent/Customer Sentiment Score', accuracy: 'High', visual: 'Sentiment Journey graph' },
    icon: 'analytics',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_conversation_sentiments.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Service Cloud Voice with sentiment-capable telephony (Amazon Connect Contact Lens or partner); EventBridge rule for Contact Lens; Call Audio Player component on Voice Call layout; optionally add Agent/Customer Sentiment Score fields to layout and reports',
    jobsToBeDone: ['empower-agents', 'improve-data', 'reduce-cost'],
    maturityLevel: 'insights',
  },
  {
    id: 'nba-voice-intelligence',
    symbol: 'Nv',
    name: 'Next Best Action (Voice)',
    fullName: 'Next Best Action with Conversation Intelligence',
    era: 'predictive',
    channels: ['voice', 'messaging'],
    description: 'Shows real-time recommendations to agents based on intelligence signals from telephony or keyword detection during conversations.',
    storyline: ['Customer expresses frustration during call', 'Telephony detects negative sentiment signal', 'Conversation Intelligence rule triggers', 'Next Best Action recommends retention offer', 'Agent executes recommendation in real-time'],
    useCases: ['Proactive retention and win-back offers', 'Real-time supervisor escalation', 'Compliance and legal reminders', 'Upsell and cross-sell automation'],
    specs: { triggers: 'Intelligence Signals + Keywords', engine: 'Recommendation Strategy', actions: 'NBA / Flow / Alert', latency: 'Near-instant', detection: 'Case-insensitive exact match' },
    icon: 'analytics',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=service.voice_intelligence_take_action_on_signals.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=service.voice_conversation_intelligence_nba.htm&type=5',
      keywordDocs: 'https://help.salesforce.com/s/articleView?id=service.voice_trigger_action_with_keywords.htm&type=5',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Create Conversation Intelligence Rules in Setup; define intelligence signals in telephony system or configure keyword triggers; build Recommendation Strategy; add Next Best Action component to page layout; requires Customize Application permission',
    jobsToBeDone: ['empower-agents', 'increase-revenue', 'increase-csat', 'automate'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'agentforce-voice',
    symbol: 'Av',
    name: 'Agentforce Voice',
    fullName: 'Agentforce Voice',
    era: 'agentic',
    channels: ['voice'],
    description: 'Autonomous AI agents that understand customer intent from spoken input and handle complete voice conversations, replacing traditional IVR with intelligent, conversational experiences.',
    storyline: ['Customer calls and speaks naturally', 'Agentforce Voice understands intent', 'Agent autonomously resolves query', 'Escalates to human when needed'],
    useCases: ['24/7 autonomous phone support', 'Intelligent IVR replacement', 'High-volume call deflection', 'Seamless human escalation'],
    specs: { engine: 'Atlas Reasoning Engine', tech: 'Speech-to-text + NLU + Text-to-speech', trust: 'Einstein Trust Layer', availability: '24/7', escalation: 'Built-in human handoff', mobile: 'iOS/Android SDK (Beta)' },
    icon: 'memory',
    links: {
      docs: 'https://help.salesforce.com/s/articleView?id=ai.agentforce_voice.htm&type=5',
      setupDocs: 'https://help.salesforce.com/s/articleView?id=ai.agent_connect_telephony_parent.htm&type=5',
      devGuide: 'https://developer.salesforce.com/docs/platform/agentforce/overview',
      partnerGuide: 'https://developer.salesforce.com/docs/platform/agentforce-partners/guide/agentforce-voice-overview',
      trailhead: null,
      video: null,
    },
    setupRequirements: 'Service Cloud Voice must be turned on (complete setup not required for CCaaS); configure Agentforce Service Agent in Agent Builder or Legacy Builder; connect telephony system (Amazon Connect, Genesys, CCaaS partners); full Service Cloud Voice setup enables seamless agent escalation and context passing',
    jobsToBeDone: ['scale-ops', 'automate', 'reduce-cost'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'email-templates',
    symbol: 'Et',
    name: 'Email Templates',
    fullName: 'Einstein Email Templates',
    era: 'generative',
    channels: ['email'],
    description: 'Helps admins generate beautiful, context-relevant email templates in seconds.',
    storyline: ['Admin needs "Renewal" template', 'Einstein drafts HTML & text', 'Template deployed across org'],
    useCases: ['Faster setup', 'Better formatting'],
    specs: { type: 'Content creation', grounding: 'Org Metadata' },
    icon: 'auto_awesome',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['automate', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'next-best-action',
    symbol: 'Nb',
    name: 'Next Best Action',
    fullName: 'Einstein Next Best Action',
    era: 'predictive',
    channels: ['field_service'],
    description: 'Recommends optimal up-sell and cross-sell opportunities at the moment of job completion.',
    storyline: ['Technician finishes repair', 'Einstein suggests "Battery Upgrade"', 'Technician adds to work order'],
    useCases: ['Increasing field revenue', 'Proactive maintenance'],
    specs: { tech: 'Recommendation Engine', ui: 'App & Console' },
    icon: 'analytics',
    links: {
      trailhead: 'https://trailhead.salesforce.com/users/rodrigovp97/trailmixes/next-best-action',
      docs: null,
      video: null,
    },
    setupRequirements: null,
    jobsToBeDone: ['increase-revenue', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'recommend-builder',
    symbol: 'Rb',
    name: 'Recommend Builder',
    fullName: 'Einstein Recommendation Builder',
    era: 'predictive',
    channels: ['field_service'],
    description: 'Allows builds of custom recommendation models to predict parts, skills, or objects for field jobs.',
    storyline: ['Historical work orders analyzed', 'Einstein predicts "Skill: HVAC Senior"', 'Dispatcher assigns correctly'],
    useCases: ['Optimizing first-time fix rates', 'Resource allocation'],
    specs: { tool: 'Declarative Builder', target: 'Any Standard Object' },
    icon: 'analytics',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['automate', 'empower-agents'],
    maturityLevel: 'foundation',
  },
  {
    id: 'pre-work-brief',
    symbol: 'Pb',
    name: 'Pre-Work Brief',
    fullName: 'Pre-Work Brief (GenAI)',
    era: 'generative',
    channels: ['field_service'],
    description: 'Gathers all customer history and asset info into a short, easy-to-read brief for a mobile technician.',
    storyline: ['Technician arrives on site', 'Opens mobile phone', 'GenAI gives 3-point summary of asset history'],
    useCases: ['Better prepared technicians', 'Enhanced customer experience'],
    specs: { output: 'Mobile Optimized', source: 'Asset & Case History' },
    icon: 'auto_awesome',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['empower-agents', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'fs-agent',
    symbol: 'Af',
    name: 'FS Agent',
    fullName: 'Agentforce Field Service Agent',
    era: 'agentic',
    channels: ['field_service'],
    description: 'An autonomous agent that manages technician questions and administrative field tasks.',
    storyline: ['Technician asks "How many bolts?"', 'Agent checks PDF manual', 'Agent supplies specs instantly'],
    useCases: ['Mobile self-sufficiency', 'Reduced back-office calls'],
    specs: { tech: 'Retrieval Augmented Plan', ui: 'FSL Mobile App' },
    icon: 'memory',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['empower-agents', 'reduce-cost'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'scheduling-agent',
    symbol: 'As',
    name: 'Scheduling Agent',
    fullName: 'Agentforce Scheduling Agent',
    era: 'agentic',
    channels: ['field_service'],
    description: 'Manages complex rescheduling and scheduling tasks autonomously for customers.',
    storyline: ["Customer texts 'Can't make it'", 'Agent finds new slot', 'Agent updates job in FSL'],
    useCases: ['Appointment flexibility', 'Dispatcher relief'],
    specs: { logic: 'Optimization Engine', flow: 'Conversational' },
    icon: 'memory',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['automate', 'increase-csat'],
    maturityLevel: 'autonomous',
  },
  {
    id: 'knowledge-edits',
    symbol: 'Ke',
    name: 'Knowledge Edits',
    fullName: 'Einstein Knowledge Edits',
    era: 'generative',
    channels: ['knowledge'],
    description: 'Helps knowledge managers rewrite, shorten, or change the tone of existing articles.',
    storyline: ['Clunky article text highlighted', 'Einstein rewrites for clarity', 'Manager publishes professional version'],
    useCases: ['Faster article lifecycle', 'Better readability'],
    specs: { feature: 'Tone & Style control', tool: 'Knowledge Console' },
    icon: 'auto_awesome',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['automate', 'reduce-time'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'service-ai-grounding',
    symbol: 'Sg',
    name: 'Service AI Grounding',
    fullName: 'Service AI Grounding',
    era: 'generative',
    channels: ['knowledge', 'cases'],
    description: 'Grounds generative AI responses in verified Salesforce Knowledge articles and CRM data to ensure accurate, trusted outputs.',
    storyline: ['Agent or bot asks a question', 'Einstein Trust Layer retrieves grounding data', 'GenAI generates a grounded, accurate response'],
    useCases: ['Trusted AI outputs', 'Reducing hallucinations'],
    specs: { tech: 'RAG + Einstein Trust Layer', source: 'Knowledge + CRM' },
    icon: 'auto_awesome',
    links: {
      trailhead: 'https://trailhead.salesforce.com/content/learn/modules/grounding-an-agent-with-data',
      docs: null,
      video: null,
    },
    setupRequirements: null,
    jobsToBeDone: ['improve-data', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
  {
    id: 'real-time-translations',
    symbol: 'Rt',
    name: 'Real-Time Translations',
    fullName: 'Real-Time Translations',
    era: 'generative',
    channels: ['messaging'],
    description: 'Translates customer and agent messages in real-time during messaging conversations, enabling cross-language support.',
    storyline: ['Customer messages in Spanish', "GenAI translates to agent's language", 'Agent replies and customer sees translation'],
    useCases: ['Global customer support', 'Eliminating language barriers'],
    specs: { type: 'Real-time translation', channel: 'Messaging' },
    icon: 'auto_awesome',
    links: { trailhead: null, docs: null, video: null },
    setupRequirements: null,
    jobsToBeDone: ['scale-ops', 'increase-csat'],
    maturityLevel: 'augmentation',
  },
];
